// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "packages",
    "uuid": "b7d08a1b-9491-89a3-a0d9-c1c72b5a9149",
    "words": [
      "packages"
    ],
    "values": {
      "en": "packages"
    }
  },
  {
    "key": "description",
    "source": "Use when modelling the packing hierarchy for a shipment — GS1 SSCC serial shipping container codes, self-referential nesting (pallet → carton → contents), dimensions/weight, item-lot lines, and UN/CEFACT packaging codes. The logistic handling-unit collection that links line items to a shipment.",
    "uuid": "a3d73cf8-bc94-81f9-9342-ea4454a4b243",
    "words": [
      "use",
      "when",
      "modelling",
      "the",
      "packing",
      "hierarchy",
      "for",
      "a",
      "shipment",
      "gs1",
      "sscc",
      "serial",
      "shipping",
      "container",
      "codes",
      "self",
      "referential",
      "nesting",
      "pallet",
      "carton",
      "contents",
      "dimensions",
      "weight",
      "item",
      "lot",
      "lines",
      "and",
      "un",
      "cefact",
      "packaging",
      "codes",
      "the",
      "logistic",
      "handling",
      "unit",
      "collection",
      "that",
      "links",
      "line",
      "items",
      "to",
      "a",
      "shipment"
    ],
    "values": {
      "en": "Use when modelling the packing hierarchy for a shipment — GS1 SSCC serial shipping container codes, self-referential nesting (pallet → carton → contents), dimensions/weight, item-lot lines, and UN/CEFACT packaging codes. The logistic handling-unit collection that links line items to a shipment."
    }
  }
]

export default translations
