// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "bank",
    "uuid": "b27d6c5c-978f-8d23-8f59-1cd44ddaf7ea",
    "words": [
      "bank"
    ],
    "values": {
      "en": "bank"
    }
  },
  {
    "key": "description",
    "source": "Use when a transaction or account references banking infrastructure — bank account, bank statement, bank transfer, bank reconciliation. A financial institution context; relationTo: 'bank-accounts' or similar.",
    "uuid": "a076a205-2b2c-8e11-981c-23625a0d568d",
    "words": [
      "use",
      "when",
      "a",
      "transaction",
      "or",
      "account",
      "references",
      "banking",
      "infrastructure",
      "bank",
      "account",
      "bank",
      "statement",
      "bank",
      "transfer",
      "bank",
      "reconciliation",
      "a",
      "financial",
      "institution",
      "context",
      "relationto",
      "bank",
      "accounts",
      "or",
      "similar"
    ],
    "values": {
      "en": "Use when a transaction or account references banking infrastructure — bank account, bank statement, bank transfer, bank reconciliation. A financial institution context; relationTo: 'bank-accounts' or similar."
    }
  }
]

export default translations
