// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "discount",
    "uuid": "ac5c5a55-1e06-89cc-a54b-f6ff7ca551c3",
    "words": [
      "discount"
    ],
    "values": {
      "en": "discount"
    }
  },
  {
    "key": "description",
    "source": "Use when applying promotional/volume/loyalty price reductions — percent or fixed amount, scope (item/order/customer), validity period, approval workflow.",
    "uuid": "e2900941-0acc-89af-ab3a-9d7099c6f9b1",
    "words": [
      "use",
      "when",
      "applying",
      "promotional",
      "volume",
      "loyalty",
      "price",
      "reductions",
      "percent",
      "or",
      "fixed",
      "amount",
      "scope",
      "item",
      "order",
      "customer",
      "validity",
      "period",
      "approval",
      "workflow"
    ],
    "values": {
      "en": "Use when applying promotional/volume/loyalty price reductions — percent or fixed amount, scope (item/order/customer), validity period, approval workflow."
    }
  }
]

export default translations
