// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "wire",
    "uuid": "6e695d9f-7d30-8529-b787-676e8b155ff2",
    "words": [
      "wire"
    ],
    "values": {
      "en": "wire"
    }
  },
  {
    "key": "description",
    "source": "Use when a reader receives the erpax GitHub URL — wireFromRepoUrl validates github.com/erpax/erpax and returns the canonical skill entry paths (content-uuid sealed). All orientation surfaces point to .claude/skills/SKILL.md; paste or clone.",
    "uuid": "9d6df213-3f6c-8ed4-b70b-31ca434bf564",
    "words": [
      "use",
      "when",
      "a",
      "reader",
      "receives",
      "the",
      "erpax",
      "github",
      "url",
      "wirefromrepourl",
      "validates",
      "github",
      "com",
      "erpax",
      "erpax",
      "and",
      "returns",
      "the",
      "canonical",
      "skill",
      "entry",
      "paths",
      "content",
      "uuid",
      "sealed",
      "all",
      "orientation",
      "surfaces",
      "point",
      "to",
      "claude",
      "skills",
      "skill",
      "md",
      "paste",
      "or",
      "clone"
    ],
    "values": {
      "en": "Use when a reader receives the erpax GitHub URL — wireFromRepoUrl validates github.com/erpax/erpax and returns the canonical skill entry paths (content-uuid sealed). All orientation surfaces point to .claude/skills/SKILL.md; paste or clone."
    }
  }
]

export default translations
