// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "procedure",
    "uuid": "d3adde63-790e-893b-a167-c804588a45fe",
    "words": [
      "procedure"
    ],
    "values": {
      "en": "procedure"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about procedure as a medical facet of medical — vocabulary pivot to @/procedure; nested not duplicated.",
    "uuid": "5a34db34-ee7b-8743-9ed4-139c7532344f",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "procedure",
      "as",
      "a",
      "medical",
      "facet",
      "of",
      "medical",
      "vocabulary",
      "pivot",
      "to",
      "procedure",
      "nested",
      "not",
      "duplicated"
    ],
    "values": {
      "en": "Use when reasoning about procedure as a medical facet of medical — vocabulary pivot to @/procedure; nested not duplicated."
    }
  }
]

export default translations
