// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "letterer",
    "uuid": "be66f0ff-8949-83ba-aa98-b49fc4213282",
    "words": [
      "letterer"
    ],
    "values": {
      "en": "letterer"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about letterer — The individual who adds lettering, including speech balloons and sound effects, to artwork.",
    "uuid": "315c02ee-f8b9-8d6b-b43d-bcb663e3fb42",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "letterer",
      "the",
      "individual",
      "who",
      "adds",
      "lettering",
      "including",
      "speech",
      "balloons",
      "and",
      "sound",
      "effects",
      "to",
      "artwork"
    ],
    "values": {
      "en": "Use when reasoning about letterer — The individual who adds lettering, including speech balloons and sound effects, to artwork."
    }
  }
]

export default translations
