// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "close",
    "uuid": "4181cdbb-02df-8337-9125-f6a34a4cacfe",
    "words": [
      "close"
    ],
    "values": {
      "en": "close"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about the forbidding boundary state in erpax — fiscal period locked, document sealed, shift/stream finished, month-end close. The universal root of the closed state; dual of open.",
    "uuid": "0a375e98-d83a-8f5a-a185-ff78f0851a66",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "the",
      "forbidding",
      "boundary",
      "state",
      "in",
      "erpax",
      "fiscal",
      "period",
      "locked",
      "document",
      "sealed",
      "shift",
      "stream",
      "finished",
      "month",
      "end",
      "close",
      "the",
      "universal",
      "root",
      "of",
      "the",
      "closed",
      "state",
      "dual",
      "of",
      "open"
    ],
    "values": {
      "en": "Use when reasoning about the forbidding boundary state in erpax — fiscal period locked, document sealed, shift/stream finished, month-end close. The universal root of the closed state; dual of open."
    }
  }
]

export default translations
