// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "runs",
    "uuid": "771995b5-d910-8945-ae2d-b685708cdbf8",
    "words": [
      "runs"
    ],
    "values": {
      "en": "runs"
    }
  },
  {
    "key": "description",
    "source": "Use when processing, auditing, or posting a periodic payroll batch — aggregates approved TimeEntries, computes gross-to-net deductions and employer-side accruals, posts IAS-19/ASC-710 journal entries, emits a pain.001 disbursement file; SOX §404 four-eyes (preparer ≠ authoriser), GDPR-classified personal data. The payroll-run collection.",
    "uuid": "d7f4a810-df3a-8b7c-bd1e-f1cc54358cf1",
    "words": [
      "use",
      "when",
      "processing",
      "auditing",
      "or",
      "posting",
      "a",
      "periodic",
      "payroll",
      "batch",
      "aggregates",
      "approved",
      "timeentries",
      "computes",
      "gross",
      "to",
      "net",
      "deductions",
      "and",
      "employer",
      "side",
      "accruals",
      "posts",
      "ias",
      "asc",
      "journal",
      "entries",
      "emits",
      "a",
      "pain",
      "disbursement",
      "file",
      "sox",
      "four",
      "eyes",
      "preparer",
      "authoriser",
      "gdpr",
      "classified",
      "personal",
      "data",
      "the",
      "payroll",
      "run",
      "collection"
    ],
    "values": {
      "en": "Use when processing, auditing, or posting a periodic payroll batch — aggregates approved TimeEntries, computes gross-to-net deductions and employer-side accruals, posts IAS-19/ASC-710 journal entries, emits a pain.001 disbursement file; SOX §404 four-eyes (preparer ≠ authoriser), GDPR-classified personal data. The payroll-run collection."
    }
  }
]

export default translations
