// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "fold",
    "uuid": "afed248e-2d6e-8ef9-b4d6-e8bb478f68ab",
    "words": [
      "fold"
    ],
    "values": {
      "en": "fold"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about fold — Double fold is mandatory for quantum mentality: word ⊗ digit; 2D documents present both sheets until seal.",
    "uuid": "cc881889-9396-8212-9d6c-2b515cc61028",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "fold",
      "double",
      "fold",
      "is",
      "mandatory",
      "for",
      "quantum",
      "mentality",
      "word",
      "digit",
      "d",
      "documents",
      "present",
      "both",
      "sheets",
      "until",
      "seal"
    ],
    "values": {
      "en": "Use when reasoning about fold — Double fold is mandatory for quantum mentality: word ⊗ digit; 2D documents present both sheets until seal."
    }
  }
]

export default translations
