// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "slogan",
    "uuid": "90e9961f-3379-8e6e-b9a0-c5cb06c1ed8b",
    "words": [
      "slogan"
    ],
    "values": {
      "en": "slogan"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about slogan — A slogan or motto associated with the item.",
    "uuid": "84b05a8e-b95e-8809-928d-fd76ea3b4014",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "slogan",
      "a",
      "slogan",
      "or",
      "motto",
      "associated",
      "with",
      "the",
      "item"
    ],
    "values": {
      "en": "Use when reasoning about slogan — A slogan or motto associated with the item."
    }
  }
]

export default translations
