// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "slogan",
    "uuid": "70795578-32b5-87e4-a679-6e962d5f9516",
    "words": [
      "slogan"
    ],
    "values": {
      "en": "slogan"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about slogan — A slogan or motto associated with the item.",
    "uuid": "8a979367-a8d9-8023-b5f9-827aca448f51",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "slogan",
      "a",
      "slogan",
      "or",
      "motto",
      "associated",
      "with",
      "the",
      "item"
    ],
    "values": {
      "en": "Use when reasoning about slogan — A slogan or motto associated with the item."
    }
  }
]

export default translations
