// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "documentation",
    "uuid": "940cf0ac-7b5c-8fd4-aa1d-7085b064c6e3",
    "words": [
      "documentation"
    ],
    "values": {
      "en": "documentation"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about documentation — Further documentation describing the Web API in more detail.",
    "uuid": "11c5a39a-f2fb-8d59-84ce-c59c66961116",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "documentation",
      "further",
      "documentation",
      "describing",
      "the",
      "web",
      "api",
      "in",
      "more",
      "detail"
    ],
    "values": {
      "en": "Use when reasoning about documentation — Further documentation describing the Web API in more detail."
    }
  }
]

export default translations
