// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "documentation",
    "uuid": "ce37c496-2838-86ac-94ec-5aac81c2cdca",
    "words": [
      "documentation"
    ],
    "values": {
      "en": "documentation"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about documentation — Further documentation describing the Web API in more detail.",
    "uuid": "b943b8b3-fac9-82e7-84e7-c73fa5a181c7",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "documentation",
      "further",
      "documentation",
      "describing",
      "the",
      "web",
      "api",
      "in",
      "more",
      "detail"
    ],
    "values": {
      "en": "Use when reasoning about documentation — Further documentation describing the Web API in more detail."
    }
  }
]

export default translations
