// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "terroir",
    "uuid": "c683a5d1-0bac-89dc-b102-41ea68f6bde1",
    "words": [
      "terroir"
    ],
    "values": {
      "en": "terroir"
    }
  },
  {
    "key": "description",
    "source": "Use when the place gives the produce its character and price — terroir: the area-specific soil, climate, topography, and practice that make a product distinctive (OIV). Expressed legally as the appellation / AVA / PDO (a certification over a delimited territory); the perennial/viticulture twin of provenance and a land-value premium.",
    "uuid": "9fc0211b-033c-8a2f-85e6-0b3317f56a0a",
    "words": [
      "use",
      "when",
      "the",
      "place",
      "gives",
      "the",
      "produce",
      "its",
      "character",
      "and",
      "price",
      "terroir",
      "the",
      "area",
      "specific",
      "soil",
      "climate",
      "topography",
      "and",
      "practice",
      "that",
      "make",
      "a",
      "product",
      "distinctive",
      "oiv",
      "expressed",
      "legally",
      "as",
      "the",
      "appellation",
      "ava",
      "pdo",
      "a",
      "certification",
      "over",
      "a",
      "delimited",
      "territory",
      "the",
      "perennial",
      "viticulture",
      "twin",
      "of",
      "provenance",
      "and",
      "a",
      "land",
      "value",
      "premium"
    ],
    "values": {
      "en": "Use when the place gives the produce its character and price — terroir: the area-specific soil, climate, topography, and practice that make a product distinctive (OIV). Expressed legally as the appellation / AVA / PDO (a certification over a delimited territory); the perennial/viticulture twin of provenance and a land-value premium."
    }
  }
]

export default translations
