// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "manure",
    "uuid": "41f240e8-a39e-83d5-ab69-616c64ccb5a0",
    "words": [
      "manure"
    ],
    "values": {
      "en": "manure"
    }
  },
  {
    "key": "description",
    "source": "Use when the animal byproduct cycles back to the soil — manure (excreta) as the nutrient output that closes the livestock→soil fertility loop, applied or deposited by grazing; the nutrient-management plan balances it to the land. The waste-to-fertility recycling node, the livestock twin of compost.",
    "uuid": "860c30ba-8eb5-8f60-bff3-54777a226575",
    "words": [
      "use",
      "when",
      "the",
      "animal",
      "byproduct",
      "cycles",
      "back",
      "to",
      "the",
      "soil",
      "manure",
      "excreta",
      "as",
      "the",
      "nutrient",
      "output",
      "that",
      "closes",
      "the",
      "livestock",
      "soil",
      "fertility",
      "loop",
      "applied",
      "or",
      "deposited",
      "by",
      "grazing",
      "the",
      "nutrient",
      "management",
      "plan",
      "balances",
      "it",
      "to",
      "the",
      "land",
      "the",
      "waste",
      "to",
      "fertility",
      "recycling",
      "node",
      "the",
      "livestock",
      "twin",
      "of",
      "compost"
    ],
    "values": {
      "en": "Use when the animal byproduct cycles back to the soil — manure (excreta) as the nutrient output that closes the livestock→soil fertility loop, applied or deposited by grazing; the nutrient-management plan balances it to the land. The waste-to-fertility recycling node, the livestock twin of compost."
    }
  }
]

export default translations
