// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "observation",
    "uuid": "3f956644-61d0-8499-8c09-6582ccdee0fa",
    "words": [
      "observation"
    ],
    "values": {
      "en": "observation"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about observation — Instances of the class Observation are used to specify observations about an entity at a particular time. The principal properties of an Observation are observationAbout, measuredP",
    "uuid": "63a1d56c-ba54-84f8-a82b-500512be56da",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "observation",
      "instances",
      "of",
      "the",
      "class",
      "observation",
      "are",
      "used",
      "to",
      "specify",
      "observations",
      "about",
      "an",
      "entity",
      "at",
      "a",
      "particular",
      "time",
      "the",
      "principal",
      "properties",
      "of",
      "an",
      "observation",
      "are",
      "observationabout",
      "measuredp"
    ],
    "values": {
      "en": "Use when reasoning about observation — Instances of the class Observation are used to specify observations about an entity at a particular time. The principal properties of an Observation are observationAbout, measuredP"
    }
  }
]

export default translations
