// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "jurisdictions",
    "uuid": "1123ad54-cbf4-8bf2-b965-b5880da3912f",
    "words": [
      "jurisdictions"
    ],
    "values": {
      "en": "jurisdictions"
    }
  },
  {
    "key": "description",
    "source": "Use when looking up or seeding read-only reference data for tax authority geographies — country, region, local and supranational levels with ISO-3166 codes, primary currency, languages, regulatory characteristics, banking requirements, filing deadlines and applicable compliance frameworks. The super-admin-maintained jurisdiction reference collection.",
    "uuid": "e1e1c05a-1f77-8458-ba5b-d657424d68b3",
    "words": [
      "use",
      "when",
      "looking",
      "up",
      "or",
      "seeding",
      "read",
      "only",
      "reference",
      "data",
      "for",
      "tax",
      "authority",
      "geographies",
      "country",
      "region",
      "local",
      "and",
      "supranational",
      "levels",
      "with",
      "iso",
      "codes",
      "primary",
      "currency",
      "languages",
      "regulatory",
      "characteristics",
      "banking",
      "requirements",
      "filing",
      "deadlines",
      "and",
      "applicable",
      "compliance",
      "frameworks",
      "the",
      "super",
      "admin",
      "maintained",
      "jurisdiction",
      "reference",
      "collection"
    ],
    "values": {
      "en": "Use when looking up or seeding read-only reference data for tax authority geographies — country, region, local and supranational levels with ISO-3166 codes, primary currency, languages, regulatory characteristics, banking requirements, filing deadlines and applicable compliance frameworks. The super-admin-maintained jurisdiction reference collection."
    }
  }
]

export default translations
