// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "boundary",
    "uuid": "f4ce78bd-7604-87c6-8aa8-c1d54f7cac2d",
    "words": [
      "boundary"
    ],
    "values": {
      "en": "boundary"
    }
  },
  {
    "key": "description",
    "source": "Use when computing per-file quantum import/export boundaries — barrel entanglements and export facets derived from source bytes, content-addressed as boundaryUuid; drift is impurity; collapse rewrites deep escapes to raise tamper-cost.",
    "uuid": "fed4ee8d-b9f0-8745-8184-97b6885e28e7",
    "words": [
      "use",
      "when",
      "computing",
      "per",
      "file",
      "quantum",
      "import",
      "export",
      "boundaries",
      "barrel",
      "entanglements",
      "and",
      "export",
      "facets",
      "derived",
      "from",
      "source",
      "bytes",
      "content",
      "addressed",
      "as",
      "boundaryuuid",
      "drift",
      "is",
      "impurity",
      "collapse",
      "rewrites",
      "deep",
      "escapes",
      "to",
      "raise",
      "tamper",
      "cost"
    ],
    "values": {
      "en": "Use when computing per-file quantum import/export boundaries — barrel entanglements and export facets derived from source bytes, content-addressed as boundaryUuid; drift is impurity; collapse rewrites deep escapes to raise tamper-cost."
    }
  }
]

export default translations
