import type { CountryApi } from '@/country/api'
/**
 * country/api/world — the non-EU (world) slice of the country-authority registry.
 *
 * Split from the country/api hub so its index.ts stays a thin barrel
 * ([[rules]]/concentration). Pure data keyed by ISO-3166 country; the parent
 * merges the slices into COUNTRY_APIS and owns the lookup functions. Type-only
 * import back to the parent — erased at runtime, so no cycle.
 */
export const WORLD_COUNTRY_APIS: Readonly<Record<string, ReadonlyArray<CountryApi>>> = {
  AU: [
    {
      kind: 'business_registry',
      name: 'ABN Lookup',
      authority: 'Australian Business Register',
      endpoint: 'https://abr.business.gov.au/json',
      auth: 'api_key',
      format: 'json',
      documentation: 'https://abr.business.gov.au/Tools/WebServices',
      description: 'Lookup a registered ABN/ACN and trading name.',
      clientImplemented: true,
    },
    {
      kind: 'tax_authority',
      name: 'ATO Online Services',
      authority: 'Australian Taxation Office',
      endpoint: 'https://api.ato.gov.au',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://softwaredevelopers.ato.gov.au/',
      description: 'BAS lodgement, STP payroll, super reporting (M2M auth via SBR).',
      clientImplemented: false,
    },
  ],
  BR: [
    {
      kind: 'business_registry',
      name: 'CNPJ Receita Federal',
      authority: 'Receita Federal do Brasil',
      endpoint: 'https://www.receitaws.com.br/v1/cnpj',
      auth: 'none',
      format: 'json',
      documentation: 'https://receitaws.com.br/',
      description: 'CNPJ lookup (community proxy over RF data).',
      // No client module ships for this rail — `clientImplemented` means
      // "src/country/api/client/ ships a working module", and none fetches this
      // endpoint. It was `true`, which counted the rail as a promise erpax had
      // not made: catalogue-only is the honest state ([[outward]]/coverage).
      clientImplemented: false,
    },
    {
      kind: 'e_invoicing',
      name: 'NFe / NFSe SEFAZ',
      authority: 'Secretarias da Fazenda Estaduais',
      endpoint: 'https://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx', // varies per state
      auth: 'mtls',
      format: 'xml',
      documentation: 'https://www.nfe.fazenda.gov.br/portal/principal.aspx',
      description: 'Per-state NFe issuance + SEFAZ clearance (mTLS A1/A3 cert).',
      clientImplemented: false,
    },
  ],
  CA: [
    {
      kind: 'business_registry',
      name: 'CRA Business Number Validation',
      authority: 'Canada Revenue Agency',
      endpoint: 'https://api.canada.ca/businesses/v1/businesses',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://www.canada.ca/en/revenue-agency.html',
      description: 'Validate a CRA Business Number / GST/HST registration.',
      clientImplemented: false,
    },
  ],
  CN: [
    {
      kind: 'tax_authority',
      name: '电子税务局',
      authority: 'State Taxation Administration (STA)',
      endpoint: 'https://etax.chinatax.gov.cn',
      auth: 'jwt_signed',
      format: 'json',
      documentation: 'https://www.chinatax.gov.cn/',
      description: 'STA electronic tax bureau, fully-electronic invoice submission.',
      clientImplemented: false,
    },
  ],
  GB: [
    {
      kind: 'business_registry',
      name: 'Companies House',
      authority: 'Companies House',
      endpoint: 'https://api.company-information.service.gov.uk',
      auth: 'api_key',
      format: 'json',
      documentation: 'https://developer.company-information.service.gov.uk/',
      description: 'UK company search, officers, filings — free key-based REST API.',
      clientImplemented: true,
    },
    {
      kind: 'tax_authority',
      name: 'HMRC MTD',
      authority: 'HM Revenue & Customs',
      endpoint: 'https://api.service.hmrc.gov.uk',
      sandboxEndpoint: 'https://test-api.service.hmrc.gov.uk',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.service.hmrc.gov.uk/api-documentation',
      description: 'Making Tax Digital VAT, ITSA, corporation tax APIs.',
      clientImplemented: false,
    },
  ],
  HK: [
    {
      kind: 'business_registry',
      name: 'Cyber Search Centre',
      authority: 'HK Companies Registry',
      endpoint: 'https://www.icris.cr.gov.hk/csci/',
      auth: 'api_key',
      format: 'mixed',
      documentation: 'https://www.cr.gov.hk/',
      description: 'Hong Kong CR Cyber Search (paid per query, account-based).',
      clientImplemented: false,
    },
  ],
  IN: [
    {
      kind: 'business_registry',
      name: 'MCA21',
      authority: 'Ministry of Corporate Affairs',
      endpoint: 'https://www.mca.gov.in',
      auth: 'api_key',
      format: 'mixed',
      documentation: 'https://www.mca.gov.in/MinistryV2/companyllpmasterdata.html',
      description: 'CIN / LLPIN master data lookup.',
      clientImplemented: false,
    },
    {
      kind: 'e_invoicing',
      name: 'GST e-Invoice IRP',
      authority: 'Goods and Services Tax Network',
      endpoint: 'https://einvoice1.gst.gov.in/api',
      sandboxEndpoint: 'https://einv-apisandbox.nic.in',
      auth: 'jwt_signed',
      format: 'json',
      documentation: 'https://einv-apisandbox.nic.in/',
      description: 'IRN generation + e-invoice clearance (mandatory ≥ INR 5cr turnover).',
      clientImplemented: false,
    },
  ],
  JP: [
    {
      kind: 'business_registry',
      name: '法人番号公表サイト',
      authority: 'National Tax Agency',
      endpoint: 'https://api.houjin-bangou.nta.go.jp/4',
      auth: 'api_key',
      format: 'mixed',
      documentation: 'https://www.houjin-bangou.nta.go.jp/webapi/',
      description: 'NTA corporate-number public API (free key registration).',
      clientImplemented: true,
    },
    {
      kind: 'tax_authority',
      name: 'e-Tax',
      authority: 'National Tax Agency',
      endpoint: 'https://www.e-tax.nta.go.jp',
      auth: 'jwt_signed',
      format: 'xml',
      documentation: 'https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/hojin/annai/13_01.htm',
      description: 'e-Tax filing for corp tax, consumption tax, withholding.',
      clientImplemented: false,
    },
  ],
  MX: [
    {
      kind: 'e_invoicing',
      name: 'CFDI 4.0 PAC',
      authority: 'Servicio de Administración Tributaria',
      endpoint: 'https://cfdi.sat.gob.mx',
      auth: 'mtls',
      format: 'xml',
      documentation: 'https://www.sat.gob.mx',
      description: 'CFDI issuance through Authorised Certification Providers (PACs).',
      clientImplemented: false,
    },
    {
      kind: 'business_registry',
      name: 'RFC Constancia',
      authority: 'SAT',
      endpoint: 'https://siat.sat.gob.mx/PTSC/IdcSiat',
      auth: 'mtls',
      format: 'mixed',
      documentation: 'https://www.sat.gob.mx',
      description: 'RFC validity + Constancia de Situación Fiscal.',
      clientImplemented: false,
    },
  ],
  NO: [
    {
      kind: 'business_registry',
      name: 'Brønnøysundregistrene (Brreg)',
      authority: 'Brønnøysundregistrene',
      endpoint: 'https://data.brreg.no/enhetsregisteret/api',
      auth: 'none',
      format: 'json',
      documentation: 'https://data.brreg.no/enhetsregisteret/api/dokumentasjon/no/index.html',
      description: 'Free open API for Norwegian Central Coordinating Register.',
      clientImplemented: true,
    },
  ],
  NZ: [
    {
      kind: 'business_registry',
      name: 'NZBN',
      authority: 'Companies Office',
      endpoint: 'https://api.business.govt.nz/services/v5/nzbn',
      auth: 'api_key',
      format: 'json',
      documentation: 'https://api.business.govt.nz/',
      description: 'Lookup by NZBN; addresses, classification, status.',
      clientImplemented: true,
    },
  ],
  SG: [
    {
      kind: 'business_registry',
      name: 'ACRA Bizfile',
      authority: 'Accounting and Corporate Regulatory Authority',
      endpoint: 'https://www.acra.gov.sg/api',
      auth: 'api_key',
      format: 'json',
      documentation: 'https://www.acra.gov.sg/services/api',
      description: 'UEN / business profile lookup (paid per profile).',
      clientImplemented: false,
    },
    {
      kind: 'e_invoicing',
      name: 'InvoiceNow Peppol',
      authority: 'IMDA',
      endpoint: 'https://www.imda.gov.sg/InvoiceNow',
      auth: 'oauth2',
      format: 'xml',
      documentation: 'https://www.peppol.org/who-is-who/peppol-authorities',
      description: 'Singapore Peppol authority — InvoiceNow B2G + voluntary B2B.',
      clientImplemented: false,
    },
  ],
  US: [
    {
      kind: 'sanctions',
      name: 'OFAC SDN List',
      authority: 'US Treasury OFAC',
      endpoint: 'https://www.treasury.gov/ofac/downloads/sdn.xml',
      auth: 'none',
      format: 'xml',
      documentation: 'https://ofac.treasury.gov/',
      description: 'Specially Designated Nationals list (daily refresh).',
      clientImplemented: true,
    },
    {
      kind: 'business_registry',
      name: 'SEC EDGAR',
      authority: 'Securities and Exchange Commission',
      endpoint: 'https://data.sec.gov',
      auth: 'none',
      format: 'json',
      documentation: 'https://www.sec.gov/edgar/sec-api-documentation',
      description: 'Public-company filings, financial-statement facts (XBRL).',
      clientImplemented: true,
    },
    {
      kind: 'tax_authority',
      name: 'IRS MeF',
      authority: 'Internal Revenue Service',
      endpoint: 'https://la.www4.irs.gov/a2a/mef/api',
      auth: 'mtls',
      format: 'xml',
      documentation: 'https://www.irs.gov/e-file-providers/modernized-e-file-mef-internet-filing',
      description: 'IRS Modernized e-File for 1120/1065/941/990 series.',
      clientImplemented: false,
    },
  ],
}
