// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "city",
    "uuid": "0718892c-f8c7-84d7-bf0d-33addd28c80f",
    "words": [
      "city"
    ],
    "values": {
      "en": "city"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about city — A city or town.",
    "uuid": "3661da4f-c9e2-8da4-b531-a3307b9ba0e5",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "city",
      "a",
      "city",
      "or",
      "town"
    ],
    "values": {
      "en": "Use when reasoning about city — A city or town."
    }
  }
]

export default translations
