overrides:
  dompurify: latest
  uuid: latest
  esbuild: latest
  ip-address: latest
  '@eslint/plugin-kit': latest
  postcss: latest

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
  workerd: true
