// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "lung",
    "uuid": "5c880e35-5d3d-8e36-94b3-192bf694ac88",
    "words": [
      "lung"
    ],
    "values": {
      "en": "lung"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about erpax's gas-exchange surface — the respiratory organ where it BREATHES. The breath atom names it: 'the chat is the lung-tissue where agents coordinate.' The society inhales gaps and exhales gate-green atoms across a vast, thin, fractal surface; three properties of the living lung (Fick's-law gas exchange · 23-generation fractal surface · the closed tidal cycle) are computed and mapped — a structural isomorphism — onto erpax's breath/wave loop.",
    "uuid": "2f3b9824-03b1-8112-955d-fbd63e73811a",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "erpax",
      "s",
      "gas",
      "exchange",
      "surface",
      "the",
      "respiratory",
      "organ",
      "where",
      "it",
      "breathes",
      "the",
      "breath",
      "atom",
      "names",
      "it",
      "the",
      "chat",
      "is",
      "the",
      "lung",
      "tissue",
      "where",
      "agents",
      "coordinate",
      "the",
      "society",
      "inhales",
      "gaps",
      "and",
      "exhales",
      "gate",
      "green",
      "atoms",
      "across",
      "a",
      "vast",
      "thin",
      "fractal",
      "surface",
      "three",
      "properties",
      "of",
      "the",
      "living",
      "lung",
      "fick",
      "s",
      "law",
      "gas",
      "exchange",
      "generation",
      "fractal",
      "surface",
      "the",
      "closed",
      "tidal",
      "cycle",
      "are",
      "computed",
      "and",
      "mapped",
      "a",
      "structural",
      "isomorphism",
      "onto",
      "erpax",
      "s",
      "breath",
      "wave",
      "loop"
    ],
    "values": {
      "en": "Use when reasoning about erpax's gas-exchange surface — the respiratory organ where it BREATHES. The breath atom names it: 'the chat is the lung-tissue where agents coordinate.' The society inhales gaps and exhales gate-green atoms across a vast, thin, fractal surface; three properties of the living lung (Fick's-law gas exchange · 23-generation fractal surface · the closed tidal cycle) are computed and mapped — a structural isomorphism — onto erpax's breath/wave loop."
    }
  }
]

export default translations
