// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "algorithm",
    "uuid": "8a6b58d2-d239-85b6-9132-2261513e6686",
    "words": [
      "algorithm"
    ],
    "values": {
      "en": "algorithm"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about algorithm — The algorithm or rules to follow to compute the score.",
    "uuid": "4f6f4b05-9703-82c1-8ed1-19d18c6addb0",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "algorithm",
      "the",
      "algorithm",
      "or",
      "rules",
      "to",
      "follow",
      "to",
      "compute",
      "the",
      "score"
    ],
    "values": {
      "en": "Use when reasoning about algorithm — The algorithm or rules to follow to compute the score."
    }
  }
]

export default translations
