// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "vocabulary",
    "uuid": "f2a288a9-a379-80d8-a308-ec65234d7110",
    "words": [
      "vocabulary"
    ],
    "values": {
      "en": "vocabulary"
    }
  },
  {
    "key": "description",
    "source": "Use when checking that every word in the corpus comes from the shared standards-grounded vocabulary — the dictionary, schema.org, standard codes, and established domain terms. Whatever the language, words are written only from this one scheme; an ungrounded word is entropy, and the audit computes its zero-entropy solution.",
    "uuid": "778c3492-3d19-8074-a99c-bc2ba49bd757",
    "words": [
      "use",
      "when",
      "checking",
      "that",
      "every",
      "word",
      "in",
      "the",
      "corpus",
      "comes",
      "from",
      "the",
      "shared",
      "standards",
      "grounded",
      "vocabulary",
      "the",
      "dictionary",
      "schema",
      "org",
      "standard",
      "codes",
      "and",
      "established",
      "domain",
      "terms",
      "whatever",
      "the",
      "language",
      "words",
      "are",
      "written",
      "only",
      "from",
      "this",
      "one",
      "scheme",
      "an",
      "ungrounded",
      "word",
      "is",
      "entropy",
      "and",
      "the",
      "audit",
      "computes",
      "its",
      "zero",
      "entropy",
      "solution"
    ],
    "values": {
      "en": "Use when checking that every word in the corpus comes from the shared standards-grounded vocabulary — the dictionary, schema.org, standard codes, and established domain terms. Whatever the language, words are written only from this one scheme; an ungrounded word is entropy, and the audit computes its zero-entropy solution."
    }
  }
]

export default translations
