// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "activities",
    "uuid": "81fb59e8-808c-8f7a-930c-7133d34779dc",
    "words": [
      "activities"
    ],
    "values": {
      "en": "activities"
    }
  },
  {
    "key": "description",
    "source": "Use when maintaining the GDPR Art.30 Records of Processing Activities (RoPA) — documenting each processing activity's purpose, lawful basis, data categories, retention period, third-country transfer safeguards, and scheduling annual DPO reviews. The controller/processor RoPA register.",
    "uuid": "5a4f5cfe-ead7-8a86-a378-c53c5f83ed87",
    "words": [
      "use",
      "when",
      "maintaining",
      "the",
      "gdpr",
      "art",
      "records",
      "of",
      "processing",
      "activities",
      "ropa",
      "documenting",
      "each",
      "processing",
      "activity",
      "s",
      "purpose",
      "lawful",
      "basis",
      "data",
      "categories",
      "retention",
      "period",
      "third",
      "country",
      "transfer",
      "safeguards",
      "and",
      "scheduling",
      "annual",
      "dpo",
      "reviews",
      "the",
      "controller",
      "processor",
      "ropa",
      "register"
    ],
    "values": {
      "en": "Use when maintaining the GDPR Art.30 Records of Processing Activities (RoPA) — documenting each processing activity's purpose, lawful basis, data categories, retention period, third-country transfer safeguards, and scheduling annual DPO reviews. The controller/processor RoPA register."
    }
  }
]

export default translations
