// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "lichen",
    "uuid": "a94ac797-8409-8657-92bf-af94b4f0db59",
    "words": [
      "lichen"
    ],
    "values": {
      "en": "lichen"
    }
  },
  {
    "key": "description",
    "source": "Use when one 'organism' is really a committee — a lichen is a fungus plus a photosynthetic partner (and often a yeast) living as a single composite body, the textbook case that the INDIVIDUAL is a question, not a given. Symbiosis incarnate; the natural twin of erpax's actor-merge (one identity, many partners).",
    "uuid": "894e41cc-4657-8234-9a43-9eb4f702dfca",
    "words": [
      "use",
      "when",
      "one",
      "organism",
      "is",
      "really",
      "a",
      "committee",
      "a",
      "lichen",
      "is",
      "a",
      "fungus",
      "plus",
      "a",
      "photosynthetic",
      "partner",
      "and",
      "often",
      "a",
      "yeast",
      "living",
      "as",
      "a",
      "single",
      "composite",
      "body",
      "the",
      "textbook",
      "case",
      "that",
      "the",
      "individual",
      "is",
      "a",
      "question",
      "not",
      "a",
      "given",
      "symbiosis",
      "incarnate",
      "the",
      "natural",
      "twin",
      "of",
      "erpax",
      "s",
      "actor",
      "merge",
      "one",
      "identity",
      "many",
      "partners"
    ],
    "values": {
      "en": "Use when one 'organism' is really a committee — a lichen is a fungus plus a photosynthetic partner (and often a yeast) living as a single composite body, the textbook case that the INDIVIDUAL is a question, not a given. Symbiosis incarnate; the natural twin of erpax's actor-merge (one identity, many partners)."
    }
  }
]

export default translations
