// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "word",
    "uuid": "093f26b7-394e-8578-8fa7-732c6b7c7753",
    "words": [
      "word"
    ],
    "values": {
      "en": "word"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about the WORD half of the double-torus — one 64-bit address architecture (folder name / aura / link space) that vortexes with the digit architecture into the 128-bit content-uuid; interact64 ANDs the two torus halves, architectureBond entangles word ⊕ digit on the matrix.",
    "uuid": "cc874efe-4fbb-85ff-90a8-506c0340fd5a",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "the",
      "word",
      "half",
      "of",
      "the",
      "double",
      "torus",
      "one",
      "bit",
      "address",
      "architecture",
      "folder",
      "name",
      "aura",
      "link",
      "space",
      "that",
      "vortexes",
      "with",
      "the",
      "digit",
      "architecture",
      "into",
      "the",
      "bit",
      "content",
      "uuid",
      "interact64",
      "ands",
      "the",
      "two",
      "torus",
      "halves",
      "architecturebond",
      "entangles",
      "word",
      "digit",
      "on",
      "the",
      "matrix"
    ],
    "values": {
      "en": "Use when reasoning about the WORD half of the double-torus — one 64-bit address architecture (folder name / aura / link space) that vortexes with the digit architecture into the 128-bit content-uuid; interact64 ANDs the two torus halves, architectureBond entangles word ⊕ digit on the matrix."
    }
  }
]

export default translations
