// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "war",
    "uuid": "f3f42348-e198-8598-b30e-55fc452ef0c9",
    "words": [
      "war"
    ],
    "values": {
      "en": "war"
    }
  },
  {
    "key": "description",
    "source": "Use when the society turns warfare tactics to peace — reconnaissance, the OODA loop, coordinated formations, and defense-in-depth applied to building harmony and driving entropy to zero, never to destruction.",
    "uuid": "16df9a6b-135c-8d61-a836-357738e5e5ab",
    "words": [
      "use",
      "when",
      "the",
      "society",
      "turns",
      "warfare",
      "tactics",
      "to",
      "peace",
      "reconnaissance",
      "the",
      "ooda",
      "loop",
      "coordinated",
      "formations",
      "and",
      "defense",
      "in",
      "depth",
      "applied",
      "to",
      "building",
      "harmony",
      "and",
      "driving",
      "entropy",
      "to",
      "zero",
      "never",
      "to",
      "destruction"
    ],
    "values": {
      "en": "Use when the society turns warfare tactics to peace — reconnaissance, the OODA loop, coordinated formations, and defense-in-depth applied to building harmony and driving entropy to zero, never to destruction."
    }
  }
]

export default translations
