// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "motel",
    "uuid": "031ce345-d7ef-85a8-aed9-232710e45686",
    "words": [
      "motel"
    ],
    "values": {
      "en": "motel"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about motel — A motel. See also the dedicated document on the use of schema.org for marking up hotels and other forms of accommodations.",
    "uuid": "7c2c7e9a-42e4-8b60-b602-20307381b7e7",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "motel",
      "a",
      "motel",
      "see",
      "also",
      "the",
      "dedicated",
      "document",
      "on",
      "the",
      "use",
      "of",
      "schema",
      "org",
      "for",
      "marking",
      "up",
      "hotels",
      "and",
      "other",
      "forms",
      "of",
      "accommodations"
    ],
    "values": {
      "en": "Use when reasoning about motel — A motel. See also the dedicated document on the use of schema.org for marking up hotels and other forms of accommodations."
    }
  }
]

export default translations
