// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "checker",
    "uuid": "6958d443-6426-8974-b574-eaa509266da8",
    "words": [
      "checker"
    ],
    "values": {
      "en": "checker"
    }
  },
  {
    "key": "description",
    "source": "Use when deciding whether a posting date falls in a locked fiscal period — closed periods refuse new postings (admin override required) but allow reversals and prior-period-adjustments, and an unparseable date fails CLOSED; the SOX §404 control an auditor signs.",
    "uuid": "394afa0d-dbe1-8834-96d5-6442f1916227",
    "words": [
      "use",
      "when",
      "deciding",
      "whether",
      "a",
      "posting",
      "date",
      "falls",
      "in",
      "a",
      "locked",
      "fiscal",
      "period",
      "closed",
      "periods",
      "refuse",
      "new",
      "postings",
      "admin",
      "override",
      "required",
      "but",
      "allow",
      "reversals",
      "and",
      "prior",
      "period",
      "adjustments",
      "and",
      "an",
      "unparseable",
      "date",
      "fails",
      "closed",
      "the",
      "sox",
      "control",
      "an",
      "auditor",
      "signs"
    ],
    "values": {
      "en": "Use when deciding whether a posting date falls in a locked fiscal period — closed periods refuse new postings (admin override required) but allow reversals and prior-period-adjustments, and an unparseable date fails CLOSED; the SOX §404 control an auditor signs."
    }
  }
]

export default translations
