// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "orchestrate",
    "uuid": "fec794e4-c436-88bc-af50-da1410a66d6b",
    "words": [
      "orchestrate"
    ],
    "values": {
      "en": "orchestrate"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about orchestrate — Quantum orchestration engine for parallel Millennium Problem computation",
    "uuid": "63827d52-ab10-84b9-bf9a-09727d6da478",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "orchestrate",
      "quantum",
      "orchestration",
      "engine",
      "for",
      "parallel",
      "millennium",
      "problem",
      "computation"
    ],
    "values": {
      "en": "Use when reasoning about orchestrate — Quantum orchestration engine for parallel Millennium Problem computation"
    }
  }
]

export default translations
