// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "body",
    "uuid": "f5cd43a1-af3a-81c6-8f22-40859a7455c3",
    "words": [
      "body"
    ],
    "values": {
      "en": "body"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about erpax as ONE organism — the eight organs harmonized into a body. Each organ is sent through the wave mechanism; its horo position sounds a note and a colour (A432); composed, the organs span the full diatonic spectrum and rest at unity (the closing wave). The body harmonizes ⟺ every organ healthy ⊕ full-spectrum chord ⊕ folds to unity — wholeness renders as harmony, a failing organ as dissonance.",
    "uuid": "4f12c00c-3678-862b-bacf-b4de3b7a839b",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "erpax",
      "as",
      "one",
      "organism",
      "the",
      "eight",
      "organs",
      "harmonized",
      "into",
      "a",
      "body",
      "each",
      "organ",
      "is",
      "sent",
      "through",
      "the",
      "wave",
      "mechanism",
      "its",
      "horo",
      "position",
      "sounds",
      "a",
      "note",
      "and",
      "a",
      "colour",
      "a432",
      "composed",
      "the",
      "organs",
      "span",
      "the",
      "full",
      "diatonic",
      "spectrum",
      "and",
      "rest",
      "at",
      "unity",
      "the",
      "closing",
      "wave",
      "the",
      "body",
      "harmonizes",
      "every",
      "organ",
      "healthy",
      "full",
      "spectrum",
      "chord",
      "folds",
      "to",
      "unity",
      "wholeness",
      "renders",
      "as",
      "harmony",
      "a",
      "failing",
      "organ",
      "as",
      "dissonance"
    ],
    "values": {
      "en": "Use when reasoning about erpax as ONE organism — the eight organs harmonized into a body. Each organ is sent through the wave mechanism; its horo position sounds a note and a colour (A432); composed, the organs span the full diatonic spectrum and rest at unity (the closing wave). The body harmonizes ⟺ every organ healthy ⊕ full-spectrum chord ⊕ folds to unity — wholeness renders as harmony, a failing organ as dissonance."
    }
  }
]

export default translations
