/**
 * Export-service contract — the render-ready projection a financial
 * statement takes on its way to xlsx (ExcelJS) or PDF (Puppeteer),
 * plus per-export options and the uniform result envelope.
 *
 * Distinct from the generated `FinancialStatement` collection doc
 * (`@/payload-types`): this is the flattened presentation DTO the
 * exporters lay out — sections → rows → totals. PDF/A + PDF/UA
 * profiles are NOT here; `pdf.service` augments `ExportOptions`
 * locally with the canonical types from `@/standards/iso-19005` and
 * `@/standards/iso-14289`.
 *
 * @standard ISO-8601-1:2019 date-time (asOfDate)
 * @standard ISO/IEC-29500:2016 office-open-xml (xlsx)
 * @standard ISO-19005-2:2011 pdf-a-2 (archival — see @/standards/iso-19005)
 * @standard ISO-14289-1:2014 pdf-ua-1 (accessibility — see @/standards/iso-14289)
 * @see ./excel.service.ts
 * @see ./pdf.service.ts
 */

/** One line item in a statement section. */
export interface FinancialStatementRow {
  label: string
  amount: number
  /** Indent depth for nested items (0/undefined = top level). */
  level?: number
  isBold?: boolean
}

/** A named group of rows with an optional subtotal. */
export interface FinancialStatementSection {
  name: string
  rows: FinancialStatementRow[]
  subtotal?: number
}

/** Render-ready financial-statement projection (not the collection doc). */
export interface FinancialStatement {
  title: string
  subtitle?: string
  asOfDate?: Date
  sections: FinancialStatementSection[]
  totals?: { label: string; amount: number }
  notes?: string[]
}

/**
 * Render-time attribution shown in the PDF footer ("Generated by …").
 * NOT the ISO-19005 archival packet — that XMP metadata is built from
 * the statement itself (see `@/standards/iso-19005` `PdfAMetadataInput`,
 * consumed by `pdf.service`'s `buildArchivalMetadata`).
 */
export interface ExportMetadata {
  author?: string
}

/** Per-export options; PDF-only fields are ignored by the xlsx exporter. */
export interface ExportOptions {
  fileName?: string
  orientation?: 'portrait' | 'landscape'
  metadata?: ExportMetadata
}

/** Uniform result envelope returned by every exporter. */
export interface ExportResult {
  success: boolean
  fileName: string
  size: number
  format: 'excel' | 'pdf'
  generatedAt: Date
  error?: string
}
