// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "psychological",
    "uuid": "ef1245ab-8cb8-8b21-a892-a62ac1e1e64d",
    "words": [
      "psychological"
    ],
    "values": {
      "en": "psychological"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about psychological — A schema.org component word, collided out of schema.org compounds — fused from PsychologicalTreatment (sti · collapse · merge).",
    "uuid": "0dc4ecb6-639d-8f07-92c6-f82c15323c98",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "psychological",
      "a",
      "schema",
      "org",
      "component",
      "word",
      "collided",
      "out",
      "of",
      "schema",
      "org",
      "compounds",
      "fused",
      "from",
      "psychologicaltreatment",
      "sti",
      "collapse",
      "merge"
    ],
    "values": {
      "en": "Use when reasoning about psychological — A schema.org component word, collided out of schema.org compounds — fused from PsychologicalTreatment (sti · collapse · merge)."
    }
  }
]

export default translations
