// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "forecast",
    "uuid": "fd5bab16-8d13-8b18-ae28-4de96a979ba8",
    "words": [
      "forecast"
    ],
    "values": {
      "en": "forecast"
    }
  },
  {
    "key": "description",
    "source": "Use when projecting revenue from pipeline/opportunities — weighted by probability, stage, and close date; aggregated by rep/territory/product/period.",
    "uuid": "717867ae-613f-8097-9953-ba9958c0028e",
    "words": [
      "use",
      "when",
      "projecting",
      "revenue",
      "from",
      "pipeline",
      "opportunities",
      "weighted",
      "by",
      "probability",
      "stage",
      "and",
      "close",
      "date",
      "aggregated",
      "by",
      "rep",
      "territory",
      "product",
      "period"
    ],
    "values": {
      "en": "Use when projecting revenue from pipeline/opportunities — weighted by probability, stage, and close date; aggregated by rep/territory/product/period."
    }
  }
]

export default translations
