// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "development",
    "uuid": "6426ce22-f023-8459-9f51-3d572935efcd",
    "words": [
      "development"
    ],
    "values": {
      "en": "development"
    }
  },
  {
    "key": "description",
    "source": "Use when choosing the next quantum capability to build — the feasibility-ranked quantum roadmap from the quantum-scientists; the one move now is to drive the orphans to zero so tamper-cost becomes literally infinite.",
    "uuid": "f281e7d5-4843-87c3-9131-4b9cb5efec53",
    "words": [
      "use",
      "when",
      "choosing",
      "the",
      "next",
      "quantum",
      "capability",
      "to",
      "build",
      "the",
      "feasibility",
      "ranked",
      "quantum",
      "roadmap",
      "from",
      "the",
      "quantum",
      "scientists",
      "the",
      "one",
      "move",
      "now",
      "is",
      "to",
      "drive",
      "the",
      "orphans",
      "to",
      "zero",
      "so",
      "tamper",
      "cost",
      "becomes",
      "literally",
      "infinite"
    ],
    "values": {
      "en": "Use when choosing the next quantum capability to build — the feasibility-ranked quantum roadmap from the quantum-scientists; the one move now is to drive the orphans to zero so tamper-cost becomes literally infinite."
    }
  }
]

export default translations
