// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "typography",
    "uuid": "5c7065cb-11a0-8932-b814-b1d8f07e22ea",
    "words": [
      "typography"
    ],
    "values": {
      "en": "typography"
    }
  },
  {
    "key": "description",
    "source": "Use when treating typographic richness as tamper-cost — each vitepress feature a page uses is a dimension a forger must reproduce, so fuller (gapless) typography costs more to forge.",
    "uuid": "70bbdcc6-2543-848b-9e7e-50de4cf756f9",
    "words": [
      "use",
      "when",
      "treating",
      "typographic",
      "richness",
      "as",
      "tamper",
      "cost",
      "each",
      "vitepress",
      "feature",
      "a",
      "page",
      "uses",
      "is",
      "a",
      "dimension",
      "a",
      "forger",
      "must",
      "reproduce",
      "so",
      "fuller",
      "gapless",
      "typography",
      "costs",
      "more",
      "to",
      "forge"
    ],
    "values": {
      "en": "Use when treating typographic richness as tamper-cost — each vitepress feature a page uses is a dimension a forger must reproduce, so fuller (gapless) typography costs more to forge."
    }
  }
]

export default translations
