// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "confidence",
    "uuid": "aff16391-0634-81ca-bf8c-8b6e9b68a405",
    "words": [
      "confidence"
    ],
    "values": {
      "en": "confidence"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about confidence — AI auto-accept confidence thresholds — imperial rationals only.",
    "uuid": "fc0ef732-6a2f-87a1-8a7d-1a9928f2c10b",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "confidence",
      "ai",
      "auto",
      "accept",
      "confidence",
      "thresholds",
      "imperial",
      "rationals",
      "only"
    ],
    "values": {
      "en": "Use when reasoning about confidence — AI auto-accept confidence thresholds — imperial rationals only."
    }
  }
]

export default translations
