// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "coinsurance",
    "uuid": "4824459b-9795-8a54-a8d7-a7c0bd7dc983",
    "words": [
      "coinsurance"
    ],
    "values": {
      "en": "coinsurance"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about coinsurance as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus.",
    "uuid": "4b49ac85-09ee-8b35-a1b4-2092aadc72d2",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "coinsurance",
      "as",
      "a",
      "schema",
      "org",
      "vocabulary",
      "word",
      "the",
      "single",
      "word",
      "collided",
      "from",
      "the",
      "schema",
      "org",
      "terms",
      "that",
      "contain",
      "it",
      "content",
      "addressed",
      "into",
      "the",
      "corpus"
    ],
    "values": {
      "en": "Use when reasoning about coinsurance as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus."
    }
  }
]

export default translations
