// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "collide",
    "uuid": "8b7c6fcc-84f3-80d1-9493-8925c501734c",
    "words": [
      "collide"
    ],
    "values": {
      "en": "collide"
    }
  },
  {
    "key": "description",
    "source": "Use when folding two atoms into one — collide is the deferred INHALE of development, the DRY collapse that merges the expansion back toward one and so lowers entropy; it DEFINES the fold collide(a,b) = merge two into one but is applied LATER, never during the exhale.",
    "uuid": "dccbe619-851d-878f-b015-aba1630c9689",
    "words": [
      "use",
      "when",
      "folding",
      "two",
      "atoms",
      "into",
      "one",
      "collide",
      "is",
      "the",
      "deferred",
      "inhale",
      "of",
      "development",
      "the",
      "dry",
      "collapse",
      "that",
      "merges",
      "the",
      "expansion",
      "back",
      "toward",
      "one",
      "and",
      "so",
      "lowers",
      "entropy",
      "it",
      "defines",
      "the",
      "fold",
      "collide",
      "a",
      "b",
      "merge",
      "two",
      "into",
      "one",
      "but",
      "is",
      "applied",
      "later",
      "never",
      "during",
      "the",
      "exhale"
    ],
    "values": {
      "en": "Use when folding two atoms into one — collide is the deferred INHALE of development, the DRY collapse that merges the expansion back toward one and so lowers entropy; it DEFINES the fold collide(a,b) = merge two into one but is applied LATER, never during the exhale."
    }
  }
]

export default translations
