// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "checkbox",
    "uuid": "d2bda10d-169b-84e2-80e3-ce1a622ae21e",
    "words": [
      "checkbox"
    ],
    "values": {
      "en": "checkbox"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about checkbox — 's returns an and expects a **native** input to fire it. The shadcn checkbox is a Radix button with — it fires , and the native event never happens.",
    "uuid": "0a41cafc-958b-8aed-b4df-1af30671d1a7",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "checkbox",
      "s",
      "returns",
      "an",
      "and",
      "expects",
      "a",
      "native",
      "input",
      "to",
      "fire",
      "it",
      "the",
      "shadcn",
      "checkbox",
      "is",
      "a",
      "radix",
      "button",
      "with",
      "it",
      "fires",
      "and",
      "the",
      "native",
      "event",
      "never",
      "happens"
    ],
    "values": {
      "en": "Use when reasoning about checkbox — 's returns an and expects a **native** input to fire it. The shadcn checkbox is a Radix button with — it fires , and the native event never happens."
    }
  }
]

export default translations
