// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "lifecycle",
    "uuid": "a3823697-b9c2-8574-bb8b-3d55bafa8e59",
    "words": [
      "lifecycle"
    ],
    "values": {
      "en": "lifecycle"
    }
  },
  {
    "key": "description",
    "source": "Case state machine on the horo ring—filed to sealed through seven positions",
    "uuid": "e9fa1ced-bd54-813c-a1d0-8899a7a68b8f",
    "words": [
      "case",
      "state",
      "machine",
      "on",
      "the",
      "horo",
      "ring",
      "filed",
      "to",
      "sealed",
      "through",
      "seven",
      "positions"
    ],
    "values": {
      "en": "Case state machine on the horo ring—filed to sealed through seven positions"
    }
  }
]

export default translations
