// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "resources",
    "uuid": "ce5385c5-344a-8e2b-b215-829c9de369ac",
    "words": [
      "resources"
    ],
    "values": {
      "en": "resources"
    }
  },
  {
    "key": "description",
    "source": "Use when cataloguing or querying reservable assets — rooms, vehicles, equipment, beds, machinery, parking, co-working desks, time slots — across hospitality, fleet, facility management or field-service; rate ladders, availability windows, yield management, GL/tax linkage. The agnostic resource-booking master — pairs with bookings.",
    "uuid": "d567cb5d-2629-873c-86bd-eb6af9145eb1",
    "words": [
      "use",
      "when",
      "cataloguing",
      "or",
      "querying",
      "reservable",
      "assets",
      "rooms",
      "vehicles",
      "equipment",
      "beds",
      "machinery",
      "parking",
      "co",
      "working",
      "desks",
      "time",
      "slots",
      "across",
      "hospitality",
      "fleet",
      "facility",
      "management",
      "or",
      "field",
      "service",
      "rate",
      "ladders",
      "availability",
      "windows",
      "yield",
      "management",
      "gl",
      "tax",
      "linkage",
      "the",
      "agnostic",
      "resource",
      "booking",
      "master",
      "pairs",
      "with",
      "bookings"
    ],
    "values": {
      "en": "Use when cataloguing or querying reservable assets — rooms, vehicles, equipment, beds, machinery, parking, co-working desks, time slots — across hospitality, fleet, facility management or field-service; rate ladders, availability windows, yield management, GL/tax linkage. The agnostic resource-booking master — pairs with bookings."
    }
  }
]

export default translations
