// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "brain",
    "uuid": "3c57882f-b9d7-8aec-8afc-6eec8ea4b452",
    "words": [
      "brain"
    ],
    "values": {
      "en": "brain"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about the brain as an organ of body — pivot to canonical @/brain; zero duplication.",
    "uuid": "f1ccc5dd-2ec2-8aa1-8ea1-f4803190bc79",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "the",
      "brain",
      "as",
      "an",
      "organ",
      "of",
      "body",
      "pivot",
      "to",
      "canonical",
      "brain",
      "zero",
      "duplication"
    ],
    "values": {
      "en": "Use when reasoning about the brain as an organ of body — pivot to canonical @/brain; zero duplication."
    }
  }
]

export default translations
