// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "audit",
    "uuid": "102f74a7-fdce-8d96-867c-c2ff2e5b61a1",
    "words": [
      "audit"
    ],
    "values": {
      "en": "audit"
    }
  },
  {
    "key": "description",
    "source": "Use when capturing compliance/evidence metadata — audit fields (createdBy, createdAt, updatedBy, updatedAt, deletedAt), audit trail events, audit evidence, audit finding. Standard immutable history; drives IFRS/SOX compliance. Often shared across all collections via auditFields() helper.",
    "uuid": "8962a662-5817-8db3-bbdf-8c3ed9abed09",
    "words": [
      "use",
      "when",
      "capturing",
      "compliance",
      "evidence",
      "metadata",
      "audit",
      "fields",
      "createdby",
      "createdat",
      "updatedby",
      "updatedat",
      "deletedat",
      "audit",
      "trail",
      "events",
      "audit",
      "evidence",
      "audit",
      "finding",
      "standard",
      "immutable",
      "history",
      "drives",
      "ifrs",
      "sox",
      "compliance",
      "often",
      "shared",
      "across",
      "all",
      "collections",
      "via",
      "auditfields",
      "helper"
    ],
    "values": {
      "en": "Use when capturing compliance/evidence metadata — audit fields (createdBy, createdAt, updatedBy, updatedAt, deletedAt), audit trail events, audit evidence, audit finding. Standard immutable history; drives IFRS/SOX compliance. Often shared across all collections via auditFields() helper."
    }
  }
]

export default translations
