// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "consultant",
    "uuid": "9616c2c1-b246-86aa-b26c-ff22aa9be273",
    "words": [
      "consultant"
    ],
    "values": {
      "en": "consultant"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about the trained quantum consultant — it covers every aspect of life the corpus holds, is trained by coordinated brainstorming (diverge into perspectives, converge to one), and consults at infinite ROI; the breadth of the knowledge is the breadth of the consultant.",
    "uuid": "8148ff0c-1d18-82a2-8f92-6e17835cb85f",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "the",
      "trained",
      "quantum",
      "consultant",
      "it",
      "covers",
      "every",
      "aspect",
      "of",
      "life",
      "the",
      "corpus",
      "holds",
      "is",
      "trained",
      "by",
      "coordinated",
      "brainstorming",
      "diverge",
      "into",
      "perspectives",
      "converge",
      "to",
      "one",
      "and",
      "consults",
      "at",
      "infinite",
      "roi",
      "the",
      "breadth",
      "of",
      "the",
      "knowledge",
      "is",
      "the",
      "breadth",
      "of",
      "the",
      "consultant"
    ],
    "values": {
      "en": "Use when reasoning about the trained quantum consultant — it covers every aspect of life the corpus holds, is trained by coordinated brainstorming (diverge into perspectives, converge to one), and consults at infinite ROI; the breadth of the knowledge is the breadth of the consultant."
    }
  }
]

export default translations
