// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "assets",
    "uuid": "d3f903d3-ce3e-8bf5-aa6f-d9adbbe2fc63",
    "words": [
      "assets"
    ],
    "values": {
      "en": "assets"
    }
  },
  {
    "key": "description",
    "source": "Use when measuring, re-measuring, or disclosing IAS 41 biological assets — livestock, aquaculture, annual/perennial crops, forestry, vineyard produce — at fair-value-less-costs-to-sell; biological-transformation vs. price-change P&L split; bearer-plant IAS-16 carve-out; harvest-event transformation lifecycle. The IAS-41 biological-asset measurement collection.",
    "uuid": "df73a371-013d-8d53-9bd8-651ad54344bf",
    "words": [
      "use",
      "when",
      "measuring",
      "re",
      "measuring",
      "or",
      "disclosing",
      "ias",
      "biological",
      "assets",
      "livestock",
      "aquaculture",
      "annual",
      "perennial",
      "crops",
      "forestry",
      "vineyard",
      "produce",
      "at",
      "fair",
      "value",
      "less",
      "costs",
      "to",
      "sell",
      "biological",
      "transformation",
      "vs",
      "price",
      "change",
      "p",
      "l",
      "split",
      "bearer",
      "plant",
      "ias",
      "carve",
      "out",
      "harvest",
      "event",
      "transformation",
      "lifecycle",
      "the",
      "ias",
      "biological",
      "asset",
      "measurement",
      "collection"
    ],
    "values": {
      "en": "Use when measuring, re-measuring, or disclosing IAS 41 biological assets — livestock, aquaculture, annual/perennial crops, forestry, vineyard produce — at fair-value-less-costs-to-sell; biological-transformation vs. price-change P&L split; bearer-plant IAS-16 carve-out; harvest-event transformation lifecycle. The IAS-41 biological-asset measurement collection."
    }
  }
]

export default translations
