// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "submission",
    "uuid": "8faadb37-af25-8256-bc02-49cac24090a8",
    "words": [
      "submission"
    ],
    "values": {
      "en": "submission"
    }
  },
  {
    "key": "description",
    "source": "Use when modelling one submission — the singular model of the submissions collection (the plural store); a record sent in for review or processing.",
    "uuid": "3464159f-f72d-82cc-a0e1-7337edd6b5b9",
    "words": [
      "use",
      "when",
      "modelling",
      "one",
      "submission",
      "the",
      "singular",
      "model",
      "of",
      "the",
      "submissions",
      "collection",
      "the",
      "plural",
      "store",
      "a",
      "record",
      "sent",
      "in",
      "for",
      "review",
      "or",
      "processing"
    ],
    "values": {
      "en": "Use when modelling one submission — the singular model of the submissions collection (the plural store); a record sent in for review or processing."
    }
  }
]

export default translations
