// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "support",
    "uuid": "3643ecae-c387-8cb4-89c2-255ed9ad0ecd",
    "words": [
      "support"
    ],
    "values": {
      "en": "support"
    }
  },
  {
    "key": "description",
    "source": "Qualification, candidature, degree, application that Thesis supports.",
    "uuid": "c8d2fda9-a386-837d-82c1-a6229b9f66b0",
    "words": [
      "qualification",
      "candidature",
      "degree",
      "application",
      "that",
      "thesis",
      "supports"
    ],
    "values": {
      "en": "Qualification, candidature, degree, application that Thesis supports."
    }
  }
]

export default translations
