// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "encodes",
    "uuid": "276e58ec-8cf9-892c-9698-3470547d29be",
    "words": [
      "encodes"
    ],
    "values": {
      "en": "encodes"
    }
  },
  {
    "key": "description",
    "source": "encodes: a schema.org component word, fused from encodesBioChemEntity, encodesCreativeWork",
    "uuid": "4814d279-0f1e-8b85-a503-676df918e23e",
    "words": [
      "encodes",
      "a",
      "schema",
      "org",
      "component",
      "word",
      "fused",
      "from",
      "encodesbiochementity",
      "encodescreativework"
    ],
    "values": {
      "en": "encodes: a schema.org component word, fused from encodesBioChemEntity, encodesCreativeWork"
    }
  }
]

export default translations
