// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "immutability",
    "uuid": "85dcda7e-dd66-80ce-a1cc-84db01d2f793",
    "words": [
      "immutability"
    ],
    "values": {
      "en": "immutability"
    }
  },
  {
    "key": "description",
    "source": "Use when enforcing that a fiscalised sale cannot be edited or deleted — under Наредба Н-18 a closed fiscal sale is corrected by a reversal, never by mutation.",
    "uuid": "6de28e0b-7c5b-855a-93ec-e818fda49305",
    "words": [
      "use",
      "when",
      "enforcing",
      "that",
      "a",
      "fiscalised",
      "sale",
      "cannot",
      "be",
      "edited",
      "or",
      "deleted",
      "under",
      "a",
      "closed",
      "fiscal",
      "sale",
      "is",
      "corrected",
      "by",
      "a",
      "reversal",
      "never",
      "by",
      "mutation"
    ],
    "values": {
      "en": "Use when enforcing that a fiscalised sale cannot be edited or deleted — under Наредба Н-18 a closed fiscal sale is corrected by a reversal, never by mutation."
    }
  }
]

export default translations
