// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "interval",
    "uuid": "6ec4c5e3-eb57-8df3-b74b-8e4aef94cf50",
    "words": [
      "interval"
    ],
    "values": {
      "en": "interval"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about interval — Special relativity's decidable core, proved for **all integers** rather than checked on a carrier, and carrying one consequence this corpus actually needs.",
    "uuid": "417aef82-a662-89c0-b1a6-7f75380d6690",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "interval",
      "special",
      "relativity",
      "s",
      "decidable",
      "core",
      "proved",
      "for",
      "all",
      "integers",
      "rather",
      "than",
      "checked",
      "on",
      "a",
      "carrier",
      "and",
      "carrying",
      "one",
      "consequence",
      "this",
      "corpus",
      "actually",
      "needs"
    ],
    "values": {
      "en": "Use when reasoning about interval — Special relativity's decidable core, proved for **all integers** rather than checked on a carrier, and carrying one consequence this corpus actually needs."
    }
  }
]

export default translations
