// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "calories",
    "uuid": "911483fb-fa39-81bc-96e3-3c087ab288d9",
    "words": [
      "calories"
    ],
    "values": {
      "en": "calories"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about calories — The number of calories.",
    "uuid": "dac4347f-1657-8afa-9f79-19b01cc6c7e5",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "calories",
      "the",
      "number",
      "of",
      "calories"
    ],
    "values": {
      "en": "Use when reasoning about calories — The number of calories."
    }
  }
]

export default translations
