// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "entity",
    "uuid": "cd49dd93-3d4e-8f18-9d44-4667220fb052",
    "words": [
      "entity"
    ],
    "values": {
      "en": "entity"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about entity as a medical facet of medical — vocabulary pivot to @/entity; nested not duplicated.",
    "uuid": "8389fbd9-cfc0-871a-89b1-e6e21636b094",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "entity",
      "as",
      "a",
      "medical",
      "facet",
      "of",
      "medical",
      "vocabulary",
      "pivot",
      "to",
      "entity",
      "nested",
      "not",
      "duplicated"
    ],
    "values": {
      "en": "Use when reasoning about entity as a medical facet of medical — vocabulary pivot to @/entity; nested not duplicated."
    }
  }
]

export default translations
