// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "messages",
    "uuid": "035619ad-7946-81d4-a114-ed0c368a0f20",
    "words": [
      "messages"
    ],
    "values": {
      "en": "messages"
    }
  },
  {
    "key": "description",
    "source": "Use when sending or querying internal addressed messages between users — subject/body, priority (high/normal/low), multi-recipient addressing, threaded replies via parentMessage, optional attachment to invoices/customers/vendors/orders, and read-at tracking. The internal user-to-user messaging collection.",
    "uuid": "d3c7345c-2ffd-8ff3-9784-9a7384324fad",
    "words": [
      "use",
      "when",
      "sending",
      "or",
      "querying",
      "internal",
      "addressed",
      "messages",
      "between",
      "users",
      "subject",
      "body",
      "priority",
      "high",
      "normal",
      "low",
      "multi",
      "recipient",
      "addressing",
      "threaded",
      "replies",
      "via",
      "parentmessage",
      "optional",
      "attachment",
      "to",
      "invoices",
      "customers",
      "vendors",
      "orders",
      "and",
      "read",
      "at",
      "tracking",
      "the",
      "internal",
      "user",
      "to",
      "user",
      "messaging",
      "collection"
    ],
    "values": {
      "en": "Use when sending or querying internal addressed messages between users — subject/body, priority (high/normal/low), multi-recipient addressing, threaded replies via parentMessage, optional attachment to invoices/customers/vendors/orders, and read-at tracking. The internal user-to-user messaging collection."
    }
  }
]

export default translations
