// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "move",
    "uuid": "8ef39aad-9265-8a71-9ea6-fc0c54de389e",
    "words": [
      "move"
    ],
    "values": {
      "en": "move"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about move — A schema.org component word, collided out of schema.org compounds — fused from MoveAction (sti · collapse · merge).",
    "uuid": "4cec101b-4719-82c9-bacf-1fafd35973ef",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "move",
      "a",
      "schema",
      "org",
      "component",
      "word",
      "collided",
      "out",
      "of",
      "schema",
      "org",
      "compounds",
      "fused",
      "from",
      "moveaction",
      "sti",
      "collapse",
      "merge"
    ],
    "values": {
      "en": "Use when reasoning about move — A schema.org component word, collided out of schema.org compounds — fused from MoveAction (sti · collapse · merge)."
    }
  }
]

export default translations
