// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "kpi",
    "uuid": "843b6ae6-035b-829f-a72a-6dbf99af9548",
    "words": [
      "kpi"
    ],
    "values": {
      "en": "kpi"
    }
  },
  {
    "key": "description",
    "source": "Use when defining, computing, or tracking KPIs — target metrics with threshold, formula, frequency, owner, and variances. The measurable objective beneath strategy.",
    "uuid": "10b29063-9e2a-8809-9a80-997749d94556",
    "words": [
      "use",
      "when",
      "defining",
      "computing",
      "or",
      "tracking",
      "kpis",
      "target",
      "metrics",
      "with",
      "threshold",
      "formula",
      "frequency",
      "owner",
      "and",
      "variances",
      "the",
      "measurable",
      "objective",
      "beneath",
      "strategy"
    ],
    "values": {
      "en": "Use when defining, computing, or tracking KPIs — target metrics with threshold, formula, frequency, owner, and variances. The measurable objective beneath strategy."
    }
  }
]

export default translations
