// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "voting",
    "uuid": "722a180e-e97e-866b-b342-8aaf7107373f",
    "words": [
      "voting"
    ],
    "values": {
      "en": "voting"
    }
  },
  {
    "key": "description",
    "source": "Use when the society casts and tallies collective choice — ballots, votes, and rating series — where every gameable violation (double-voting, stuffing, post-cast tampering, aggregate fudging, anonymity collision, cross-tenant pollution) is made a uuid-mismatch any third party can detect without trusting the platform.",
    "uuid": "8c2d8815-0c55-8abd-8afc-3ef87be58e33",
    "words": [
      "use",
      "when",
      "the",
      "society",
      "casts",
      "and",
      "tallies",
      "collective",
      "choice",
      "ballots",
      "votes",
      "and",
      "rating",
      "series",
      "where",
      "every",
      "gameable",
      "violation",
      "double",
      "voting",
      "stuffing",
      "post",
      "cast",
      "tampering",
      "aggregate",
      "fudging",
      "anonymity",
      "collision",
      "cross",
      "tenant",
      "pollution",
      "is",
      "made",
      "a",
      "uuid",
      "mismatch",
      "any",
      "third",
      "party",
      "can",
      "detect",
      "without",
      "trusting",
      "the",
      "platform"
    ],
    "values": {
      "en": "Use when the society casts and tallies collective choice — ballots, votes, and rating series — where every gameable violation (double-voting, stuffing, post-cast tampering, aggregate fudging, anonymity collision, cross-tenant pollution) is made a uuid-mismatch any third party can detect without trusting the platform."
    }
  }
]

export default translations
