// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "crest",
    "uuid": "207cbfbd-3c63-83b1-9c5c-429343cb7bb4",
    "words": [
      "crest"
    ],
    "values": {
      "en": "crest"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about the peak position of the horo state ring — digit 8, \\\"the ascent peaks\\\", the high step where a flow is fully built and architectures merge (packed, assembled, ready). Top of the ascent arc; nested under horo.",
    "uuid": "d8be0e51-4943-82ff-8e01-ea5684fac6bc",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "the",
      "peak",
      "position",
      "of",
      "the",
      "horo",
      "state",
      "ring",
      "digit",
      "the",
      "ascent",
      "peaks",
      "the",
      "high",
      "step",
      "where",
      "a",
      "flow",
      "is",
      "fully",
      "built",
      "and",
      "architectures",
      "merge",
      "packed",
      "assembled",
      "ready",
      "top",
      "of",
      "the",
      "ascent",
      "arc",
      "nested",
      "under",
      "horo"
    ],
    "values": {
      "en": "Use when reasoning about the peak position of the horo state ring — digit 8, \\\"the ascent peaks\\\", the high step where a flow is fully built and architectures merge (packed, assembled, ready). Top of the ascent arc; nested under horo."
    }
  }
]

export default translations
