// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "anatomy",
    "uuid": "55b57463-f5d9-8554-808e-2db4066a25c7",
    "words": [
      "anatomy"
    ],
    "values": {
      "en": "anatomy"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about anatomy as an anatomical part of body — vocabulary pivot to @/anatomy; nested not duplicated.",
    "uuid": "453efb95-e2bf-8e30-a8b9-7ef988ac3e7d",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "anatomy",
      "as",
      "an",
      "anatomical",
      "part",
      "of",
      "body",
      "vocabulary",
      "pivot",
      "to",
      "anatomy",
      "nested",
      "not",
      "duplicated"
    ],
    "values": {
      "en": "Use when reasoning about anatomy as an anatomical part of body — vocabulary pivot to @/anatomy; nested not duplicated."
    }
  }
]

export default translations
