// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "carbon",
    "uuid": "e18fb530-d94c-875a-931f-14341e142dd1",
    "words": [
      "carbon"
    ],
    "values": {
      "en": "carbon"
    }
  },
  {
    "key": "description",
    "source": "Use when accounting the gCO2e of a chain step for ESRS E1 / CSRD reporting — estimateCarbon converts CPU-ms and egress-bytes into grams via grid intensity, recordCarbon accumulates per tenant, getTenantCarbon reads the running total; the carbon dual of cost.",
    "uuid": "d3b9db7c-cfa0-88af-8ee0-c13954af08b3",
    "words": [
      "use",
      "when",
      "accounting",
      "the",
      "gco2e",
      "of",
      "a",
      "chain",
      "step",
      "for",
      "esrs",
      "e1",
      "csrd",
      "reporting",
      "estimatecarbon",
      "converts",
      "cpu",
      "ms",
      "and",
      "egress",
      "bytes",
      "into",
      "grams",
      "via",
      "grid",
      "intensity",
      "recordcarbon",
      "accumulates",
      "per",
      "tenant",
      "gettenantcarbon",
      "reads",
      "the",
      "running",
      "total",
      "the",
      "carbon",
      "dual",
      "of",
      "cost"
    ],
    "values": {
      "en": "Use when accounting the gCO2e of a chain step for ESRS E1 / CSRD reporting — estimateCarbon converts CPU-ms and egress-bytes into grams via grid intensity, recordCarbon accumulates per tenant, getTenantCarbon reads the running total; the carbon dual of cost."
    }
  }
]

export default translations
