// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "buyer",
    "uuid": "14c3e82f-1411-8041-9a19-552564d776f2",
    "words": [
      "buyer"
    ],
    "values": {
      "en": "buyer"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about buyer — A sub property of participant. The participant/person/organization that bought the object.",
    "uuid": "c9c2f6fd-d5d1-8dbc-9264-7533a258f45b",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "buyer",
      "a",
      "sub",
      "property",
      "of",
      "participant",
      "the",
      "participant",
      "person",
      "organization",
      "that",
      "bought",
      "the",
      "object"
    ],
    "values": {
      "en": "Use when reasoning about buyer — A sub property of participant. The participant/person/organization that bought the object."
    }
  }
]

export default translations
