// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "article",
    "uuid": "36d094dc-bcbb-8773-a4ac-481dcba308f7",
    "words": [
      "article"
    ],
    "values": {
      "en": "article"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about article as a medical facet of medical — vocabulary pivot to @/article; nested not duplicated.",
    "uuid": "4223e211-0396-85c0-972b-52d7ae687efb",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "article",
      "as",
      "a",
      "medical",
      "facet",
      "of",
      "medical",
      "vocabulary",
      "pivot",
      "to",
      "article",
      "nested",
      "not",
      "duplicated"
    ],
    "values": {
      "en": "Use when reasoning about article as a medical facet of medical — vocabulary pivot to @/article; nested not duplicated."
    }
  }
]

export default translations
