import type { TradingApi } from '@/trading/api'
/**
 * trading/api/goods — the goods-rails (e-commerce · marketplace · shipping · product-data) slice of the trading-API registry.
 *
 * Split out of the trading/api hub so the parent index.ts stays a thin barrel
 * ([[rules]]/concentration): the registry is one flat array; region + category are
 * fields, not keys, so the goods/goods halves are pure data leaves. The parent
 * concatenates them into TRADING_APIS and owns the region/category query functions.
 * Type-only import back to the parent — erased at runtime, so no cycle.
 */
export const GOODS_TRADING_APIS: ReadonlyArray<TradingApi> = [
  {
    category: 'ecommerce_platform', provider: 'Shopify', name: 'Shopify Admin API (GraphQL)',
    region: 'GLOBAL', endpoint: 'https://{shop}.myshopify.com/admin/api/2026-04/graphql.json',
    auth: 'oauth2', format: 'json',
    documentation: 'https://shopify.dev/docs/api/admin-graphql',
    description: 'Storefront orders, products, inventory, fulfilment, customers. GraphQL-first.',
    clientImplemented: false,
    notes: 'Per-shop subdomain template; date-versioned (pin a version). Token via X-Shopify-Access-Token.',
  },
  {
    category: 'ecommerce_platform', provider: 'WooCommerce', name: 'WooCommerce REST API (v3)',
    region: 'GLOBAL', endpoint: 'https://{store}/wp-json/wc/v3',
    auth: 'basic', format: 'json',
    documentation: 'https://woocommerce.github.io/woocommerce-rest-api-docs/',
    description: 'Orders, products, customers, coupons, reports for self-hosted WooCommerce stores.',
    clientImplemented: false,
    notes: 'Self-hosted: base URL is the tenant WordPress install. Consumer key/secret over HTTP Basic.',
  },
  {
    category: 'ecommerce_platform', provider: 'Adobe Commerce / Magento', name: 'Adobe Commerce REST API (V1)',
    region: 'GLOBAL', endpoint: 'https://{host}/rest/V1',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.adobe.com/commerce/webapi/rest/',
    description: 'Catalog, orders, customers, inventory (MSI), carts for Adobe Commerce / Magento OS.',
    clientImplemented: false,
    notes: 'Self/cloud-hosted base. Integration tokens (PaaS) or Adobe IMS OAuth2 (cloud) — confirm per deployment.',
  },
  {
    category: 'ecommerce_platform', provider: 'BigCommerce', name: 'BigCommerce REST Management API (v3)',
    region: 'GLOBAL', endpoint: 'https://api.bigcommerce.com/stores/{store_hash}/v3',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.bigcommerce.com/docs/start/authentication',
    description: 'Catalog, orders, carts, customers, inventory for BigCommerce-hosted stores.',
    clientImplemented: false,
    notes: 'Store hash in path. X-Auth-Token long-lived OAuth token (no refresh under standard creds).',
  },
  {
    category: 'ecommerce_platform', provider: 'PrestaShop', name: 'PrestaShop Webservice API',
    region: 'EU', endpoint: 'https://{store}/api',
    auth: 'basic', format: 'xml',
    documentation: 'https://devdocs.prestashop-project.org/9/webservice/',
    description: 'CRUD over store resources (products, orders, customers, stock) for self-hosted PrestaShop.',
    clientImplemented: false,
    notes: 'EU-popular self-hosted. 32-char key as HTTP Basic username. JSON via ?io_format=JSON.',
  },
  {
    category: 'ecommerce_platform', provider: 'OpenCart', name: 'OpenCart API (core)',
    region: 'GLOBAL', endpoint: 'https://{store}/index.php?route=api',
    auth: 'api_key', format: 'json',
    documentation: 'https://docs.opencart.com/en-gb/system/users/api/',
    description: 'Core OpenCart API: session-token cart/order operations. Narrow surface vs full management.',
    clientImplemented: false,
    notes: 'Core API is cart/order-centric; full catalog REST admin needs a third-party extension.',
  },
  {
    category: 'marketplace', provider: 'eMAG', name: 'eMAG Marketplace API (api-3)',
    region: 'BG', endpoint: 'https://marketplace-api.emag.bg/api-3',
    auth: 'basic', format: 'json',
    documentation: 'https://marketplace.emag.ro/documentation/api/external',
    description: 'Dominant RO/BG marketplace: offers, orders, AWB/courier, invoices, VAT. THE Balkans channel.',
    clientImplemented: false,
    notes: 'Per-country host (.emag.bg/.ro/.hu/.pl) on /api-3. HTTP Basic (username + password + Base64 hash). Highest BG priority.',
  },
  {
    category: 'marketplace', provider: 'Allegro', name: 'Allegro REST API',
    region: 'PL', endpoint: 'https://api.allegro.pl', sandboxEndpoint: 'https://api.allegro.pl.allegrosandbox.pl',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.allegro.pl/documentation',
    description: 'Largest Polish marketplace: offers, orders, shipments, billing, disputes. OpenAPI 3.0.',
    clientImplemented: false,
    notes: 'OAuth2 only (no API keys). Access tokens are JWTs (12h). Fully separate sandbox tenant.',
  },
  {
    category: 'marketplace', provider: 'OLX Group', name: 'OLX Partner API',
    region: 'EU', endpoint: 'https://api.olxgroup.com',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.olxgroup.com/',
    description: 'Classifieds inventory sync across OLX marketplaces (incl. BG, RO, PL, UA) + verticals.',
    clientImplemented: false,
    notes: 'Balkans-relevant (BG/RO). Partner-gated; listing-centric, not full order/fulfilment.',
  },
  {
    category: 'marketplace', provider: 'Amazon', name: 'Selling Partner API (SP-API) — EU',
    region: 'EU', endpoint: 'https://sellingpartnerapi-eu.amazon.com', sandboxEndpoint: 'https://sandbox.sellingpartnerapi-eu.amazon.com',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer-docs.amazon.com/sp-api',
    description: 'Orders, FBA/MFN, listings, catalog, feeds, reports, finances across EU marketplaces.',
    clientImplemented: false,
    notes: 'Login-with-Amazon OAuth2 (token at api.amazon.com/auth/o2/token); region-pinned base; PII ops need RDT tokens. Heavy onboarding.',
  },
  {
    category: 'marketplace', provider: 'eBay', name: 'eBay Sell APIs (REST)',
    region: 'GLOBAL', endpoint: 'https://api.ebay.com', sandboxEndpoint: 'https://api.sandbox.ebay.com',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.ebay.com/api-docs/static/ebay-rest-landing.html',
    description: 'Sell suite: Inventory, Fulfilment (orders), Account, Marketing, Finances.',
    clientImplemented: false,
    notes: 'OAuth2 app + user tokens. Marketplace via X-EBAY-C-MARKETPLACE-ID header.',
  },
  {
    category: 'marketplace', provider: 'Etsy', name: 'Etsy Open API v3',
    region: 'GLOBAL', endpoint: 'https://api.etsy.com/v3',
    auth: 'oauth2_pkce', format: 'json',
    documentation: 'https://developer.etsy.com/documentation/',
    description: 'Handmade/vintage marketplace: listings, inventory, receipts (orders), shipping, payments.',
    clientImplemented: false,
    notes: 'OAuth2 authorization-code + PKCE; every request also needs an x-api-key header. No sandbox.',
  },
  {
    category: 'marketplace', provider: 'Google', name: 'Google Merchant API',
    region: 'GLOBAL', endpoint: 'https://merchantapi.googleapis.com',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developers.google.com/merchant/api',
    description: 'Merchant Center product feeds, inventory, promotions, reports for Google Shopping surfaces.',
    clientImplemented: false,
    notes: 'GA — supersedes the deprecated Content API for Shopping v2.1. OAuth2 scope .../auth/content.',
  },
  {
    category: 'marketplace', provider: 'Meta', name: 'Meta Commerce Platform (Graph API)',
    region: 'GLOBAL', endpoint: 'https://graph.facebook.com/v23.0',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developers.facebook.com/docs/commerce-platform/',
    description: 'Facebook & Instagram Shops: product catalog (Batch API), commerce_orders, inventory.',
    clientImplemented: false,
    notes: 'Graph version in path (pin + upgrade plan). Access-tier gated; commerce_orders only for on-platform checkout.',
  },
  {
    category: 'marketplace', provider: 'Walmart', name: 'Walmart Marketplace API (US)',
    region: 'US', endpoint: 'https://marketplace.walmartapis.com/v3',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.walmart.com/us-marketplace/docs/introduction-to-marketplace-apis',
    description: 'US marketplace: items, orders, inventory, prices, returns, shipping.',
    clientImplemented: false,
    notes: 'OAuth2 client-credentials; WM_SVC.NAME / WM_QOS.CORRELATION_ID headers. US seller-gated.',
  },
  {
    category: 'marketplace', provider: 'Wish', name: 'Wish Marketplace API v3',
    region: 'GLOBAL', endpoint: 'https://merchant.wish.com/api/v3', sandboxEndpoint: 'https://sandbox.merchant.wish.com/api/v3',
    auth: 'oauth2', format: 'json',
    documentation: 'https://merchant.wish.com/documentation/api/v3/reference',
    description: 'Global discount marketplace: products, variations, orders, fulfilment, returns.',
    clientImplemented: false,
    notes: 'OAuth2; clean prod↔sandbox host swap. Lower Balkans relevance than eMAG/Allegro.',
  },
  {
    category: 'shipping_carrier', provider: 'Econt Express', name: 'Econt Express API (e-Econt / Shipments)',
    region: 'BG', endpoint: 'https://ee.econt.com/services', sandboxEndpoint: 'https://demo.econt.com/ee/services',
    auth: 'basic', format: 'json',
    documentation: 'https://ee.econt.com/services/',
    description: 'Dominant BG courier: nomenclatures, shipment/label creation, courier request, COD (наложен платеж).',
    clientImplemented: true,
    notes: 'BG-critical. Per-service JSON POST; HTTP Basic (username+password). Client: trackEcont (src/trading/api/client).',
  },
  {
    category: 'shipping_carrier', provider: 'Speedy', name: 'Speedy REST/JSON Web API',
    region: 'BG', endpoint: 'https://api.speedy.bg/v1',
    auth: 'basic', format: 'json',
    documentation: 'https://api.speedy.bg/web-api.html',
    description: 'Dominant BG courier: shipment, price calc, label/waybill (PDF+ZPL), pickup, tracking, COD.',
    clientImplemented: true,
    notes: 'BG-critical (DPDgroup). userName+password per request. Client: trackSpeedy (src/trading/api/client).',
  },
  {
    category: 'shipping_carrier', provider: 'Speedy', name: 'Speedy EPS SOAP Web Service (legacy)',
    region: 'BG', endpoint: 'https://services.speedy.bg/eps/v1/',
    auth: 'basic', format: 'soap',
    documentation: 'https://services.speedy.bg/eps/docs/',
    description: 'Legacy SOAP EPS web service — predecessor of the REST/JSON API.',
    clientImplemented: false,
    notes: 'Legacy. Prefer the REST v1 contract for new integrations.',
  },
  {
    category: 'shipping_carrier', provider: 'Български пощи (Bulgarian Posts)', name: 'Bulgarian Posts tracking',
    region: 'BG', endpoint: 'https://www.bgpost.bg',
    auth: 'none', format: 'mixed',
    documentation: 'https://www.bgpost.bg/en',
    description: 'BG national postal operator; UPU S10 tracking numbers; Postpay COD product.',
    clientImplemented: false,
    notes: 'No verifiable official public developer API found — catalogue-only; UPU S10 tracking is the realistic fallback.',
  },
  {
    category: 'shipping_carrier', provider: 'Sameday', name: 'Sameday Courier eAWB API',
    region: 'EU', endpoint: 'https://api.sameday.ro/api', sandboxEndpoint: 'https://sameday-api.demo.zitec.com/api',
    auth: 'api_key', format: 'json',
    documentation: 'https://sameday-api.demo.zitec.com/documentation/client',
    description: 'Regional courier (RO + BG): pickup points, services, eAWB, label, tracking, COD (ramburs).',
    clientImplemented: false,
    notes: 'Username+password → bearer token. Open-source PHP SDK. Confirm BG prod host per tenant.',
  },
  {
    category: 'shipping_carrier', provider: 'DHL', name: 'MyDHL API (DHL Express)',
    region: 'GLOBAL', endpoint: 'https://express.api.dhl.com/mydhlapi', sandboxEndpoint: 'https://express.api.dhl.com/mydhlapi/test',
    auth: 'basic', format: 'json',
    documentation: 'https://developer.dhl.com/api-reference/mydhl-api-dhl-express',
    description: 'DHL Express rating, transit times, shipment + pickup booking, label, tracking.',
    clientImplemented: false,
    notes: 'HTTP Basic. Test env capped 500 calls/day.',
  },
  {
    category: 'shipping_carrier', provider: 'DHL', name: 'DHL Shipment Tracking — Unified',
    region: 'GLOBAL', endpoint: 'https://api-eu.dhl.com/track/shipments',
    auth: 'api_key', format: 'json',
    documentation: 'https://developer.dhl.com/api-reference/shipment-tracking',
    description: 'Cross-divisional unified tracking by tracking number (push webhook variant available).',
    clientImplemented: false,
    notes: 'DHL-API-Key header. Read-only tracking — pairs with carrier-specific label APIs.',
  },
  {
    category: 'shipping_carrier', provider: 'DHL', name: 'DHL Parcel DE Shipping',
    region: 'DE', endpoint: 'https://api-eu.dhl.com/parcel/de/shipping/v2', sandboxEndpoint: 'https://api-sandbox.dhl.com/parcel/de/shipping/v2',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.dhl.com/api-reference/parcel-de-shipping-post-parcel-germany',
    description: 'Domestic-DE parcel label creation, manifests, returns for DHL Paket business customers.',
    clientImplemented: false,
  },
  {
    category: 'shipping_carrier', provider: 'DPD', name: 'DPD Shipper Web Services',
    region: 'EU', endpoint: 'https://wsshipper.dpd.nl',
    auth: 'soap_wsse', format: 'soap',
    documentation: 'https://integrations.dpd.nl/dpd-shipper/dpd-shipper-webservices/api-developer-guidelines/',
    description: 'DPD parcel label, shipment + pickup, tracking, COD via login-token SOAP calls.',
    clientImplemented: false,
    notes: 'SOAP/legacy; endpoints are country-specific (NL shown). A newer REST "MyDPD" exists in some markets.',
  },
  {
    category: 'shipping_carrier', provider: 'GLS', name: 'GLS ShipIT REST API',
    region: 'EU', endpoint: 'https://api.gls-group.eu/public/v1',
    auth: 'basic', format: 'json',
    documentation: 'https://shipit.gls-group.eu/',
    description: 'GLS parcel creation, label (PDF/ZPL), tracking, pickup; COD in eligible countries.',
    clientImplemented: false,
    notes: 'HTTP Basic. National units vary — verify base/path per the GLS unit serving the tenant.',
  },
  {
    category: 'shipping_carrier', provider: 'PostNL', name: 'PostNL Send & Track',
    region: 'NL', endpoint: 'https://api.postnl.nl', sandboxEndpoint: 'https://api-sandbox.postnl.nl',
    auth: 'api_key', format: 'json',
    documentation: 'https://docs.api.postnl.nl/',
    description: 'PostNL shipping/labelling, barcode, confirming, returns and track & trace.',
    clientImplemented: false,
    notes: 'apikey header. Older SOAP webservices still exist; REST is current.',
  },
  {
    category: 'shipping_carrier', provider: 'InPost', name: 'InPost Shipping API (ShipX)',
    region: 'EU', endpoint: 'https://api-shipx-pl.easypack24.net/v1', sandboxEndpoint: 'https://sandbox-api-shipx-pl.easypack24.net/v1',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developers.inpost-group.com/shipping',
    description: 'InPost parcel-locker (Paczkomat) + courier shipments, label download, COD.',
    clientImplemented: false,
    notes: 'OAuth 2.1 bearer; country-scoped hosts. Strong locker-network fit for PL/regional e-commerce.',
  },
  {
    category: 'shipping_carrier', provider: 'UPS', name: 'UPS REST API (Shipping / Rating / Tracking)',
    region: 'GLOBAL', endpoint: 'https://onlinetools.ups.com/api', sandboxEndpoint: 'https://wwwcie.ups.com/api',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.ups.com/',
    description: 'UPS rating, address validation, shipment/label creation, tracking, pickup.',
    clientImplemented: false,
    notes: 'OAuth2 client-credentials — legacy access-key auth removed 2024.',
  },
  {
    category: 'shipping_carrier', provider: 'FedEx', name: 'FedEx APIs (Ship / Track)',
    region: 'GLOBAL', endpoint: 'https://apis.fedex.com', sandboxEndpoint: 'https://apis-sandbox.fedex.com',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.fedex.com/api/en-us/home.html',
    description: 'FedEx Ship (label), Rate, and Track (batch + visibility webhooks).',
    clientImplemented: false,
    notes: 'OAuth2 client-credentials → bearer.',
  },
  {
    category: 'shipping_carrier', provider: 'TNT (FedEx)', name: 'TNT Express ExpressConnect Web Services',
    region: 'EU', endpoint: 'https://express.tnt.com/expressconnect',
    auth: 'basic', format: 'xml',
    documentation: 'https://express.tnt.com/expresswebservices-website/app/landing.html',
    description: 'TNT ExpressConnect: shipping, pricing and tracking over XML web services.',
    clientImplemented: false,
    notes: 'Legacy XML; TNT absorbed into FedEx — prefer FedEx APIs for new EU integrations.',
  },
  {
    category: 'shipping_aggregator', provider: 'EasyPost', name: 'EasyPost Shipping API',
    region: 'GLOBAL', endpoint: 'https://api.easypost.com/v2',
    auth: 'basic', format: 'json',
    documentation: 'https://docs.easypost.com/',
    description: 'Multi-carrier aggregator: rate shopping, label buy, tracking, address verification, customs.',
    clientImplemented: false,
    notes: 'API key as Basic username. US-centric carrier coverage; thin on BG-native couriers.',
  },
  {
    category: 'shipping_aggregator', provider: 'Shippo', name: 'Shippo Shipping API',
    region: 'GLOBAL', endpoint: 'https://api.goshippo.com',
    auth: 'api_key', format: 'json',
    documentation: 'https://docs.goshippo.com/',
    description: 'Multi-carrier aggregator: rates, labels, tracking, returns across UPS/FedEx/USPS/DHL.',
    clientImplemented: false,
    notes: 'Custom header `Authorization: ShippoToken <key>`.',
  },
  {
    category: 'shipping_aggregator', provider: 'Sendcloud', name: 'Sendcloud API v2',
    region: 'EU', endpoint: 'https://panel.sendcloud.sc/api/v2',
    auth: 'basic', format: 'json',
    documentation: 'https://www.sendcloud.dev/docs/',
    description: 'EU-focused multi-carrier aggregator (DPD, GLS, PostNL, InPost, DHL, UPS +).',
    clientImplemented: false,
    notes: 'Public key = username, secret key = password. Best EU-native carrier breadth.',
  },
  {
    category: 'shipping_aggregator', provider: 'ShipStation', name: 'ShipStation API',
    region: 'GLOBAL', endpoint: 'https://ssapi.shipstation.com',
    auth: 'basic', format: 'json',
    documentation: 'https://docs.shipstation.com/',
    description: 'Order + multi-carrier shipping aggregator: orders, rate shopping, label, fulfilment, tracking.',
    clientImplemented: false,
    notes: 'API Key = username, API Secret = password. Rate-limited (40 req/min).',
  },
  {
    category: 'product_data', provider: 'GS1', name: 'Verified by GS1 (GS1 Registry Platform)',
    region: 'GLOBAL', endpoint: 'https://www.gs1.org/services/verified-by-gs1',
    auth: 'api_key', format: 'json',
    documentation: 'https://www.gs1.org/services/verified-by-gs1/getting-started',
    description: 'Authoritative GTIN/GLN/SSCC verification against the global GS1 Registry.',
    clientImplemented: false,
    notes: 'No single global endpoint — queryable API provisioned per Member Organisation (GS1 US/UK). Resolve per region.',
  },
  {
    category: 'product_data', provider: 'GS1', name: 'GS1 GDSN (Global Data Synchronisation Network)',
    region: 'GLOBAL', endpoint: 'https://www.gs1.org/services/gdsn',
    auth: 'mtls', format: 'xml',
    documentation: 'https://www.gs1.org/services/gdsn/how-gdsn-works',
    description: 'Federated master-data sync via certified data pools + the GS1 Global Registry.',
    clientImplemented: false,
    notes: 'NOT a callable API — integrate with one certified data pool (1WorldSync/Atrify/Syndigo) via GS1 XML over AS2/AS4.',
  },
  {
    category: 'product_data', provider: 'Open Food Facts', name: 'Open Food Facts Product API v2',
    region: 'GLOBAL', endpoint: 'https://world.openfoodfacts.org/api/v2', sandboxEndpoint: 'https://world.openfoodfacts.net/api/v2',
    auth: 'none', format: 'json',
    documentation: 'https://openfoodfacts.github.io/openfoodfacts-server/api/',
    description: 'Open product database by barcode (EAN/GTIN): name, brand, ingredients, nutrition, Nutri-Score.',
    clientImplemented: true,
    notes: 'Cleanest open REST product lookup. Descriptive User-Agent required; reads need no key. Client: lookupOpenFoodFactsProduct.',
  },
  {
    category: 'product_data', provider: 'Icecat', name: 'Open Icecat Product API',
    region: 'GLOBAL', endpoint: 'https://live.icecat.biz/api',
    auth: 'api_key', format: 'mixed',
    documentation: 'https://iceclog.com/manual-for-icecat-json-product-requests/',
    description: 'Rich product content by GTIN/MPN+brand: specs, images, multilingual marketing copy.',
    clientImplemented: false,
    notes: 'Strong for IT/CE/electronics. Open Icecat tier free with registration; Full Icecat licensed.',
  },
  {
    category: 'doc_validation', provider: 'Peppol Practical (Helger)', name: 'Peppol / EN 16931 Document Validation Web Service',
    region: 'EU', endpoint: 'https://peppol.helger.com/wsdvs',
    auth: 'none', format: 'soap',
    documentation: 'https://peppol.helger.com/public/menuitem-validation-ws2',
    description: 'Validate UBL/CII documents against Peppol BIS 3.0, EN 16931 and country schematron.',
    clientImplemented: false,
    notes: 'Canonical free validator; SOAP (WSDL). Best-effort uptime — confirm an arrangement before prod reliance.',
  },
]
