// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "scene",
    "uuid": "cd6abcff-a27c-88e1-be7b-f89ce22dc68d",
    "words": [
      "scene"
    ],
    "values": {
      "en": "scene"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about scene — render already projects one content-uuid to **colour · sound · vibration**.",
    "uuid": "93054982-ae5d-8778-b3be-6fba82d27333",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "scene",
      "render",
      "already",
      "projects",
      "one",
      "content",
      "uuid",
      "to",
      "colour",
      "sound",
      "vibration"
    ],
    "values": {
      "en": "Use when reasoning about scene — render already projects one content-uuid to **colour · sound · vibration**."
    }
  }
]

export default translations
