// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "max",
    "uuid": "8ccf9ddc-e672-8a58-a175-c1f52fc49ae1",
    "words": [
      "max"
    ],
    "values": {
      "en": "max"
    }
  },
  {
    "key": "description",
    "source": "max: a schema.org component word, fused from childMaxAge, energyEfficiencyScaleMax, maxPrice, maxValue, requiredMaxAge, suggestedMaxAge",
    "uuid": "d631d5d6-8bfb-8d1a-9256-751d08461f9b",
    "words": [
      "max",
      "a",
      "schema",
      "org",
      "component",
      "word",
      "fused",
      "from",
      "childmaxage",
      "energyefficiencyscalemax",
      "maxprice",
      "maxvalue",
      "requiredmaxage",
      "suggestedmaxage"
    ],
    "values": {
      "en": "max: a schema.org component word, fused from childMaxAge, energyEfficiencyScaleMax, maxPrice, maxValue, requiredMaxAge, suggestedMaxAge"
    }
  }
]

export default translations
