// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "data-protection",
    "uuid": "89c10c56-a8f3-8d17-a196-59a268f26549",
    "words": [
      "data",
      "protection"
    ],
    "values": {
      "en": "data-protection"
    }
  },
  {
    "key": "description",
    "source": "Use when a contract or processing agreement specifies data-protection obligations — processor/controller roles, permitted uses, security measures (encryption, access controls, breach notification), DPA terms.",
    "uuid": "81d62abb-44aa-857f-8a4d-3cf182e3cc09",
    "words": [
      "use",
      "when",
      "a",
      "contract",
      "or",
      "processing",
      "agreement",
      "specifies",
      "data",
      "protection",
      "obligations",
      "processor",
      "controller",
      "roles",
      "permitted",
      "uses",
      "security",
      "measures",
      "encryption",
      "access",
      "controls",
      "breach",
      "notification",
      "dpa",
      "terms"
    ],
    "values": {
      "en": "Use when a contract or processing agreement specifies data-protection obligations — processor/controller roles, permitted uses, security measures (encryption, access controls, breach notification), DPA terms."
    }
  }
]

export default translations
