// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "blood",
    "uuid": "22ee50da-e2ce-831d-8bac-5d12a8498288",
    "words": [
      "blood"
    ],
    "values": {
      "en": "blood"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about the blood as an organ of body — pivot to canonical @/blood; zero duplication.",
    "uuid": "22768ba6-2527-89b8-84da-bc642318a017",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "the",
      "blood",
      "as",
      "an",
      "organ",
      "of",
      "body",
      "pivot",
      "to",
      "canonical",
      "blood",
      "zero",
      "duplication"
    ],
    "values": {
      "en": "Use when reasoning about the blood as an organ of body — pivot to canonical @/blood; zero duplication."
    }
  }
]

export default translations
