// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "communication",
    "uuid": "6cf0773f-3c28-842b-9e41-93ddc21b5793",
    "words": [
      "communication"
    ],
    "values": {
      "en": "communication"
    }
  },
  {
    "key": "description",
    "source": "Use when agents transfer messages — a directed communication between agent ids, the message a content-uuid; relaying preserves the uuid (no-cloning), so the content is never forged in transit.",
    "uuid": "6ba8cfa1-c226-8d3a-af9a-1047646a5e56",
    "words": [
      "use",
      "when",
      "agents",
      "transfer",
      "messages",
      "a",
      "directed",
      "communication",
      "between",
      "agent",
      "ids",
      "the",
      "message",
      "a",
      "content",
      "uuid",
      "relaying",
      "preserves",
      "the",
      "uuid",
      "no",
      "cloning",
      "so",
      "the",
      "content",
      "is",
      "never",
      "forged",
      "in",
      "transit"
    ],
    "values": {
      "en": "Use when agents transfer messages — a directed communication between agent ids, the message a content-uuid; relaying preserves the uuid (no-cloning), so the content is never forged in transit."
    }
  }
]

export default translations
