// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "irrigation",
    "uuid": "74084326-f92e-8358-8802-d96a7ecc3dbd",
    "words": [
      "irrigation"
    ],
    "values": {
      "en": "irrigation"
    }
  },
  {
    "key": "description",
    "source": "Use when water is supplied to a crop on a managed schedule — drip/trickle vs overhead application, fertigation (fertilizer through the line), and evapotranspiration-based scheduling (the water budget). Irrigation credits the soil-water reservoir that evapotranspiration debits; schedule it like a checkbook — replace the deficit before the crop hits stress.",
    "uuid": "db903fbc-ebad-8110-ac44-8d329160568e",
    "words": [
      "use",
      "when",
      "water",
      "is",
      "supplied",
      "to",
      "a",
      "crop",
      "on",
      "a",
      "managed",
      "schedule",
      "drip",
      "trickle",
      "vs",
      "overhead",
      "application",
      "fertigation",
      "fertilizer",
      "through",
      "the",
      "line",
      "and",
      "evapotranspiration",
      "based",
      "scheduling",
      "the",
      "water",
      "budget",
      "irrigation",
      "credits",
      "the",
      "soil",
      "water",
      "reservoir",
      "that",
      "evapotranspiration",
      "debits",
      "schedule",
      "it",
      "like",
      "a",
      "checkbook",
      "replace",
      "the",
      "deficit",
      "before",
      "the",
      "crop",
      "hits",
      "stress"
    ],
    "values": {
      "en": "Use when water is supplied to a crop on a managed schedule — drip/trickle vs overhead application, fertigation (fertilizer through the line), and evapotranspiration-based scheduling (the water budget). Irrigation credits the soil-water reservoir that evapotranspiration debits; schedule it like a checkbook — replace the deficit before the crop hits stress."
    }
  }
]

export default translations
