// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "location",
    "uuid": "c9b062c7-8168-88fb-91ae-58de10840bf0",
    "words": [
      "location"
    ],
    "values": {
      "en": "location"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about location as a anatomical part of [[body]] — vocabulary pivot to @/location; nested not duplicated.",
    "uuid": "d870329b-c114-8eb3-be84-e8d2e781710d",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "location",
      "as",
      "a",
      "anatomical",
      "part",
      "of",
      "body",
      "vocabulary",
      "pivot",
      "to",
      "location",
      "nested",
      "not",
      "duplicated"
    ],
    "values": {
      "en": "Use when reasoning about location as a anatomical part of [[body]] — vocabulary pivot to @/location; nested not duplicated."
    }
  }
]

export default translations
