// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "limit",
    "uuid": "2d204a34-47a1-8638-86d9-81a9b0d97368",
    "words": [
      "limit"
    ],
    "values": {
      "en": "limit"
    }
  },
  {
    "key": "description",
    "source": "Use when mapping the boundary of erpax — what it CAN do (the provable: addressable, balanced, conserved FORM) vs what it CANNOT do from within (truth, judgment, finality, true-erasure, prevention, the subjective — the Gödel boundary). The live finder is services/architecture-invariants; the hard limits are filled by proving the unprovable — supplying the missing 1/3 from OUTSIDE the formalism.",
    "uuid": "226e321e-3a21-85a1-bf51-19c788fa49fe",
    "words": [
      "use",
      "when",
      "mapping",
      "the",
      "boundary",
      "of",
      "erpax",
      "what",
      "it",
      "can",
      "do",
      "the",
      "provable",
      "addressable",
      "balanced",
      "conserved",
      "form",
      "vs",
      "what",
      "it",
      "cannot",
      "do",
      "from",
      "within",
      "truth",
      "judgment",
      "finality",
      "true",
      "erasure",
      "prevention",
      "the",
      "subjective",
      "the",
      "g",
      "del",
      "boundary",
      "the",
      "live",
      "finder",
      "is",
      "services",
      "architecture",
      "invariants",
      "the",
      "hard",
      "limits",
      "are",
      "filled",
      "by",
      "proving",
      "the",
      "unprovable",
      "supplying",
      "the",
      "missing",
      "from",
      "outside",
      "the",
      "formalism"
    ],
    "values": {
      "en": "Use when mapping the boundary of erpax — what it CAN do (the provable: addressable, balanced, conserved FORM) vs what it CANNOT do from within (truth, judgment, finality, true-erasure, prevention, the subjective — the Gödel boundary). The live finder is services/architecture-invariants; the hard limits are filled by proving the unprovable — supplying the missing 1/3 from OUTSIDE the formalism."
    }
  }
]

export default translations
