// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "link",
    "uuid": "16f3a76b-8dd4-8797-89a4-1441b236d2cc",
    "words": [
      "link"
    ],
    "values": {
      "en": "link"
    }
  },
  {
    "key": "description",
    "source": "Use when one atom references another in prose — every wikilink must resolve to a real atom, no dead wires; coverage = resolving / total over the live corpus map.",
    "uuid": "4ce97510-53ea-8108-8995-23fdb5a90880",
    "words": [
      "use",
      "when",
      "one",
      "atom",
      "references",
      "another",
      "in",
      "prose",
      "every",
      "wikilink",
      "must",
      "resolve",
      "to",
      "a",
      "real",
      "atom",
      "no",
      "dead",
      "wires",
      "coverage",
      "resolving",
      "total",
      "over",
      "the",
      "live",
      "corpus",
      "map"
    ],
    "values": {
      "en": "Use when one atom references another in prose — every wikilink must resolve to a real atom, no dead wires; coverage = resolving / total over the live corpus map."
    }
  }
]

export default translations
