// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "error",
    "uuid": "afc9ea33-bb02-8dc7-b78d-675d72a36bdb",
    "words": [
      "error"
    ],
    "values": {
      "en": "error"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about error — A field that rejects input and explains nothing is a dead end: the user knows the form will not submit and has no way to learn what to change.",
    "uuid": "bcd27d86-94c4-89ce-b472-31a44318adf9",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "error",
      "a",
      "field",
      "that",
      "rejects",
      "input",
      "and",
      "explains",
      "nothing",
      "is",
      "a",
      "dead",
      "end",
      "the",
      "user",
      "knows",
      "the",
      "form",
      "will",
      "not",
      "submit",
      "and",
      "has",
      "no",
      "way",
      "to",
      "learn",
      "what",
      "to",
      "change"
    ],
    "values": {
      "en": "Use when reasoning about error — A field that rejects input and explains nothing is a dead end: the user knows the form will not submit and has no way to learn what to change."
    }
  }
]

export default translations
