// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "adjustments",
    "uuid": "2b47dc13-c5f4-8bcf-9882-22a8da3977c6",
    "words": [
      "adjustments"
    ],
    "values": {
      "en": "adjustments"
    }
  },
  {
    "key": "description",
    "source": "Use when recording the small ±0.01 plug entries that reconcile integer-cents ledger totals to presentation-rounded statements — IAS-1 §51(e) rounding plugs and IAS-21 §39 FX-translation fragments by type (presentation, FX, tax, cash-settlement). The rounding-adjustments GL sub-collection.",
    "uuid": "fc635d98-45de-82dc-8f54-dafe76b623ef",
    "words": [
      "use",
      "when",
      "recording",
      "the",
      "small",
      "plug",
      "entries",
      "that",
      "reconcile",
      "integer",
      "cents",
      "ledger",
      "totals",
      "to",
      "presentation",
      "rounded",
      "statements",
      "ias",
      "e",
      "rounding",
      "plugs",
      "and",
      "ias",
      "fx",
      "translation",
      "fragments",
      "by",
      "type",
      "presentation",
      "fx",
      "tax",
      "cash",
      "settlement",
      "the",
      "rounding",
      "adjustments",
      "gl",
      "sub",
      "collection"
    ],
    "values": {
      "en": "Use when recording the small ±0.01 plug entries that reconcile integer-cents ledger totals to presentation-rounded statements — IAS-1 §51(e) rounding plugs and IAS-21 §39 FX-translation fragments by type (presentation, FX, tax, cash-settlement). The rounding-adjustments GL sub-collection."
    }
  }
]

export default translations
