// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "game",
    "uuid": "76f014ae-7826-814e-87c3-3a2eeddb3661",
    "words": [
      "game"
    ],
    "values": {
      "en": "game"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about game — The Game type represents things which are games. These are typically rule-governed recreational activities, e.g. role-playing games in which players assume the role of characters i",
    "uuid": "6e564ed6-7b87-843a-bab1-4fbe638883d4",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "game",
      "the",
      "game",
      "type",
      "represents",
      "things",
      "which",
      "are",
      "games",
      "these",
      "are",
      "typically",
      "rule",
      "governed",
      "recreational",
      "activities",
      "e",
      "g",
      "role",
      "playing",
      "games",
      "in",
      "which",
      "players",
      "assume",
      "the",
      "role",
      "of",
      "characters",
      "i"
    ],
    "values": {
      "en": "Use when reasoning about game — The Game type represents things which are games. These are typically rule-governed recreational activities, e.g. role-playing games in which players assume the role of characters i"
    }
  }
]

export default translations
