// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "sensory",
    "uuid": "e94a38ae-461b-86ac-855e-76ec8cbfd70c",
    "words": [
      "sensory"
    ],
    "values": {
      "en": "sensory"
    }
  },
  {
    "key": "description",
    "source": "sensory: a schema.org component word, fused from sensoryRequirement, sensoryUnit",
    "uuid": "16a77be8-be68-88e5-86d3-d2cbe2f425cb",
    "words": [
      "sensory",
      "a",
      "schema",
      "org",
      "component",
      "word",
      "fused",
      "from",
      "sensoryrequirement",
      "sensoryunit"
    ],
    "values": {
      "en": "sensory: a schema.org component word, fused from sensoryRequirement, sensoryUnit"
    }
  }
]

export default translations
