// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "gtin",
    "uuid": "8e0fcb3b-23d4-8f4f-bc72-dffc3cccaf04",
    "words": [
      "gtin"
    ],
    "values": {
      "en": "gtin"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about gtin — A Global Trade Item Number (GTIN). GTINs identify trade items, including products and services, using numeric identification codes. A correct gtin value should be a valid GTIN, whi",
    "uuid": "26fe60d0-64f4-8452-af4b-68477363ea10",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "gtin",
      "a",
      "global",
      "trade",
      "item",
      "number",
      "gtin",
      "gtins",
      "identify",
      "trade",
      "items",
      "including",
      "products",
      "and",
      "services",
      "using",
      "numeric",
      "identification",
      "codes",
      "a",
      "correct",
      "gtin",
      "value",
      "should",
      "be",
      "a",
      "valid",
      "gtin",
      "whi"
    ],
    "values": {
      "en": "Use when reasoning about gtin — A Global Trade Item Number (GTIN). GTINs identify trade items, including products and services, using numeric identification codes. A correct gtin value should be a valid GTIN, whi"
    }
  }
]

export default translations
