// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "consistency",
    "uuid": "8056c2a8-a94a-81b0-88c8-c566174d12fd",
    "words": [
      "consistency"
    ],
    "values": {
      "en": "consistency"
    }
  },
  {
    "key": "description",
    "source": "Use when enforcing or auditing data consistency — ACID properties, eventual consistency vs strong consistency, consistency models (read-after-write, causal), constraint enforcement, synchronization guarantees across replicas or shards.",
    "uuid": "600ff7c0-83bb-873a-af4f-7e6cd89a177b",
    "words": [
      "use",
      "when",
      "enforcing",
      "or",
      "auditing",
      "data",
      "consistency",
      "acid",
      "properties",
      "eventual",
      "consistency",
      "vs",
      "strong",
      "consistency",
      "consistency",
      "models",
      "read",
      "after",
      "write",
      "causal",
      "constraint",
      "enforcement",
      "synchronization",
      "guarantees",
      "across",
      "replicas",
      "or",
      "shards"
    ],
    "values": {
      "en": "Use when enforcing or auditing data consistency — ACID properties, eventual consistency vs strong consistency, consistency models (read-after-write, causal), constraint enforcement, synchronization guarantees across replicas or shards."
    }
  }
]

export default translations
