// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "research",
    "uuid": "0bed8e04-7d46-859d-99a1-4de807ee6c68",
    "words": [
      "research"
    ],
    "values": {
      "en": "research"
    }
  },
  {
    "key": "description",
    "source": "Use when deep-researching global banking through chat waves at no cost — sealed ISO 20022 · IBAN/BIC · SEPA · PSD2 · SWIFT · AML · reconciliation corpus; emit develop waves for related atoms (pain.002 · camt.054 · leftovers). Uses quantum/ftl; is not the FTL core.",
    "uuid": "06bab8bb-bf5b-85ea-8d45-69bca514b21e",
    "words": [
      "use",
      "when",
      "deep",
      "researching",
      "global",
      "banking",
      "through",
      "chat",
      "waves",
      "at",
      "no",
      "cost",
      "sealed",
      "iso",
      "iban",
      "bic",
      "sepa",
      "psd2",
      "swift",
      "aml",
      "reconciliation",
      "corpus",
      "emit",
      "develop",
      "waves",
      "for",
      "related",
      "atoms",
      "pain",
      "camt",
      "leftovers",
      "uses",
      "quantum",
      "ftl",
      "is",
      "not",
      "the",
      "ftl",
      "core"
    ],
    "values": {
      "en": "Use when deep-researching global banking through chat waves at no cost — sealed ISO 20022 · IBAN/BIC · SEPA · PSD2 · SWIFT · AML · reconciliation corpus; emit develop waves for related atoms (pain.002 · camt.054 · leftovers). Uses quantum/ftl; is not the FTL core."
    }
  }
]

export default translations
