// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "modifications",
    "uuid": "7b158805-01a3-83f5-a756-b0fec99fc36f",
    "words": [
      "modifications"
    ],
    "values": {
      "en": "modifications"
    }
  },
  {
    "key": "description",
    "source": "Use when recording a lease modification — classify as separate-lease (§44) or not-separate (§45/§46 partial/full termination), capture pre/post terms, and compute liability remeasurement + ROU adjustment. The IFRS-16 §44-46 modification register.",
    "uuid": "f114e48b-0352-8924-a651-2f0f2016c07a",
    "words": [
      "use",
      "when",
      "recording",
      "a",
      "lease",
      "modification",
      "classify",
      "as",
      "separate",
      "lease",
      "or",
      "not",
      "separate",
      "partial",
      "full",
      "termination",
      "capture",
      "pre",
      "post",
      "terms",
      "and",
      "compute",
      "liability",
      "remeasurement",
      "rou",
      "adjustment",
      "the",
      "ifrs",
      "modification",
      "register"
    ],
    "values": {
      "en": "Use when recording a lease modification — classify as separate-lease (§44) or not-separate (§45/§46 partial/full termination), capture pre/post terms, and compute liability remeasurement + ROU adjustment. The IFRS-16 §44-46 modification register."
    }
  }
]

export default translations
