// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "prepayment",
    "uuid": "07e3e48a-b7a1-861e-82bc-cda2532460b6",
    "words": [
      "prepayment"
    ],
    "values": {
      "en": "prepayment"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about prepayment as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus.",
    "uuid": "a931d53e-ce41-820a-8fe4-eae36dce7b15",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "prepayment",
      "as",
      "a",
      "schema",
      "org",
      "vocabulary",
      "word",
      "the",
      "single",
      "word",
      "collided",
      "from",
      "the",
      "schema",
      "org",
      "terms",
      "that",
      "contain",
      "it",
      "content",
      "addressed",
      "into",
      "the",
      "corpus"
    ],
    "values": {
      "en": "Use when reasoning about prepayment as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus."
    }
  }
]

export default translations
