// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "barcode",
    "uuid": "c44f6c1b-c461-802c-9ca1-701af476d358",
    "words": [
      "barcode"
    ],
    "values": {
      "en": "barcode"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about barcode — An image of a visual machine-readable code such as a barcode or QR code.",
    "uuid": "fb70721b-d163-8841-8f32-df8f18d795b5",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "barcode",
      "an",
      "image",
      "of",
      "a",
      "visual",
      "machine",
      "readable",
      "code",
      "such",
      "as",
      "a",
      "barcode",
      "or",
      "qr",
      "code"
    ],
    "values": {
      "en": "Use when reasoning about barcode — An image of a visual machine-readable code such as a barcode or QR code."
    }
  }
]

export default translations
