// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "industry",
    "uuid": "ae7b2cab-a2fe-84b8-99c5-51c139c28c50",
    "words": [
      "industry"
    ],
    "values": {
      "en": "industry"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about industry — The industry associated with the job position.",
    "uuid": "1c860243-072f-83e0-8168-7eeef007c0e8",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "industry",
      "the",
      "industry",
      "associated",
      "with",
      "the",
      "job",
      "position"
    ],
    "values": {
      "en": "Use when reasoning about industry — The industry associated with the job position."
    }
  }
]

export default translations
