// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "submissions",
    "uuid": "d99419d0-dd94-8473-b524-ef75115ad62d",
    "words": [
      "submissions"
    ],
    "values": {
      "en": "submissions"
    }
  },
  {
    "key": "description",
    "source": "Use when building, submitting, or auditing Bulgarian Наредба Н-18 Приложение-38 standardised sales-audit files to НАП — period, self-checking header (count + control sum), submission status, НАП response, and the XML; never-deletable compliance trail. The BG fiscal-audit-file submission log.",
    "uuid": "8bd99f05-3ad2-8c00-a0e2-8ca1719d6576",
    "words": [
      "use",
      "when",
      "building",
      "submitting",
      "or",
      "auditing",
      "bulgarian",
      "standardised",
      "sales",
      "audit",
      "files",
      "to",
      "period",
      "self",
      "checking",
      "header",
      "count",
      "control",
      "sum",
      "submission",
      "status",
      "response",
      "and",
      "the",
      "xml",
      "never",
      "deletable",
      "compliance",
      "trail",
      "the",
      "bg",
      "fiscal",
      "audit",
      "file",
      "submission",
      "log"
    ],
    "values": {
      "en": "Use when building, submitting, or auditing Bulgarian Наредба Н-18 Приложение-38 standardised sales-audit files to НАП — period, self-checking header (count + control sum), submission status, НАП response, and the XML; never-deletable compliance trail. The BG fiscal-audit-file submission log."
    }
  }
]

export default translations
