// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "unp",
    "uuid": "a1af94e7-5e1c-832c-b80a-a04b9b1e4216",
    "words": [
      "unp"
    ],
    "values": {
      "en": "unp"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about unp — Наредба Н-18 / СУПТО — УНП (Уникален номер на продажба / Unique Sales Number).",
    "uuid": "f2870360-256c-845c-9f7a-f3461924b9da",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "unp",
      "unique",
      "sales",
      "number"
    ],
    "values": {
      "en": "Use when reasoning about unp — Наредба Н-18 / СУПТО — УНП (Уникален номер на продажба / Unique Sales Number)."
    }
  }
]

export default translations
