// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "angle",
    "uuid": "25ac0b56-1db0-8c56-b398-0829d1d30474",
    "words": [
      "angle"
    ],
    "values": {
      "en": "angle"
    }
  },
  {
    "key": "description",
    "source": "Use when the fold must be read as a rotation — the doubling map ×2 (the fold's generator) acts on the six units of (ℤ/9ℤ)* as an exact 60° rotation, because that group is cyclic of order 6. One fold = 60°; opposition (×8 ≡ −1) = 180° = three folds; the axis {3,6,9} is off the orbit. This is the angle the flat computations missed. Rigorous group theory; the hue/torus mapping is the model layer.",
    "uuid": "db2474bc-3d44-82ad-8540-a47ed0cf103c",
    "words": [
      "use",
      "when",
      "the",
      "fold",
      "must",
      "be",
      "read",
      "as",
      "a",
      "rotation",
      "the",
      "doubling",
      "map",
      "the",
      "fold",
      "s",
      "generator",
      "acts",
      "on",
      "the",
      "six",
      "units",
      "of",
      "as",
      "an",
      "exact",
      "rotation",
      "because",
      "that",
      "group",
      "is",
      "cyclic",
      "of",
      "order",
      "one",
      "fold",
      "opposition",
      "three",
      "folds",
      "the",
      "axis",
      "is",
      "off",
      "the",
      "orbit",
      "this",
      "is",
      "the",
      "angle",
      "the",
      "flat",
      "computations",
      "missed",
      "rigorous",
      "group",
      "theory",
      "the",
      "hue",
      "torus",
      "mapping",
      "is",
      "the",
      "model",
      "layer"
    ],
    "values": {
      "en": "Use when the fold must be read as a rotation — the doubling map ×2 (the fold's generator) acts on the six units of (ℤ/9ℤ)* as an exact 60° rotation, because that group is cyclic of order 6. One fold = 60°; opposition (×8 ≡ −1) = 180° = three folds; the axis {3,6,9} is off the orbit. This is the angle the flat computations missed. Rigorous group theory; the hue/torus mapping is the model layer."
    }
  }
]

export default translations
