import type { CountryApi } from '@/country/api'
/**
 * country/api/bank — open-banking / PSD2 / banking-rails APIs, keyed by country.
 * Split from the hub so its index.ts stays a thin barrel ([[rules]]/concentration).
 * Type-only import back to the parent — no cycle.
 */
export const BANK_APIS: Readonly<Record<string, ReadonlyArray<CountryApi>>> = {
  // EU PSD2 — per-bank ASPSP endpoints discovered via the EBA register
  EU: [
    {
      kind: 'open_banking',
      name: 'EBA Register of Payment Institutions',
      authority: 'European Banking Authority',
      endpoint: 'https://euclid.eba.europa.eu/register/pir/disclaimer',
      auth: 'none',
      format: 'json',
      documentation: 'https://www.eba.europa.eu/regulation-and-policy/passporting-and-supervision-of-branches/eba-register-payment-and-electronic-money-institutions-under-psd2',
      description: 'Discover authorised ASPSPs for PSD2 AISP/PISP onboarding.',
      clientImplemented: false,
    },
  ],
  GB: [
    {
      kind: 'open_banking',
      name: 'OBIE Directory',
      authority: 'Open Banking Implementation Entity',
      endpoint: 'https://directory.openbanking.org.uk',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://standards.openbanking.org.uk/api-specifications/',
      description: 'CMA9 + voluntary ASPSP registry, AISP/PISP/CBPII roles.',
      clientImplemented: false,
    },
  ],
  AU: [
    {
      kind: 'open_banking',
      name: 'CDR Register',
      authority: 'ACCC / Treasury',
      endpoint: 'https://api.cdr.gov.au',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://consumerdatastandards.gov.au/',
      description: 'Consumer Data Right register — banking phase 1 + energy.',
      clientImplemented: false,
    },
  ],
  BR: [
    {
      kind: 'open_banking',
      name: 'Open Finance Brasil',
      authority: 'Banco Central do Brasil',
      endpoint: 'https://openbankingbrasil.org.br',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://openbanking-brasil.github.io/',
      description: 'Open Finance phases 1-4 (accounts, payments, products, insurance).',
      clientImplemented: false,
    },
  ],
  IN: [
    {
      kind: 'open_banking',
      name: 'Account Aggregator (RBI)',
      authority: 'Reserve Bank of India',
      endpoint: 'https://sahamati.org.in/aa-register',
      auth: 'jwt_signed',
      format: 'json',
      documentation: 'https://sahamati.org.in/',
      description: 'NBFC-AA framework for consented financial-data sharing.',
      clientImplemented: false,
    },
    {
      kind: 'open_banking',
      name: 'UPI (NPCI)',
      authority: 'National Payments Corporation of India',
      endpoint: 'https://www.npci.org.in/what-we-do/upi/product-overview',
      auth: 'mtls',
      format: 'json',
      documentation: 'https://www.npci.org.in/what-we-do/upi/product-overview',
      description: 'Unified Payments Interface — peer-to-peer + merchant rails.',
      clientImplemented: false,
    },
  ],
  BG: [
    // BNB (the regulator) is the discovery anchor — every BG ASPSP must
    // publish PSD2 endpoints discoverable through BNB's register, and
    // most use the Berlin Group NextGenPSD2 spec.
    {
      kind: 'bank_directory',
      name: 'БНБ Регистър на платежните институции',
      authority: 'Българска народна банка',
      endpoint: 'https://www.bnb.bg/RegistersAndServices/RSReportRegisters/index.htm',
      auth: 'none',
      format: 'mixed',
      documentation: 'https://www.bnb.bg/RegistersAndServices/index.htm',
      description: 'BNB register of authorised BG ASPSPs (PSD2 + e-money institutions).',
      clientImplemented: true,
    },
    // Major BG banks — top 10 by deposits, all PSD2-licensed AISPs/PISPs.
    // Endpoints follow the Berlin Group NextGenPSD2 v1.3 contract; per-bank
    // sandbox URLs vary, the production paths converge on /v1/accounts etc.
    {
      kind: 'open_banking',
      name: 'UniCredit Bulbank — PSD2 API',
      authority: 'UniCredit Bulbank AD',
      endpoint: 'https://api.unicreditbulbank.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.unicreditbulbank.bg',
      description: 'BG market leader by assets — Berlin Group NextGenPSD2 v1.3.',
      clientImplemented: true,
    },
    {
      kind: 'open_banking',
      name: 'DSK Bank — PSD2 API',
      authority: 'Банка ДСК АД',
      endpoint: 'https://api.dskbank.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.dskbank.bg',
      description: 'Largest retail bank by branches — OTP Group subsidiary.',
      clientImplemented: true,
    },
    {
      kind: 'open_banking',
      name: 'Postbank — PSD2 API',
      authority: 'Юробанк България АД (Postbank)',
      endpoint: 'https://api.postbank.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.postbank.bg',
      description: 'Eurobank subsidiary — Berlin Group NextGenPSD2.',
      clientImplemented: true,
    },
    {
      kind: 'open_banking',
      name: 'Fibank — PSD2 API',
      authority: 'Първа инвестиционна банка АД',
      endpoint: 'https://api.fibank.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.fibank.bg',
      description: 'First Investment Bank — domestic, PSD2 compliant.',
      clientImplemented: true,
    },
    {
      kind: 'open_banking',
      name: 'KBC Bank Bulgaria — PSD2 API',
      authority: 'KBC Bank Bulgaria EAD',
      endpoint: 'https://api.kbcbank.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.kbcbank.bg',
      description: 'KBC Group subsidiary (former Raiffeisenbank Bulgaria + UBB merger).',
      clientImplemented: true,
    },
    {
      kind: 'open_banking',
      name: 'ProCredit Bank Bulgaria — PSD2 API',
      authority: 'ProCredit Bank (Bulgaria) EAD',
      endpoint: 'https://api.procreditbank.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.procreditbank.bg',
      description: 'SME-focused bank, ProCredit Holding subsidiary.',
      clientImplemented: true,
    },
    {
      kind: 'open_banking',
      name: 'Allianz Bank Bulgaria — PSD2 API',
      authority: 'Allianz Bank Bulgaria AD',
      endpoint: 'https://api.allianzbank.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.allianzbank.bg',
      description: 'Allianz Group subsidiary, retail + private banking.',
      clientImplemented: true,
    },
    {
      kind: 'open_banking',
      name: 'Investbank — PSD2 API',
      authority: 'Инвестбанк АД',
      endpoint: 'https://api.investbank.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.investbank.bg',
      description: 'Domestic universal bank, Berlin Group NextGenPSD2.',
      clientImplemented: true,
    },
    {
      kind: 'open_banking',
      name: 'Central Cooperative Bank — PSD2 API',
      authority: 'Централна кооперативна банка АД',
      endpoint: 'https://api.ccbank.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.ccbank.bg',
      description: 'CCB — cooperative-origin universal bank.',
      clientImplemented: true,
    },
    {
      kind: 'open_banking',
      name: 'BACB — PSD2 API',
      authority: 'Българо-американска кредитна банка АД',
      endpoint: 'https://api.bacb.bg/psd2',
      auth: 'oauth2',
      format: 'json',
      documentation: 'https://developer.bacb.bg',
      description: 'Bulgarian-American Credit Bank — Berlin Group NextGenPSD2.',
      clientImplemented: true,
    },
  ],
  US: [
    {
      kind: 'bank_directory',
      name: 'FRB Routing Number Lookup',
      authority: 'Federal Reserve Banks',
      endpoint: 'https://www.frbservices.org/EPaymentsDirectory/search.html',
      auth: 'none',
      format: 'mixed',
      documentation: 'https://www.frbservices.org/resources/routing-number-directory/index.html',
      description: 'Validate ABA routing number + ACH/Fedwire participants.',
      clientImplemented: false,
    },
  ],
  // Global SWIFT / BIC directory
  GLOBAL: [
    {
      kind: 'bank_directory',
      name: 'SWIFT BIC Search',
      authority: 'SWIFT',
      endpoint: 'https://www2.swift.com/bsl/',
      auth: 'api_key',
      format: 'json',
      documentation: 'https://www.swift.com/standards/data-standards/bic',
      description: 'Authoritative ISO 9362 BIC directory (paid).',
      clientImplemented: false,
    },
  ],
}
