// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "transmission",
    "uuid": "d7b8ed03-ce77-84c0-a4c0-554b3b08067f",
    "words": [
      "transmission"
    ],
    "values": {
      "en": "transmission"
    }
  },
  {
    "key": "description",
    "source": "transmission: a schema.org component word, fused from transmissionMethod, vehicleTransmission",
    "uuid": "da805c8d-47ea-8e5d-b9a7-a44273b05928",
    "words": [
      "transmission",
      "a",
      "schema",
      "org",
      "component",
      "word",
      "fused",
      "from",
      "transmissionmethod",
      "vehicletransmission"
    ],
    "values": {
      "en": "transmission: a schema.org component word, fused from transmissionMethod, vehicleTransmission"
    }
  }
]

export default translations
