// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "activities",
    "uuid": "81fb59e8-808c-8f7a-930c-7133d34779dc",
    "words": [
      "activities"
    ],
    "values": {
      "en": "activities"
    }
  },
  {
    "key": "description",
    "source": "Use when logging or analysing CRM touch-points — calls, emails, meetings, demos, tasks, social touches, document/quote sends, site visits — against a lead, opportunity, customer, vendor or project; relationship history, last-touch date, direction (inbound/outbound), rep activity volume, next-step planning. The CRM activity-log collection.",
    "uuid": "c6d80307-13a4-888c-b1ff-9252f291aa71",
    "words": [
      "use",
      "when",
      "logging",
      "or",
      "analysing",
      "crm",
      "touch",
      "points",
      "calls",
      "emails",
      "meetings",
      "demos",
      "tasks",
      "social",
      "touches",
      "document",
      "quote",
      "sends",
      "site",
      "visits",
      "against",
      "a",
      "lead",
      "opportunity",
      "customer",
      "vendor",
      "or",
      "project",
      "relationship",
      "history",
      "last",
      "touch",
      "date",
      "direction",
      "inbound",
      "outbound",
      "rep",
      "activity",
      "volume",
      "next",
      "step",
      "planning",
      "the",
      "crm",
      "activity",
      "log",
      "collection"
    ],
    "values": {
      "en": "Use when logging or analysing CRM touch-points — calls, emails, meetings, demos, tasks, social touches, document/quote sends, site visits — against a lead, opportunity, customer, vendor or project; relationship history, last-touch date, direction (inbound/outbound), rep activity volume, next-step planning. The CRM activity-log collection."
    }
  }
]

export default translations
