// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "query",
    "uuid": "cf3c3b1d-fe91-8f75-af4c-fcd661cc9c90",
    "words": [
      "query"
    ],
    "values": {
      "en": "query"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about query — A sub property of instrument. The query used on this action.",
    "uuid": "8752b534-c698-86b1-b4a3-e4bee82d3f51",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "query",
      "a",
      "sub",
      "property",
      "of",
      "instrument",
      "the",
      "query",
      "used",
      "on",
      "this",
      "action"
    ],
    "values": {
      "en": "Use when reasoning about query — A sub property of instrument. The query used on this action."
    }
  }
]

export default translations
