// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "merkle",
    "uuid": "e6d2ba96-546f-899f-a141-71916465e423",
    "words": [
      "merkle"
    ],
    "values": {
      "en": "merkle"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about merkle — Merkle chain operations — fold message-uuids into tamper-evident thread-uuids",
    "uuid": "d3a124df-a6fd-849d-a0bd-50caaf360a21",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "merkle",
      "merkle",
      "chain",
      "operations",
      "fold",
      "message",
      "uuids",
      "into",
      "tamper",
      "evident",
      "thread",
      "uuids"
    ],
    "values": {
      "en": "Use when reasoning about merkle — Merkle chain operations — fold message-uuids into tamper-evident thread-uuids"
    }
  }
]

export default translations
