// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "editor",
    "uuid": "e1b06ecd-fac5-873f-a0b1-10325de08866",
    "words": [
      "editor"
    ],
    "values": {
      "en": "editor"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about editor — Specifies the Person who edited the CreativeWork.",
    "uuid": "76257c6e-4928-8466-b863-7c9a83deb129",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "editor",
      "specifies",
      "the",
      "person",
      "who",
      "edited",
      "the",
      "creativework"
    ],
    "values": {
      "en": "Use when reasoning about editor — Specifies the Person who edited the CreativeWork."
    }
  }
]

export default translations
