// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "toy",
    "uuid": "14144490-67dd-8b99-a6ba-a3a9697e3f43",
    "words": [
      "toy"
    ],
    "values": {
      "en": "toy"
    }
  },
  {
    "key": "description",
    "source": "toy: a schema.org component word, fused from ToyStore",
    "uuid": "f635d8c3-ae2c-8292-8428-2fce7ee432ca",
    "words": [
      "toy",
      "a",
      "schema",
      "org",
      "component",
      "word",
      "fused",
      "from",
      "toystore"
    ],
    "values": {
      "en": "toy: a schema.org component word, fused from ToyStore"
    }
  }
]

export default translations
