// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "endorsers",
    "uuid": "15942d16-af96-8305-a2b4-764749b751e8",
    "words": [
      "endorsers"
    ],
    "values": {
      "en": "endorsers"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about endorsers — People or organizations that endorse the plan.",
    "uuid": "611f0be6-8187-8d19-9fad-63cf08976cc0",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "endorsers",
      "people",
      "or",
      "organizations",
      "that",
      "endorse",
      "the",
      "plan"
    ],
    "values": {
      "en": "Use when reasoning about endorsers — People or organizations that endorse the plan."
    }
  }
]

export default translations
