// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "endorsers",
    "uuid": "0bf84890-5930-8efa-882a-8115a5f49fad",
    "words": [
      "endorsers"
    ],
    "values": {
      "en": "endorsers"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about endorsers — People or organizations that endorse the plan.",
    "uuid": "e535b58d-82c1-8a0f-9e69-b2e0cc8f3732",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "endorsers",
      "people",
      "or",
      "organizations",
      "that",
      "endorse",
      "the",
      "plan"
    ],
    "values": {
      "en": "Use when reasoning about endorsers — People or organizations that endorse the plan."
    }
  }
]

export default translations
