// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "publish",
    "uuid": "1639b738-f7f4-833f-89f9-7049469bfa7b",
    "words": [
      "publish"
    ],
    "values": {
      "en": "publish"
    }
  },
  {
    "key": "description",
    "source": "publishSelf — wrap a GenomeBundle in a verifiable federation envelope.",
    "uuid": "5586320a-7620-891b-93b9-dc641deee975",
    "words": [
      "publishself",
      "wrap",
      "a",
      "genomebundle",
      "in",
      "a",
      "verifiable",
      "federation",
      "envelope"
    ],
    "values": {
      "en": "publishSelf — wrap a GenomeBundle in a verifiable federation envelope."
    }
  }
]

export default translations
