// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "frontmatter",
    "uuid": "f034b640-0355-8574-8556-f66a0d4ed43d",
    "words": [
      "frontmatter"
    ],
    "values": {
      "en": "frontmatter"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about frontmatter — skill/frontmatter — pre-push gate for SKILL.md frontmatter & atom-naming law.",
    "uuid": "44275ad9-fd15-8742-8afc-e0c45aa82798",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "frontmatter",
      "skill",
      "frontmatter",
      "pre",
      "push",
      "gate",
      "for",
      "skill",
      "md",
      "frontmatter",
      "atom",
      "naming",
      "law"
    ],
    "values": {
      "en": "Use when reasoning about frontmatter — skill/frontmatter — pre-push gate for SKILL.md frontmatter & atom-naming law."
    }
  }
]

export default translations
