// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "gaps",
    "uuid": "603c0873-ca7a-8ffc-9219-dfd38d033624",
    "words": [
      "gaps"
    ],
    "values": {
      "en": "gaps"
    }
  },
  {
    "key": "description",
    "source": "Use when asked to fill the gaps in quantum mechanics — the honest toolbox that NAMES the open gaps (measurement problem, Born rule, preferred basis, quantum gravity, interpretation) and refuses to fill them. Every gap's `fills` is the literal false, so the code cannot claim a solution; the corpus tools are shown as lenses to learn through, never fillings. HARMONY ≠ TRUTH.",
    "uuid": "f9f5d54d-a20c-8fbd-8422-405e3f9d11e2",
    "words": [
      "use",
      "when",
      "asked",
      "to",
      "fill",
      "the",
      "gaps",
      "in",
      "quantum",
      "mechanics",
      "the",
      "honest",
      "toolbox",
      "that",
      "names",
      "the",
      "open",
      "gaps",
      "measurement",
      "problem",
      "born",
      "rule",
      "preferred",
      "basis",
      "quantum",
      "gravity",
      "interpretation",
      "and",
      "refuses",
      "to",
      "fill",
      "them",
      "every",
      "gap",
      "s",
      "fills",
      "is",
      "the",
      "literal",
      "false",
      "so",
      "the",
      "code",
      "cannot",
      "claim",
      "a",
      "solution",
      "the",
      "corpus",
      "tools",
      "are",
      "shown",
      "as",
      "lenses",
      "to",
      "learn",
      "through",
      "never",
      "fillings",
      "harmony",
      "truth"
    ],
    "values": {
      "en": "Use when asked to fill the gaps in quantum mechanics — the honest toolbox that NAMES the open gaps (measurement problem, Born rule, preferred basis, quantum gravity, interpretation) and refuses to fill them. Every gap's `fills` is the literal false, so the code cannot claim a solution; the corpus tools are shown as lenses to learn through, never fillings. HARMONY ≠ TRUTH."
    }
  }
]

export default translations
