// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "dom",
    "uuid": "ac5bfa28-c6cb-8b11-920a-9ae2edc352ef",
    "words": [
      "dom"
    ],
    "values": {
      "en": "dom"
    }
  },
  {
    "key": "description",
    "source": "Use when code must branch on whether a real browser DOM is available — a default boolean that is true only when window, window.document and document.createElement all exist, guarding browser-only work on the server or in non-DOM runtimes.",
    "uuid": "728093a6-b5b7-8323-ad6f-7afcb4caf548",
    "words": [
      "use",
      "when",
      "code",
      "must",
      "branch",
      "on",
      "whether",
      "a",
      "real",
      "browser",
      "dom",
      "is",
      "available",
      "a",
      "default",
      "boolean",
      "that",
      "is",
      "true",
      "only",
      "when",
      "window",
      "window",
      "document",
      "and",
      "document",
      "createelement",
      "all",
      "exist",
      "guarding",
      "browser",
      "only",
      "work",
      "on",
      "the",
      "server",
      "or",
      "in",
      "non",
      "dom",
      "runtimes"
    ],
    "values": {
      "en": "Use when code must branch on whether a real browser DOM is available — a default boolean that is true only when window, window.document and document.createElement all exist, guarding browser-only work on the server or in non-DOM runtimes."
    }
  }
]

export default translations
