// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "agent",
    "uuid": "5d45901e-1d7e-8e1c-ab39-b5460ceae031",
    "words": [
      "agent"
    ],
    "values": {
      "en": "agent"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about agent — Use to audit an agent's own changeset the way a real auditor audits a human's submission — every claim (@invariant · @standard · @compliance · @audit) in a changed code file must have a proof leg beside it, or the submission is refused. ISO 19011 §6.4: a finding traces to objective evidence. Run: git diff --name-only | tsx src/audit/agent/index.ts",
    "uuid": "288c46e0-b8a7-846e-a6b3-473bf9d11755",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "agent",
      "use",
      "to",
      "audit",
      "an",
      "agent",
      "s",
      "own",
      "changeset",
      "the",
      "way",
      "a",
      "real",
      "auditor",
      "audits",
      "a",
      "human",
      "s",
      "submission",
      "every",
      "claim",
      "invariant",
      "standard",
      "compliance",
      "audit",
      "in",
      "a",
      "changed",
      "code",
      "file",
      "must",
      "have",
      "a",
      "proof",
      "leg",
      "beside",
      "it",
      "or",
      "the",
      "submission",
      "is",
      "refused",
      "iso",
      "a",
      "finding",
      "traces",
      "to",
      "objective",
      "evidence",
      "run",
      "git",
      "diff",
      "name",
      "only",
      "tsx",
      "src",
      "audit",
      "agent",
      "index",
      "ts"
    ],
    "values": {
      "en": "Use when reasoning about agent — Use to audit an agent's own changeset the way a real auditor audits a human's submission — every claim (@invariant · @standard · @compliance · @audit) in a changed code file must have a proof leg beside it, or the submission is refused. ISO 19011 §6.4: a finding traces to objective evidence. Run: git diff --name-only | tsx src/audit/agent/index.ts"
    }
  }
]

export default translations
