// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "backup",
    "uuid": "4e82a4a9-a326-8ca8-9460-3842108e0235",
    "words": [
      "backup"
    ],
    "values": {
      "en": "backup"
    }
  },
  {
    "key": "description",
    "source": "Use when ensuring data recovery — backup strategy (full/incremental/differential), backup retention, restoration procedures, backup encryption, cross-region backups, RTO/RPO targets, backup testing/validation.",
    "uuid": "0f300506-ea13-8a78-83c9-e3af6782b001",
    "words": [
      "use",
      "when",
      "ensuring",
      "data",
      "recovery",
      "backup",
      "strategy",
      "full",
      "incremental",
      "differential",
      "backup",
      "retention",
      "restoration",
      "procedures",
      "backup",
      "encryption",
      "cross",
      "region",
      "backups",
      "rto",
      "rpo",
      "targets",
      "backup",
      "testing",
      "validation"
    ],
    "values": {
      "en": "Use when ensuring data recovery — backup strategy (full/incremental/differential), backup retention, restoration procedures, backup encryption, cross-region backups, RTO/RPO targets, backup testing/validation."
    }
  }
]

export default translations
