// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "resolution",
    "uuid": "988ea9e7-5487-880d-abc2-8cb1575b44f0",
    "words": [
      "resolution"
    ],
    "values": {
      "en": "resolution"
    }
  },
  {
    "key": "description",
    "source": "Use when closing or resolving a ticket, issue, or complaint — root-cause analysis, solution implementation, confirmation, closure. The endpoint of a support lifecycle.",
    "uuid": "cc4b01d6-6f8c-8ac6-995d-557812b45433",
    "words": [
      "use",
      "when",
      "closing",
      "or",
      "resolving",
      "a",
      "ticket",
      "issue",
      "or",
      "complaint",
      "root",
      "cause",
      "analysis",
      "solution",
      "implementation",
      "confirmation",
      "closure",
      "the",
      "endpoint",
      "of",
      "a",
      "support",
      "lifecycle"
    ],
    "values": {
      "en": "Use when closing or resolving a ticket, issue, or complaint — root-cause analysis, solution implementation, confirmation, closure. The endpoint of a support lifecycle."
    }
  }
]

export default translations
