// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "element",
    "uuid": "c35021d5-7942-8d83-85d0-0e962804e55d",
    "words": [
      "element"
    ],
    "values": {
      "en": "element"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about an identity element.",
    "uuid": "4f621426-823f-864b-89fe-97eb186ed5ba",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "an",
      "identity",
      "element"
    ],
    "values": {
      "en": "Use when reasoning about an identity element."
    }
  }
]

export default translations
