import type { TradingApi } from '@/trading/api'
/**
 * trading/api/money — the money-rails (payment · banking · FX · e-invoicing/EDI) slice of the trading-API registry.
 *
 * Split out of the trading/api hub so the parent index.ts stays a thin barrel
 * ([[rules]]/concentration): the registry is one flat array; region + category are
 * fields, not keys, so the money/goods halves are pure data leaves. The parent
 * concatenates them into TRADING_APIS and owns the region/category query functions.
 * Type-only import back to the parent — erased at runtime, so no cycle.
 */
export const MONEY_TRADING_APIS: ReadonlyArray<TradingApi> = [
  {
    category: 'payment_gateway', provider: 'myPOS', name: 'myPOS Online Payments (IPC)',
    region: 'BG', endpoint: 'https://www.mypos.com', sandboxEndpoint: 'https://demo.developers.mypos.eu',
    auth: 'hmac', format: 'mixed',
    documentation: 'https://developers.mypos.com/en/doc/online_payments/v1_4/20-api-reference',
    description: 'BG-origin acquirer/POS; online IPCPurchase/PreAuth via RSA-SHA256-signed POST.',
    clientImplemented: false,
    notes: 'BG-critical. Per-store RSA key pair (SID + KeyIndex). Production IPC gateway host ships in the merchant config pack — unverified until live onboarding.',
  },
  {
    category: 'payment_gateway', provider: 'BORICA', name: 'BORICA e-Commerce Gateway (APGW / 3-D Secure)',
    region: 'BG', endpoint: 'https://3dsgate.borica.bg', sandboxEndpoint: 'https://3dsgate-dev.borica.bg',
    auth: 'hmac', format: 'mixed',
    documentation: 'https://www.borica.bg/en/products-and-services/helpdesk-za-razrabotchitsi',
    description: 'BG bank-owned card acquiring gateway (Visa/Mastercard/Amex/JCB) with 3-D Secure.',
    clientImplemented: false,
    notes: 'BG-critical: owned by 19 BG banks, default card rail for most BG merchant accounts. MAC/RSA-signed form POST. Production host inferred from the dev pair — verify on onboarding.',
  },
  {
    category: 'payment_gateway', provider: 'ePay.bg', name: 'ePay.bg WEB API',
    region: 'BG', endpoint: 'https://www.epay.bg', sandboxEndpoint: 'https://demo.epay.bg/xdev/api',
    auth: 'hmac', format: 'json',
    documentation: 'https://kb.epay.bg/en/',
    description: 'Dominant BG online wallet/card gateway; JSON REST with APPID/DEVICEID/TOKEN + checksum.',
    clientImplemented: false,
    notes: 'BG-critical incumbent e-wallet; pairs with easyPay for cash. HMAC-style CHECKSUM per request. Confirm prod base path before shipping.',
  },
  {
    category: 'payment_gateway', provider: 'easyPay', name: 'easyPay (ePay.bg cash network)',
    region: 'BG', endpoint: 'https://www.easypay.bg',
    auth: 'hmac', format: 'json',
    documentation: 'https://kb.epay.bg/en/web/easypay/',
    description: 'BG cash-in/voucher network; cash collection for online orders via the ePay.bg API.',
    clientImplemented: false,
    notes: 'BG-critical for cash-paying customers ("плати в брой на easyPay"). Rides the ePay.bg WEB API (composes with that entry).',
  },
  {
    category: 'payment_gateway', provider: 'iCard', name: 'iCard / iPay Payment Gateway (IPG)',
    region: 'BG', endpoint: 'https://www.icards.eu',
    auth: 'hmac', format: 'mixed',
    documentation: 'https://github.com/iCardDirect/IPG-Documentation',
    description: 'BG-licensed EMI; card acquiring + iPay wallet via the iCardDirect iPayment Gateway.',
    clientImplemented: false,
    notes: 'BG-critical: iCard AD is a BG e-money institution (parent of myPOS). Signed form-POST. Production IPG host provisional. Its PSD2 API (docs.openbank.icard.com) is a separate banking entry.',
  },
  {
    category: 'payment_gateway', provider: 'Paysera', name: 'Paysera Checkout API',
    region: 'EU', endpoint: 'https://checkout-eu-a.paysera.com/checkout/rest/v1',
    auth: 'hmac', format: 'json',
    documentation: 'https://developers.paysera.com/en/checkout/basic',
    description: 'EU EMI checkout aggregating cards + local bank methods; common low-cost rail for BG SMEs.',
    clientImplemented: false,
    notes: 'project_id + sign_password (HMAC ss1 + RSA ss2). Operates in BG.',
  },
  {
    category: 'payment_gateway', provider: 'Stripe', name: 'Stripe Payments & Connect API',
    region: 'GLOBAL', endpoint: 'https://api.stripe.com',
    auth: 'api_key', format: 'json',
    documentation: 'https://docs.stripe.com/api',
    description: 'Global card/wallet acquirer + Connect; tokenized card capture (minimal PCI scope).',
    clientImplemented: false,
    notes: 'ALREADY WIRED via @payloadcms/plugin-ecommerce stripeAdapter (src/ecommerce/) with per-tenant secrets — this row is catalogue metadata only; do NOT build a parallel client. Single base; mode follows key prefix.',
  },
  {
    category: 'payment_gateway', provider: 'Adyen', name: 'Adyen Checkout API',
    region: 'GLOBAL', endpoint: 'https://{PREFIX}-checkout-live.adyenpayments.com/checkout', sandboxEndpoint: 'https://checkout-test.adyen.com',
    auth: 'api_key', format: 'json',
    documentation: 'https://docs.adyen.com/api-explorer/Checkout/latest/overview',
    description: 'Global enterprise acquirer/PSP; unified Checkout API (X-API-Key).',
    clientImplemented: false,
    notes: 'Live host carries a per-merchant {PREFIX} — resolve from tenant config, never hardcode. Test host is fixed.',
  },
  {
    category: 'payment_gateway', provider: 'PayPal', name: 'PayPal REST (Orders/Payments) API',
    region: 'GLOBAL', endpoint: 'https://api-m.paypal.com', sandboxEndpoint: 'https://api-m.sandbox.paypal.com',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.paypal.com/api/rest/',
    description: 'Global wallet + card processing; OAuth2 client-credentials bearer tokens.',
    clientImplemented: false,
  },
  {
    category: 'payment_gateway', provider: 'Braintree', name: 'Braintree GraphQL API',
    region: 'GLOBAL', endpoint: 'https://payments.braintree-api.com/graphql', sandboxEndpoint: 'https://payments.sandbox.braintree-api.com/graphql',
    auth: 'basic', format: 'json',
    documentation: 'https://developer.paypal.com/braintree/graphql/guides/making_api_calls/',
    description: 'PayPal-owned card acquirer/gateway; GraphQL over Base64 public:private key.',
    clientImplemented: false,
    notes: 'Authorization: Basic base64(public_key:private_key); requires a Braintree-Version header.',
  },
  {
    category: 'payment_gateway', provider: 'Mollie', name: 'Mollie Payments API',
    region: 'EU', endpoint: 'https://api.mollie.com',
    auth: 'api_key', format: 'json',
    documentation: 'https://docs.mollie.com/reference/overview',
    description: 'EU PSP aggregating cards + European local methods (iDEAL, Bancontact, SEPA).',
    clientImplemented: false,
    notes: 'Single base; test/live selected by key prefix.',
  },
  {
    category: 'payment_gateway', provider: 'Checkout.com', name: 'Checkout.com Payments API',
    region: 'GLOBAL', endpoint: 'https://api.checkout.com', sandboxEndpoint: 'https://api.sandbox.checkout.com',
    auth: 'oauth2', format: 'json',
    documentation: 'https://www.checkout.com/docs/developer-resources/api',
    description: 'Global enterprise acquirer; OAuth2 client-credentials or Bearer secret key.',
    clientImplemented: false,
    notes: 'Token issuance may use a per-client {prefix} subdomain; payments served on the plain hosts.',
  },
  {
    category: 'payment_gateway', provider: 'Worldpay', name: 'Worldpay Access (Card Payments) API',
    region: 'GLOBAL', endpoint: 'https://access.worldpay.com', sandboxEndpoint: 'https://try.access.worldpay.com',
    auth: 'basic', format: 'json',
    documentation: 'https://developer.worldpay.com/products/access',
    description: 'Global acquirer; Access REST APIs over HTTP Basic with versioned media types.',
    clientImplemented: false,
    notes: 'Pin a version via WP-Api-Version / Accept media types. Separate Try vs Live credentials.',
  },
  {
    category: 'direct_debit', provider: 'GoCardless', name: 'GoCardless Bank Debit API',
    region: 'GLOBAL', endpoint: 'https://api.gocardless.com', sandboxEndpoint: 'https://api-sandbox.gocardless.com',
    auth: 'api_key', format: 'json',
    documentation: 'https://developer.gocardless.com/api-reference/',
    description: 'Recurring bank debit (SEPA Core/B2B, BACS, ACH) via mandates + payments.',
    clientImplemented: false,
    notes: 'Bearer token + a GoCardless-Version header. SEPA DD makes it EU/BG-relevant for subscription billing.',
  },
  {
    category: 'payout_provider', provider: 'Wise', name: 'Wise Platform API',
    region: 'GLOBAL', endpoint: 'https://api.transferwise.com', sandboxEndpoint: 'https://api.sandbox.transferwise.tech',
    auth: 'oauth2', format: 'json',
    documentation: 'https://docs.wise.com/api-reference',
    description: 'Cross-border payouts / multi-currency: quote → recipient → transfer → fund.',
    clientImplemented: false,
    notes: 'Money-out, not acquiring. SCA-sensitive moves need an extra X-Signature (RSA) header.',
  },
  {
    category: 'payment_gateway', provider: 'Revolut', name: 'Revolut Merchant API',
    region: 'EU', endpoint: 'https://merchant.revolut.com', sandboxEndpoint: 'https://sandbox-merchant.revolut.com',
    auth: 'api_key', format: 'json',
    documentation: 'https://developer.revolut.com/docs/merchant/merchant-api',
    description: 'Revolut acquiring: server-side Orders via Secret key + Revolut Pay checkout.',
    clientImplemented: false,
    notes: 'The Merchant (acquiring) API — distinct from the Revolut Business banking API (b2b.revolut.com, OAuth2 + client-assertion JWT).',
  },
  {
    category: 'peppol_access_point', provider: 'Storecove', name: 'Storecove E-invoicing / Peppol Access Point API',
    region: 'GLOBAL', endpoint: 'https://api.storecove.com/api/v2',
    auth: 'api_key', format: 'json',
    documentation: 'https://www.storecove.com/docs/',
    description: 'Send/receive Peppol + email e-invoices via clean REST/JSON; registration, discovery, webhooks.',
    clientImplemented: false,
    notes: 'Cleanest self-serve REST AP; published OpenAPI. Sandbox is an account-level mode. Strong default BG/EU Peppol AP.',
  },
  {
    category: 'peppol_access_point', provider: 'Qvalia', name: 'Qvalia Peppol / Invoicing API',
    region: 'EU', endpoint: 'https://api.qvalia.io',
    auth: 'api_key', format: 'xml',
    documentation: 'https://api.qvalia.io/qvalia-developer-tools/api',
    description: 'White-label Peppol AP: send/receive BIS Billing invoices, credit notes, invoice-response.',
    clientImplemented: false,
    notes: 'REST envelope, strict UBL/BIS Billing 3.0 payloads. Documented sandbox.',
  },
  {
    category: 'peppol_access_point', provider: 'Unimaze', name: 'Unimaze Messaging API (Peppol Access Point)',
    region: 'EU', endpoint: 'https://apidocs.unimaze.com',
    auth: 'basic', format: 'mixed',
    documentation: 'https://apidocs.unimaze.com',
    description: 'Send/receive Peppol business documents with automatic format conversion to recipient formats.',
    clientImplemented: false,
    notes: 'HTTP Basic. Production base/version path not public — resolve on onboarding.',
  },
  {
    category: 'peppol_access_point', provider: 'Tickstar (Pagero)', name: 'Galaxy Gateway SMP Manager API v2',
    region: 'EU', endpoint: 'https://www.galaxygw.com/support/smp-manager-api-2/',
    auth: 'api_key', format: 'xml',
    documentation: 'https://www.tickstar.com/article/smp-manager-api-v-2/',
    description: 'Programmatic SMP receiver management on Tickstar/Galaxy Gateway Peppol infrastructure.',
    clientImplemented: false,
    notes: 'SMP-management (receiver registration), not self-serve send/receive. Per-tenant base. Underpins Pagero.',
  },
  {
    category: 'edi_network', provider: 'SPS Commerce', name: 'SPS Commerce Fulfillment / Transaction API',
    region: 'GLOBAL', endpoint: 'https://api.spscommerce.com',
    auth: 'oauth2', format: 'json',
    documentation: 'https://docs.api.spscommerce.com/',
    description: 'Retail supply-chain network: POs, ASNs, invoices, shipping-label + packing-slip APIs.',
    clientImplemented: false,
    notes: 'Free self-serve Dev Center; OAuth2 + JSON REST. Strongest clean API among the EDI VANs.',
  },
  {
    category: 'edi_network', provider: 'Tradeshift', name: 'Tradeshift REST API',
    region: 'GLOBAL', endpoint: 'https://api.tradeshift.com/tradeshift/rest/external',
    auth: 'oauth2', format: 'xml',
    documentation: 'https://developers.tradeshift.com/docs/api',
    description: 'B2B network + AP automation: create/send invoices and business documents (native UBL).',
    clientImplemented: false,
    notes: 'REST API, core payloads UBL XML. App registration / OAuth per tenant.',
  },
  {
    category: 'edi_network', provider: 'Cleo', name: 'Cleo Integration Cloud (CIC) API',
    region: 'GLOBAL', endpoint: 'https://support.cleo.com/hc/en-us/articles/360045587533-Documentation',
    auth: 'api_key', format: 'mixed',
    documentation: 'https://www.cleo.com/blog/sending-data-to-cleo-integration-cloud',
    description: 'EDI/API integration platform (VAN + iPaaS): REST ingress routed over AS2/SFTP/OFTP.',
    clientImplemented: false,
    notes: 'Contract-provisioned tenant instance; no public self-serve REST base. Catalogue-only.',
  },
  {
    category: 'edi_network', provider: 'EDICOM', name: 'EDICOM Global Platform (EDI / e-invoicing API)',
    region: 'GLOBAL', endpoint: 'https://edicomgroup.com/edi-software',
    auth: 'api_key', format: 'mixed',
    documentation: 'https://www.edicomgroup.com/solutions/einvoicing/EDICOM-Platform-Architecture.html',
    description: 'Global multi-standard EDI + e-invoicing SaaS with per-country compliance rules.',
    clientImplemented: false,
    notes: 'No public developer portal; API/WSDL tenant-specific + onboarding-gated. Catalogue-only.',
  },
  {
    category: 'edi_network', provider: 'OpenText (GXS / Trading Grid)', name: 'OpenText Trading Grid / Business Network',
    region: 'GLOBAL', endpoint: 'https://developer.opentext.com/resources/documentation/Trading%20Grid',
    auth: 'oauth2', format: 'mixed',
    documentation: 'https://developer.opentext.com/resources/documentation/Trading%20Grid',
    description: 'Large managed-services VAN: any-to-any B2B document exchange with application connectors.',
    clientImplemented: false,
    notes: 'Enterprise managed-services VAN; base URLs/credentials contract-provisioned. Catalogue-only.',
  },
  {
    category: 'edi_network', provider: 'Comarch', name: 'Comarch EDI Platform',
    region: 'EU', endpoint: 'https://www.comarchedi.com/',
    auth: 'api_key', format: 'mixed',
    documentation: 'https://www.comarch.com/trade-and-services/data-management/edi/',
    description: 'Cloud EDI/B2B platform across 60+ countries: orders, invoices, despatch advices.',
    clientImplemented: false,
    notes: 'Strong CEE/Poland footprint (BG-region relevant). No public self-serve REST docs. Catalogue-only.',
  },
  {
    category: 'banking_aggregator', provider: 'GoCardless', name: 'GoCardless Bank Account Data (ex-Nordigen)',
    region: 'EU', endpoint: 'https://bankaccountdata.gocardless.com/api/v2',
    auth: 'oauth2', format: 'json',
    documentation: 'https://developer.gocardless.com/bank-account-data/overview',
    description: 'One API → ~2,500 EU/UK bank PSD2 AIS feeds (accounts/balances/90-day transactions) for reconciliation.',
    clientImplemented: false,
    notes: 'Free tier. Covers BG banks (DSK, UniCredit Bulbank, Postbank) via Nordigen connectors. secret_id+secret_key → bearer token.',
  },
  {
    category: 'banking_aggregator', provider: 'Plaid', name: 'Plaid API',
    region: 'GLOBAL', endpoint: 'https://production.plaid.com', sandboxEndpoint: 'https://sandbox.plaid.com',
    auth: 'api_key', format: 'json',
    documentation: 'https://plaid.com/docs/api/',
    description: 'Bank-data + payments aggregator (Transactions, Auth, Balance). Dominant US/CA.',
    clientImplemented: false,
    notes: 'client_id + secret in body. Weak BG/EU coverage vs GoCardless/Tink/Salt Edge.',
  },
  {
    category: 'banking_aggregator', provider: 'TrueLayer', name: 'TrueLayer Data & Payments API',
    region: 'EU', endpoint: 'https://api.truelayer.com', sandboxEndpoint: 'https://api.truelayer-sandbox.com',
    auth: 'oauth2', format: 'json',
    documentation: 'https://docs.truelayer.com/',
    description: 'UK/EU open-banking: Data API (accounts/transactions) + Payments API (PIS).',
    clientImplemented: false,
    notes: 'Strong UK + Western-EU; BG coverage thin. Auth host auth.truelayer.com.',
  },
  {
    category: 'banking_aggregator', provider: 'Tink', name: 'Tink (Visa) Account Aggregation',
    region: 'EU', endpoint: 'https://api.tink.com/api/v1',
    auth: 'oauth2', format: 'json',
    documentation: 'https://docs.tink.com/api',
    description: 'EU bank-data aggregator (~3,400 banks) via the Tink Link consent flow.',
    clientImplemented: false,
    notes: 'OAuth2 client credentials + Tink Link end-user auth. Broad BG coverage.',
  },
  {
    category: 'banking_aggregator', provider: 'Salt Edge', name: 'Salt Edge Open Banking Gateway (v6 AIS)',
    region: 'EU', endpoint: 'https://www.saltedge.com/api/v6',
    auth: 'api_key', format: 'json',
    documentation: 'https://docs.saltedge.com/v6/',
    description: 'EU/global account-information aggregator with explicit Bulgaria coverage.',
    clientImplemented: false,
    notes: 'App-id / Secret headers; some flows need a signed (RSA) request. Publishes a BG coverage list.',
  },
  {
    category: 'banking_aggregator', provider: 'Yapily', name: 'Yapily Open Banking API',
    region: 'EU', endpoint: 'https://api.yapily.com',
    auth: 'basic', format: 'json',
    documentation: 'https://docs.yapily.com/api/reference/',
    description: 'EU/UK open-banking infrastructure (~1,900 institutions): accounts/transactions + payments.',
    clientImplemented: false,
    notes: 'HTTP Basic with Application-ID + Application-Secret. No front-end SDK.',
  },
  {
    category: 'fx_rates', provider: 'Frankfurter', name: 'Frankfurter FX API',
    region: 'EU', endpoint: 'https://api.frankfurter.dev/v1',
    auth: 'none', format: 'json',
    documentation: 'https://frankfurter.dev/',
    description: 'Free, key-less ECB-derived daily reference rates (latest/historical/time-series + CSV).',
    clientImplemented: true,
    notes: 'Clean queryable REST sibling of the raw ECB_RATES XML — best free IAS-21 feed. Client: fetchFrankfurterRates.',
  },
  {
    category: 'fx_rates', provider: 'ExchangeRate-API', name: 'ExchangeRate-API (open access)',
    region: 'GLOBAL', endpoint: 'https://open.er-api.com/v6/latest',
    auth: 'none', format: 'json',
    documentation: 'https://www.exchangerate-api.com/docs/free',
    description: 'Free key-less open endpoint returning latest rates for a base currency; daily refresh.',
    clientImplemented: true,
    notes: 'Key-less product is open.er-api.com (keyed v6.exchangerate-api.com is a separate paid tier). Client: fetchExchangeRateApiRates.',
  },
  {
    category: 'fx_rates', provider: 'exchangerate.host', name: 'exchangerate.host',
    region: 'GLOBAL', endpoint: 'https://api.exchangerate.host',
    auth: 'api_key', format: 'json',
    documentation: 'https://exchangerate.host/documentation',
    description: 'FX live/historical/convert (fiat + crypto). Now an apilayer product requiring an access_key.',
    clientImplemented: false,
    notes: 'Re-platformed under apilayer — the free no-auth era is gone.',
  },
  {
    category: 'fx_rates', provider: 'Open Exchange Rates', name: 'Open Exchange Rates',
    region: 'GLOBAL', endpoint: 'https://openexchangerates.org/api',
    auth: 'api_key', format: 'json',
    documentation: 'https://docs.openexchangerates.org/',
    description: 'Hourly USD-based FX (latest/historical) across many currencies.',
    clientImplemented: false,
    notes: 'app_id query param. Free plan: USD base, hourly.',
  },
  {
    category: 'fx_rates', provider: 'Fixer', name: 'Fixer (apilayer)',
    region: 'EU', endpoint: 'https://data.fixer.io/api',
    auth: 'api_key', format: 'json',
    documentation: 'https://fixer.io/documentation',
    description: 'EUR-anchored FX (latest/historical/convert/timeseries), ECB-sourced base.',
    clientImplemented: false,
    notes: 'access_key query param. Free tier: EUR base only.',
  },
  {
    category: 'fx_rates', provider: 'Twelve Data', name: 'Twelve Data (FX endpoints)',
    region: 'GLOBAL', endpoint: 'https://api.twelvedata.com',
    auth: 'api_key', format: 'json',
    documentation: 'https://twelvedata.com/docs',
    description: 'Real-time + historical FX/equity/crypto market data (/price, /exchange_rate, /time_series).',
    clientImplemented: false,
    notes: 'Market rates ≠ official IAS-21 fixing — indicative valuation only.',
  },
  {
    category: 'fx_rates', provider: 'Polygon.io', name: 'Polygon.io (Forex)',
    region: 'GLOBAL', endpoint: 'https://api.polygon.io',
    auth: 'api_key', format: 'json',
    documentation: 'https://polygon.io/docs/forex',
    description: 'Forex market data — real-time / aggregates / conversion.',
    clientImplemented: false,
    notes: 'Market rates, not official fixings.',
  },
  {
    category: 'fx_rates', provider: 'CoinGecko', name: 'CoinGecko API v3',
    region: 'GLOBAL', endpoint: 'https://api.coingecko.com/api/v3',
    auth: 'none', format: 'json',
    documentation: 'https://docs.coingecko.com/',
    description: 'Free crypto reference prices (/simple/price) across fiat quote currencies.',
    clientImplemented: false,
    notes: 'Demo tier public/no-key. Crypto valuation only — keep minor.',
  },
  {
    category: 'fx_rates', provider: 'Coinbase', name: 'Coinbase Spot Price (v2)',
    region: 'GLOBAL', endpoint: 'https://api.coinbase.com/v2',
    auth: 'none', format: 'json',
    documentation: 'https://docs.cdp.coinbase.com/coinbase-business/track-apis/prices',
    description: 'Public spot price endpoint GET /v2/prices/{pair}/spot (e.g. BTC-EUR) — no auth.',
    clientImplemented: false,
    notes: 'Indicative spot only.',
  },
]

/** @index-cross.foldback child=trading/api/money parent=trading/api — this cross folds back into its parent. */
