// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "drug",
    "uuid": "33d4d851-21d5-823c-b3d5-fb5236ba0ccf",
    "words": [
      "drug"
    ],
    "values": {
      "en": "drug"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about drug — A chemical or biologic substance, used as a medical therapy, that has a physiological effect on an organism. Here the term drug is used interchangeably with the term medicine altho",
    "uuid": "d3b869b7-da0a-8264-9680-4cd1babd93f1",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "drug",
      "a",
      "chemical",
      "or",
      "biologic",
      "substance",
      "used",
      "as",
      "a",
      "medical",
      "therapy",
      "that",
      "has",
      "a",
      "physiological",
      "effect",
      "on",
      "an",
      "organism",
      "here",
      "the",
      "term",
      "drug",
      "is",
      "used",
      "interchangeably",
      "with",
      "the",
      "term",
      "medicine",
      "altho"
    ],
    "values": {
      "en": "Use when reasoning about drug — A chemical or biologic substance, used as a medical therapy, that has a physiological effect on an organism. Here the term drug is used interchangeably with the term medicine altho"
    }
  }
]

export default translations
