// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "models",
    "uuid": "6b507ae3-9f9b-8eb8-a017-f6355492c2e8",
    "words": [
      "models"
    ],
    "values": {
      "en": "models"
    }
  },
  {
    "key": "description",
    "source": "Use when registering, routing, or auditing the AI model fallback catalog — provider/capability/tier per model, EU AI Act risk class, EU-hostable flag for data-residency, feature-guarded dispatch. The admin-editable expert-catalog the router dispatches over when the deterministic core cannot decide alone.",
    "uuid": "c726baca-ac07-83d5-a23f-75a0d19650eb",
    "words": [
      "use",
      "when",
      "registering",
      "routing",
      "or",
      "auditing",
      "the",
      "ai",
      "model",
      "fallback",
      "catalog",
      "provider",
      "capability",
      "tier",
      "per",
      "model",
      "eu",
      "ai",
      "act",
      "risk",
      "class",
      "eu",
      "hostable",
      "flag",
      "for",
      "data",
      "residency",
      "feature",
      "guarded",
      "dispatch",
      "the",
      "admin",
      "editable",
      "expert",
      "catalog",
      "the",
      "router",
      "dispatches",
      "over",
      "when",
      "the",
      "deterministic",
      "core",
      "cannot",
      "decide",
      "alone"
    ],
    "values": {
      "en": "Use when registering, routing, or auditing the AI model fallback catalog — provider/capability/tier per model, EU AI Act risk class, EU-hostable flag for data-residency, feature-guarded dispatch. The admin-editable expert-catalog the router dispatches over when the deterministic core cannot decide alone."
    }
  }
]

export default translations
