// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "visual",
    "uuid": "2d85fbf5-9eab-84e8-99c7-40166fb239ef",
    "words": [
      "visual"
    ],
    "values": {
      "en": "visual"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about visual as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus.",
    "uuid": "bd42141e-1dfe-8a77-85b3-79f93f186d15",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "visual",
      "as",
      "a",
      "schema",
      "org",
      "vocabulary",
      "word",
      "the",
      "single",
      "word",
      "collided",
      "from",
      "the",
      "schema",
      "org",
      "terms",
      "that",
      "contain",
      "it",
      "content",
      "addressed",
      "into",
      "the",
      "corpus"
    ],
    "values": {
      "en": "Use when reasoning about visual as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus."
    }
  }
]

export default translations
