// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "writing",
    "uuid": "b97a1cc7-45ad-80cd-966d-c2028dc9041e",
    "words": [
      "writing"
    ],
    "values": {
      "en": "writing"
    }
  },
  {
    "key": "description",
    "source": "Use when writing must be computed from sealed coordinates — debit/credit prose structure · law lines · wikilink density · eb/word from readme/paper.ts; never prose templates.",
    "uuid": "ab377fe6-834d-8712-8820-1e5190d5ec5b",
    "words": [
      "use",
      "when",
      "writing",
      "must",
      "be",
      "computed",
      "from",
      "sealed",
      "coordinates",
      "debit",
      "credit",
      "prose",
      "structure",
      "law",
      "lines",
      "wikilink",
      "density",
      "eb",
      "word",
      "from",
      "readme",
      "paper",
      "ts",
      "never",
      "prose",
      "templates"
    ],
    "values": {
      "en": "Use when writing must be computed from sealed coordinates — debit/credit prose structure · law lines · wikilink density · eb/word from readme/paper.ts; never prose templates."
    }
  }
]

export default translations
