// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "pricing",
    "uuid": "af45494b-1da3-8154-9aa2-bce89c493832",
    "words": [
      "pricing"
    ],
    "values": {
      "en": "pricing"
    }
  },
  {
    "key": "description",
    "source": "Use when reaching the pricing side of commerce — tiers, subscriptions, metered usage — through its own namespace; the face re-exports the commerce barrel while the matter is still being lifted out of the hub.",
    "uuid": "d4d696de-59a1-8477-b691-4a8c21ae9754",
    "words": [
      "use",
      "when",
      "reaching",
      "the",
      "pricing",
      "side",
      "of",
      "commerce",
      "tiers",
      "subscriptions",
      "metered",
      "usage",
      "through",
      "its",
      "own",
      "namespace",
      "the",
      "face",
      "re",
      "exports",
      "the",
      "commerce",
      "barrel",
      "while",
      "the",
      "matter",
      "is",
      "still",
      "being",
      "lifted",
      "out",
      "of",
      "the",
      "hub"
    ],
    "values": {
      "en": "Use when reaching the pricing side of commerce — tiers, subscriptions, metered usage — through its own namespace; the face re-exports the commerce barrel while the matter is still being lifted out of the hub."
    }
  }
]

export default translations
