// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "storage",
    "uuid": "bcee589e-7867-8b83-98be-488b4768f315",
    "words": [
      "storage"
    ],
    "values": {
      "en": "storage"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about storage as a part of computer — vocabulary pivot to @/storage; nested not duplicated.",
    "uuid": "996a4f2f-9cc1-82f0-ac9b-308bec2c1f23",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "storage",
      "as",
      "a",
      "part",
      "of",
      "computer",
      "vocabulary",
      "pivot",
      "to",
      "storage",
      "nested",
      "not",
      "duplicated"
    ],
    "values": {
      "en": "Use when reasoning about storage as a part of computer — vocabulary pivot to @/storage; nested not duplicated."
    }
  }
]

export default translations
