// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "pages",
    "uuid": "6ba73b2e-3590-8783-bb72-8415c999332b",
    "words": [
      "pages"
    ],
    "values": {
      "en": "pages"
    }
  },
  {
    "key": "description",
    "source": "Use when creating or managing CMS pages — hero blocks, content blocks, forms, SEO meta — with per-tenant unique slugs, versioned drafts, breadcrumb hierarchy, and i18n routing. The Payload CMS page collection.",
    "uuid": "395d1989-95cd-8063-89d1-b32252341067",
    "words": [
      "use",
      "when",
      "creating",
      "or",
      "managing",
      "cms",
      "pages",
      "hero",
      "blocks",
      "content",
      "blocks",
      "forms",
      "seo",
      "meta",
      "with",
      "per",
      "tenant",
      "unique",
      "slugs",
      "versioned",
      "drafts",
      "breadcrumb",
      "hierarchy",
      "and",
      "i18n",
      "routing",
      "the",
      "payload",
      "cms",
      "page",
      "collection"
    ],
    "values": {
      "en": "Use when creating or managing CMS pages — hero blocks, content blocks, forms, SEO meta — with per-tenant unique slugs, versioned drafts, breadcrumb hierarchy, and i18n routing. The Payload CMS page collection."
    }
  }
]

export default translations
