// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "works",
    "uuid": "385d8f56-52c6-8f51-b4e7-4b99832c9941",
    "words": [
      "works"
    ],
    "values": {
      "en": "works"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about works — Organizations that the person works for.",
    "uuid": "997174e6-a42e-824c-834c-2e9b8e7f1fe3",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "works",
      "organizations",
      "that",
      "the",
      "person",
      "works",
      "for"
    ],
    "values": {
      "en": "Use when reasoning about works — Organizations that the person works for."
    }
  }
]

export default translations
