// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "frameworks",
    "uuid": "71e6ff18-4bd2-849b-9f33-0d661a61fd80",
    "words": [
      "frameworks"
    ],
    "values": {
      "en": "frameworks"
    }
  },
  {
    "key": "description",
    "source": "Use when registering or browsing the reference library of compliance frameworks — IFRS, SOX, GDPR, ISO-27001, COSO, tax, ESG, banking — with code, category, issuing body, effective date, and official resource URL; super-admin-only writes, tenant-read. The read-only compliance-framework master that ComplianceRequirements link to.",
    "uuid": "63cf34b2-e9a0-811a-9451-7aaad474bf0d",
    "words": [
      "use",
      "when",
      "registering",
      "or",
      "browsing",
      "the",
      "reference",
      "library",
      "of",
      "compliance",
      "frameworks",
      "ifrs",
      "sox",
      "gdpr",
      "iso",
      "coso",
      "tax",
      "esg",
      "banking",
      "with",
      "code",
      "category",
      "issuing",
      "body",
      "effective",
      "date",
      "and",
      "official",
      "resource",
      "url",
      "super",
      "admin",
      "only",
      "writes",
      "tenant",
      "read",
      "the",
      "read",
      "only",
      "compliance",
      "framework",
      "master",
      "that",
      "compliancerequirements",
      "link",
      "to"
    ],
    "values": {
      "en": "Use when registering or browsing the reference library of compliance frameworks — IFRS, SOX, GDPR, ISO-27001, COSO, tax, ESG, banking — with code, category, issuing body, effective date, and official resource URL; super-admin-only writes, tenant-read. The read-only compliance-framework master that ComplianceRequirements link to."
    }
  }
]

export default translations
