// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "photograph",
    "uuid": "7332e2e0-e2e3-847e-84a8-041439c61867",
    "words": [
      "photograph"
    ],
    "values": {
      "en": "photograph"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about photograph — A photograph.",
    "uuid": "d8bde912-55c8-8468-94d5-342a2f9c05c7",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "photograph",
      "a",
      "photograph"
    ],
    "values": {
      "en": "Use when reasoning about photograph — A photograph."
    }
  }
]

export default translations
