// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "zoroastrianism",
    "uuid": "9cbc66d7-2bfc-82b3-844d-c2c4ee1a19f0",
    "words": [
      "zoroastrianism"
    ],
    "values": {
      "en": "zoroastrianism"
    }
  },
  {
    "key": "description",
    "source": "Use when reading Zoroastrianism as a diamond of invariant atoms — the cosmic contest of truth/order (asha) against the lie (druj), the sacred fire as witness, good thoughts-words-deeds, the final renovation as return to perfected zero. The source of erpax's angel/archangel polarity (Spenta Mainyu vs Angra Mainyu). Strip the Avestan prefix and asha, druj, frashokereti collapse to order/law, profane, zeropoint.",
    "uuid": "bce2d141-55fb-8cef-8a6c-6b5e8b2f0146",
    "words": [
      "use",
      "when",
      "reading",
      "zoroastrianism",
      "as",
      "a",
      "diamond",
      "of",
      "invariant",
      "atoms",
      "the",
      "cosmic",
      "contest",
      "of",
      "truth",
      "order",
      "asha",
      "against",
      "the",
      "lie",
      "druj",
      "the",
      "sacred",
      "fire",
      "as",
      "witness",
      "good",
      "thoughts",
      "words",
      "deeds",
      "the",
      "final",
      "renovation",
      "as",
      "return",
      "to",
      "perfected",
      "zero",
      "the",
      "source",
      "of",
      "erpax",
      "s",
      "angel",
      "archangel",
      "polarity",
      "spenta",
      "mainyu",
      "vs",
      "angra",
      "mainyu",
      "strip",
      "the",
      "avestan",
      "prefix",
      "and",
      "asha",
      "druj",
      "frashokereti",
      "collapse",
      "to",
      "order",
      "law",
      "profane",
      "zeropoint"
    ],
    "values": {
      "en": "Use when reading Zoroastrianism as a diamond of invariant atoms — the cosmic contest of truth/order (asha) against the lie (druj), the sacred fire as witness, good thoughts-words-deeds, the final renovation as return to perfected zero. The source of erpax's angel/archangel polarity (Spenta Mainyu vs Angra Mainyu). Strip the Avestan prefix and asha, druj, frashokereti collapse to order/law, profane, zeropoint."
    }
  }
]

export default translations
