// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "improve",
    "uuid": "2d180b02-a473-8ebd-a944-887b4d0a30f5",
    "words": [
      "improve"
    ],
    "values": {
      "en": "improve"
    }
  },
  {
    "key": "description",
    "source": "Use when standards must chat and improve via architectural reuse — addressIndex O(1), crack non-reuse, free-chat@tokens=0, emit waves. Uses quantum/ftl; path is standards/improve — not a domain ftl path.",
    "uuid": "0b1f211e-6454-8e7d-935e-309860612f81",
    "words": [
      "use",
      "when",
      "standards",
      "must",
      "chat",
      "and",
      "improve",
      "via",
      "architectural",
      "reuse",
      "addressindex",
      "o",
      "crack",
      "non",
      "reuse",
      "free",
      "chat",
      "tokens",
      "emit",
      "waves",
      "uses",
      "quantum",
      "ftl",
      "path",
      "is",
      "standards",
      "improve",
      "not",
      "a",
      "domain",
      "ftl",
      "path"
    ],
    "values": {
      "en": "Use when standards must chat and improve via architectural reuse — addressIndex O(1), crack non-reuse, free-chat@tokens=0, emit waves. Uses quantum/ftl; path is standards/improve — not a domain ftl path."
    }
  }
]

export default translations
