// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "budget",
    "uuid": "73f277f7-2353-8e49-9961-288db64369d0",
    "words": [
      "budget"
    ],
    "values": {
      "en": "budget"
    }
  }
]

export default translations
