// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "sunni",
    "uuid": "e9d9548a-e602-87cd-90ed-85af5594c55c",
    "words": [
      "sunni"
    ],
    "values": {
      "en": "sunni"
    }
  },
  {
    "key": "description",
    "source": "Use when reading Sunni Islam as a sub-diamond of islam — the people of the trodden way (sunna) and the community, leadership settled by consensus (ijma), law derived through the agreed schools. A facet-diamond of the islam archangel. Strip the Arabic prefix and sunna, ijma collapse to the followed sequence and the merge of consensus.",
    "uuid": "32fc3a11-6550-8214-b680-1d17793657af",
    "words": [
      "use",
      "when",
      "reading",
      "sunni",
      "islam",
      "as",
      "a",
      "sub",
      "diamond",
      "of",
      "islam",
      "the",
      "people",
      "of",
      "the",
      "trodden",
      "way",
      "sunna",
      "and",
      "the",
      "community",
      "leadership",
      "settled",
      "by",
      "consensus",
      "ijma",
      "law",
      "derived",
      "through",
      "the",
      "agreed",
      "schools",
      "a",
      "facet",
      "diamond",
      "of",
      "the",
      "islam",
      "archangel",
      "strip",
      "the",
      "arabic",
      "prefix",
      "and",
      "sunna",
      "ijma",
      "collapse",
      "to",
      "the",
      "followed",
      "sequence",
      "and",
      "the",
      "merge",
      "of",
      "consensus"
    ],
    "values": {
      "en": "Use when reading Sunni Islam as a sub-diamond of islam — the people of the trodden way (sunna) and the community, leadership settled by consensus (ijma), law derived through the agreed schools. A facet-diamond of the islam archangel. Strip the Arabic prefix and sunna, ijma collapse to the followed sequence and the merge of consensus."
    }
  }
]

export default translations
