// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "clock",
    "uuid": "ecaecf05-7456-8321-a1c5-9022b41f39a1",
    "words": [
      "clock"
    ],
    "values": {
      "en": "clock"
    }
  },
  {
    "key": "description",
    "source": "Use when order must be provable — one clock replacing 621 scattered time reads, where each tick folds (prev ⊕ content) so reordering or editing history breaks every later address. Supplies the interval dimension quantum/ftl lacks. Logical order, not seconds. Run: tsx src/quantum/clock/index.ts",
    "uuid": "58427464-0d70-821a-b7cf-8e7e57df3b69",
    "words": [
      "use",
      "when",
      "order",
      "must",
      "be",
      "provable",
      "one",
      "clock",
      "replacing",
      "scattered",
      "time",
      "reads",
      "where",
      "each",
      "tick",
      "folds",
      "prev",
      "content",
      "so",
      "reordering",
      "or",
      "editing",
      "history",
      "breaks",
      "every",
      "later",
      "address",
      "supplies",
      "the",
      "interval",
      "dimension",
      "quantum",
      "ftl",
      "lacks",
      "logical",
      "order",
      "not",
      "seconds",
      "run",
      "tsx",
      "src",
      "quantum",
      "clock",
      "index",
      "ts"
    ],
    "values": {
      "en": "Use when order must be provable — one clock replacing 621 scattered time reads, where each tick folds (prev ⊕ content) so reordering or editing history breaks every later address. Supplies the interval dimension quantum/ftl lacks. Logical order, not seconds. Run: tsx src/quantum/clock/index.ts"
    }
  }
]

export default translations
