// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "episodes",
    "uuid": "afe9b999-e778-85c7-8439-a66f7e957d87",
    "words": [
      "episodes"
    ],
    "values": {
      "en": "episodes"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about episodes — An episode of a TV/radio series or season.",
    "uuid": "cbf70338-d28c-8939-94e2-5408300da01e",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "episodes",
      "an",
      "episode",
      "of",
      "a",
      "tv",
      "radio",
      "series",
      "or",
      "season"
    ],
    "values": {
      "en": "Use when reasoning about episodes — An episode of a TV/radio series or season."
    }
  }
]

export default translations
