// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "amortize",
    "uuid": "c08384fb-28f1-829e-8b6e-b276a175115c",
    "words": [
      "amortize"
    ],
    "values": {
      "en": "amortize"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about amortize — ports the bond discount/premium amortization calculators verbatim (calculate, port): **effective-interest** (or straight-line where permitted) amortization of a discount/premium ov",
    "uuid": "7a397371-abf4-87f1-ac2a-9f1146d92c8f",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "amortize",
      "ports",
      "the",
      "bond",
      "discount",
      "premium",
      "amortization",
      "calculators",
      "verbatim",
      "calculate",
      "port",
      "effective",
      "interest",
      "or",
      "straight",
      "line",
      "where",
      "permitted",
      "amortization",
      "of",
      "a",
      "discount",
      "premium",
      "ov"
    ],
    "values": {
      "en": "Use when reasoning about amortize — ports the bond discount/premium amortization calculators verbatim (calculate, port): **effective-interest** (or straight-line where permitted) amortization of a discount/premium ov"
    }
  }
]

export default translations
