// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "complexity",
    "uuid": "9c4ad768-db2f-8e94-aa99-df1421eb9bd9",
    "words": [
      "complexity"
    ],
    "values": {
      "en": "complexity"
    }
  },
  {
    "key": "description",
    "source": "Use when classifying algorithmic cost — big-O from loop-depth bindings under computer; executable not glossary.",
    "uuid": "d8c35813-42ff-8b71-8d4b-cc6bb0ee4a40",
    "words": [
      "use",
      "when",
      "classifying",
      "algorithmic",
      "cost",
      "big",
      "o",
      "from",
      "loop",
      "depth",
      "bindings",
      "under",
      "computer",
      "executable",
      "not",
      "glossary"
    ],
    "values": {
      "en": "Use when classifying algorithmic cost — big-O from loop-depth bindings under computer; executable not glossary."
    }
  }
]

export default translations
