// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "open",
    "uuid": "02e9b224-64b3-89aa-8eb1-2233cd719035",
    "words": [
      "open"
    ],
    "values": {
      "en": "open"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about the permitting boundary state in erpax — fiscal period open (postable), draft editable, session/stream open. The universal root of the open state; dual of close.",
    "uuid": "f700b47f-66c8-8454-be9e-ac27951997c6",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "the",
      "permitting",
      "boundary",
      "state",
      "in",
      "erpax",
      "fiscal",
      "period",
      "open",
      "postable",
      "draft",
      "editable",
      "session",
      "stream",
      "open",
      "the",
      "universal",
      "root",
      "of",
      "the",
      "open",
      "state",
      "dual",
      "of",
      "close"
    ],
    "values": {
      "en": "Use when reasoning about the permitting boundary state in erpax — fiscal period open (postable), draft editable, session/stream open. The universal root of the open state; dual of close."
    }
  }
]

export default translations
