// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "quaternary",
    "uuid": "eadc0f75-b0b0-8b0e-b4bb-2aa9e8520589",
    "words": [
      "quaternary"
    ],
    "values": {
      "en": "quaternary"
    }
  },
  {
    "key": "description",
    "source": "Use when enforcing the four-file folder law — an atom folder holds only SKILL.md, index.ts, test.ts, translations.ts; any other file is a violation to collide into its own atom.",
    "uuid": "3510c490-e1f0-8443-a350-dbda8b0198de",
    "words": [
      "use",
      "when",
      "enforcing",
      "the",
      "four",
      "file",
      "folder",
      "law",
      "an",
      "atom",
      "folder",
      "holds",
      "only",
      "skill",
      "md",
      "index",
      "ts",
      "test",
      "ts",
      "translations",
      "ts",
      "any",
      "other",
      "file",
      "is",
      "a",
      "violation",
      "to",
      "collide",
      "into",
      "its",
      "own",
      "atom"
    ],
    "values": {
      "en": "Use when enforcing the four-file folder law — an atom folder holds only SKILL.md, index.ts, test.ts, translations.ts; any other file is a violation to collide into its own atom."
    }
  }
]

export default translations
