// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "approved",
    "uuid": "110296f1-4e4d-8e07-8c46-f192ef87af2c",
    "words": [
      "approved"
    ],
    "values": {
      "en": "approved"
    }
  },
  {
    "key": "description",
    "source": "Use when tracking approval state or flag — approved flag on invoice (boolean), approved amount (in multi-step approval workflows), approved by (user reference), approved at (date). Workflow checkpoint status value.",
    "uuid": "7220621f-cd68-891a-926f-19b3a55a8318",
    "words": [
      "use",
      "when",
      "tracking",
      "approval",
      "state",
      "or",
      "flag",
      "approved",
      "flag",
      "on",
      "invoice",
      "boolean",
      "approved",
      "amount",
      "in",
      "multi",
      "step",
      "approval",
      "workflows",
      "approved",
      "by",
      "user",
      "reference",
      "approved",
      "at",
      "date",
      "workflow",
      "checkpoint",
      "status",
      "value"
    ],
    "values": {
      "en": "Use when tracking approval state or flag — approved flag on invoice (boolean), approved amount (in multi-step approval workflows), approved by (user reference), approved at (date). Workflow checkpoint status value."
    }
  }
]

export default translations
