// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "byline",
    "uuid": "8cb0e196-5559-8e1d-96b0-adfca7d60dff",
    "words": [
      "byline"
    ],
    "values": {
      "en": "byline"
    }
  },
  {
    "key": "description",
    "source": "Use when modelling one byline — the singular model of the bylines collection (the plural store); the credited author line on a published article.",
    "uuid": "80a16485-e1ae-8344-8593-665a85b24aa8",
    "words": [
      "use",
      "when",
      "modelling",
      "one",
      "byline",
      "the",
      "singular",
      "model",
      "of",
      "the",
      "bylines",
      "collection",
      "the",
      "plural",
      "store",
      "the",
      "credited",
      "author",
      "line",
      "on",
      "a",
      "published",
      "article"
    ],
    "values": {
      "en": "Use when modelling one byline — the singular model of the bylines collection (the plural store); the credited author line on a published article."
    }
  }
]

export default translations
