// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "grantee",
    "uuid": "7e41ac60-a872-8775-9e6f-c8a33608d6de",
    "words": [
      "grantee"
    ],
    "values": {
      "en": "grantee"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about grantee — The person, organization, contact point, or audience that has been granted this permission.",
    "uuid": "fcb265a6-66ac-8915-9339-f67e0a4f9815",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "grantee",
      "the",
      "person",
      "organization",
      "contact",
      "point",
      "or",
      "audience",
      "that",
      "has",
      "been",
      "granted",
      "this",
      "permission"
    ],
    "values": {
      "en": "Use when reasoning about grantee — The person, organization, contact point, or audience that has been granted this permission."
    }
  }
]

export default translations
