// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "action",
    "uuid": "287f6cd1-4ee7-8cd6-89df-bea630acc2f8",
    "words": [
      "action"
    ],
    "values": {
      "en": "action"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about action — An action performed by a direct agent and indirect participants upon a direct object. Optionally happens at a location with the help of an inanimate instrument. The execution of th",
    "uuid": "2b99d1ad-9caf-8880-9619-fb1d2930e276",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "action",
      "an",
      "action",
      "performed",
      "by",
      "a",
      "direct",
      "agent",
      "and",
      "indirect",
      "participants",
      "upon",
      "a",
      "direct",
      "object",
      "optionally",
      "happens",
      "at",
      "a",
      "location",
      "with",
      "the",
      "help",
      "of",
      "an",
      "inanimate",
      "instrument",
      "the",
      "execution",
      "of",
      "th"
    ],
    "values": {
      "en": "Use when reasoning about action — An action performed by a direct agent and indirect participants upon a direct object. Optionally happens at a location with the help of an inanimate instrument. The execution of th"
    }
  }
]

export default translations
