// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "boolean",
    "uuid": "aa694abc-3207-8bce-ac0b-ac0387fd1b60",
    "words": [
      "boolean"
    ],
    "values": {
      "en": "boolean"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about boolean — Boolean: True or False.",
    "uuid": "93b83182-11d2-8ca2-aad4-a19e65d9f0a1",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "boolean",
      "boolean",
      "true",
      "or",
      "false"
    ],
    "values": {
      "en": "Use when reasoning about boolean — Boolean: True or False."
    }
  }
]

export default translations
