// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "free",
    "uuid": "f0845803-efd7-8dcb-9af5-95c20a511889",
    "words": [
      "free"
    ],
    "values": {
      "en": "free"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about free — A flag to signal that the item, event, or place is accessible for free.",
    "uuid": "43a0c9eb-d53e-8ee3-a2ea-3eba43e7c127",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "free",
      "a",
      "flag",
      "to",
      "signal",
      "that",
      "the",
      "item",
      "event",
      "or",
      "place",
      "is",
      "accessible",
      "for",
      "free"
    ],
    "values": {
      "en": "Use when reasoning about free — A flag to signal that the item, event, or place is accessible for free."
    }
  }
]

export default translations
