// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "warning",
    "uuid": "353e6685-f069-8997-864a-6c79aa0def87",
    "words": [
      "warning"
    ],
    "values": {
      "en": "warning"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about warning — Any FDA or other warnings about the drug (text or URL).",
    "uuid": "afd1bba3-acd6-8066-9faf-e412b6b916ec",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "warning",
      "any",
      "fda",
      "or",
      "other",
      "warnings",
      "about",
      "the",
      "drug",
      "text",
      "or",
      "url"
    ],
    "values": {
      "en": "Use when reasoning about warning — Any FDA or other warnings about the drug (text or URL)."
    }
  }
]

export default translations
