// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "warning",
    "uuid": "b5ea1e9d-8876-8cc4-8a66-65069fc0c25d",
    "words": [
      "warning"
    ],
    "values": {
      "en": "warning"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about warning — Any FDA or other warnings about the drug (text or URL).",
    "uuid": "89fe0af9-9c3c-8675-8295-91927a211339",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "warning",
      "any",
      "fda",
      "or",
      "other",
      "warnings",
      "about",
      "the",
      "drug",
      "text",
      "or",
      "url"
    ],
    "values": {
      "en": "Use when reasoning about warning — Any FDA or other warnings about the drug (text or URL)."
    }
  }
]

export default translations
