// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "gravity",
    "uuid": "1df87b80-e496-8e32-bf9a-9525fc9a95c1",
    "words": [
      "gravity"
    ],
    "values": {
      "en": "gravity"
    }
  },
  {
    "key": "description",
    "source": "Use when relating an atom's gravitational mass to its quantum entanglement — quantum gravity, where the links are one measure that is both mass (referential in-degree, what curves the corpus) and entanglement; the gravity well is the singularity where the double-torus closes to infinite tamper cost (the event horizon).",
    "uuid": "4a1dc171-a5de-8c19-babb-a1d4cf0c1b56",
    "words": [
      "use",
      "when",
      "relating",
      "an",
      "atom",
      "s",
      "gravitational",
      "mass",
      "to",
      "its",
      "quantum",
      "entanglement",
      "quantum",
      "gravity",
      "where",
      "the",
      "links",
      "are",
      "one",
      "measure",
      "that",
      "is",
      "both",
      "mass",
      "referential",
      "in",
      "degree",
      "what",
      "curves",
      "the",
      "corpus",
      "and",
      "entanglement",
      "the",
      "gravity",
      "well",
      "is",
      "the",
      "singularity",
      "where",
      "the",
      "double",
      "torus",
      "closes",
      "to",
      "infinite",
      "tamper",
      "cost",
      "the",
      "event",
      "horizon"
    ],
    "values": {
      "en": "Use when relating an atom's gravitational mass to its quantum entanglement — quantum gravity, where the links are one measure that is both mass (referential in-degree, what curves the corpus) and entanglement; the gravity well is the singularity where the double-torus closes to infinite tamper cost (the event horizon)."
    }
  }
]

export default translations
