// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "acknowledgment",
    "uuid": "37e8de81-6930-8738-9a9e-5e8993893b74",
    "words": [
      "acknowledgment"
    ],
    "values": {
      "en": "acknowledgment"
    }
  },
  {
    "key": "description",
    "source": "Use when modelling one acknowledgment — the singular model of the acknowledgments collection (the plural store); a formal confirmation that something was received or accepted.",
    "uuid": "6ae7ae5e-ebb9-85c4-8804-7dbb6a74dc5e",
    "words": [
      "use",
      "when",
      "modelling",
      "one",
      "acknowledgment",
      "the",
      "singular",
      "model",
      "of",
      "the",
      "acknowledgments",
      "collection",
      "the",
      "plural",
      "store",
      "a",
      "formal",
      "confirmation",
      "that",
      "something",
      "was",
      "received",
      "or",
      "accepted"
    ],
    "values": {
      "en": "Use when modelling one acknowledgment — the singular model of the acknowledgments collection (the plural store); a formal confirmation that something was received or accepted."
    }
  }
]

export default translations
