// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "illustrator",
    "uuid": "f05edee9-6e66-87d1-b20d-09c42ad3d8d1",
    "words": [
      "illustrator"
    ],
    "values": {
      "en": "illustrator"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about illustrator — The illustrator of the book.",
    "uuid": "96ec37f3-e16a-83c8-8949-d0c0df78bec9",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "illustrator",
      "the",
      "illustrator",
      "of",
      "the",
      "book"
    ],
    "values": {
      "en": "Use when reasoning about illustrator — The illustrator of the book."
    }
  }
]

export default translations
