// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "type",
    "uuid": "9ac40052-6ef2-8a20-bf72-f660c6551ff7",
    "words": [
      "type"
    ],
    "values": {
      "en": "type"
    }
  },
  {
    "key": "description",
    "source": "Use when categorizing an entity into a taxonomic class — customer type (company/individual), transaction type (sale/purchase), account type (asset/liability/equity). A select field carrying domain-specific enums; often paired with status for state-machine workflows.",
    "uuid": "c0bae0e2-ea44-8ed4-b823-ca45f3566675",
    "words": [
      "use",
      "when",
      "categorizing",
      "an",
      "entity",
      "into",
      "a",
      "taxonomic",
      "class",
      "customer",
      "type",
      "company",
      "individual",
      "transaction",
      "type",
      "sale",
      "purchase",
      "account",
      "type",
      "asset",
      "liability",
      "equity",
      "a",
      "select",
      "field",
      "carrying",
      "domain",
      "specific",
      "enums",
      "often",
      "paired",
      "with",
      "status",
      "for",
      "state",
      "machine",
      "workflows"
    ],
    "values": {
      "en": "Use when categorizing an entity into a taxonomic class — customer type (company/individual), transaction type (sale/purchase), account type (asset/liability/equity). A select field carrying domain-specific enums; often paired with status for state-machine workflows."
    }
  }
]

export default translations
