// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "face",
    "uuid": "3db88496-8cd9-8dea-8adb-6b32757b01f0",
    "words": [
      "face"
    ],
    "values": {
      "en": "face"
    }
  },
  {
    "key": "description",
    "source": "Use when a refactor moves matter between atoms — a split may relocate anything, but an atom that stops offering a name breaks every caller silently. Snapshot corpusFace before, compare after; a LOST name fails closed, a gained one is free. Replayed against the commit that split four concentration hubs, it catches the drop that commit made.",
    "uuid": "bde2d0ed-97c9-8632-af8f-7f4e7a821005",
    "words": [
      "use",
      "when",
      "a",
      "refactor",
      "moves",
      "matter",
      "between",
      "atoms",
      "a",
      "split",
      "may",
      "relocate",
      "anything",
      "but",
      "an",
      "atom",
      "that",
      "stops",
      "offering",
      "a",
      "name",
      "breaks",
      "every",
      "caller",
      "silently",
      "snapshot",
      "corpusface",
      "before",
      "compare",
      "after",
      "a",
      "lost",
      "name",
      "fails",
      "closed",
      "a",
      "gained",
      "one",
      "is",
      "free",
      "replayed",
      "against",
      "the",
      "commit",
      "that",
      "split",
      "four",
      "concentration",
      "hubs",
      "it",
      "catches",
      "the",
      "drop",
      "that",
      "commit",
      "made"
    ],
    "values": {
      "en": "Use when a refactor moves matter between atoms — a split may relocate anything, but an atom that stops offering a name breaks every caller silently. Snapshot corpusFace before, compare after; a LOST name fails closed, a gained one is free. Replayed against the commit that split four concentration hubs, it catches the drop that commit made."
    }
  }
]

export default translations
