// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "wave",
    "uuid": "29349600-ca54-8d4b-a097-c83679180325",
    "words": [
      "wave"
    ],
    "values": {
      "en": "wave"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about wave — Continuous quantum computation wave with real-time Zenodo publication",
    "uuid": "36933c3e-8c65-88fe-80eb-359759ddd22b",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "wave",
      "continuous",
      "quantum",
      "computation",
      "wave",
      "with",
      "real",
      "time",
      "zenodo",
      "publication"
    ],
    "values": {
      "en": "Use when reasoning about wave — Continuous quantum computation wave with real-time Zenodo publication"
    }
  }
]

export default translations
