// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "wave",
    "uuid": "debefc5a-ef19-8e2e-8a75-3c7e9982c0a2",
    "words": [
      "wave"
    ],
    "values": {
      "en": "wave"
    }
  },
  {
    "key": "description",
    "source": "Use when describing a batch of features added in one development breath before they are collided — a wave rides the horo sequence, raising entropy first so the later collide can DRY it back to the dense core.",
    "uuid": "4634dced-322a-80a2-87aa-86f107c24251",
    "words": [
      "use",
      "when",
      "describing",
      "a",
      "batch",
      "of",
      "features",
      "added",
      "in",
      "one",
      "development",
      "breath",
      "before",
      "they",
      "are",
      "collided",
      "a",
      "wave",
      "rides",
      "the",
      "horo",
      "sequence",
      "raising",
      "entropy",
      "first",
      "so",
      "the",
      "later",
      "collide",
      "can",
      "dry",
      "it",
      "back",
      "to",
      "the",
      "dense",
      "core"
    ],
    "values": {
      "en": "Use when describing a batch of features added in one development breath before they are collided — a wave rides the horo sequence, raising entropy first so the later collide can DRY it back to the dense core."
    }
  }
]

export default translations
