// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "aspect",
    "uuid": "1499271a-c372-869c-8c63-1945b818aecd",
    "words": [
      "aspect"
    ],
    "values": {
      "en": "aspect"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about aspect — An aspect of medical practice that is considered on the page, such as 'diagnosis', 'treatment', 'causes', 'prognosis', 'etiology', 'epidemiology', etc.",
    "uuid": "2b2aa66c-4931-8a77-9ff8-ffcf812dc69d",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "aspect",
      "an",
      "aspect",
      "of",
      "medical",
      "practice",
      "that",
      "is",
      "considered",
      "on",
      "the",
      "page",
      "such",
      "as",
      "diagnosis",
      "treatment",
      "causes",
      "prognosis",
      "etiology",
      "epidemiology",
      "etc"
    ],
    "values": {
      "en": "Use when reasoning about aspect — An aspect of medical practice that is considered on the page, such as 'diagnosis', 'treatment', 'causes', 'prognosis', 'etiology', 'epidemiology', etc."
    }
  }
]

export default translations
