// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "four",
    "uuid": "a619c5b9-a4f7-8470-a2d6-643258d31a76",
    "words": [
      "four"
    ],
    "values": {
      "en": "four"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about four — Four Color Theorem via basis decomposition - geometry + graph theory",
    "uuid": "e405633a-a338-8400-b2b6-c7db60f434e8",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "four",
      "four",
      "color",
      "theorem",
      "via",
      "basis",
      "decomposition",
      "geometry",
      "graph",
      "theory"
    ],
    "values": {
      "en": "Use when reasoning about four — Four Color Theorem via basis decomposition - geometry + graph theory"
    }
  }
]

export default translations
