// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "face",
    "uuid": "a6bb6d7a-afe2-8f66-b80f-c873cdf44f28",
    "words": [
      "face"
    ],
    "values": {
      "en": "face"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about face — Every number in this session reached its reader as a sentence. *\\\"48 blind probes\\\"*, *\\\"1.6× slower cached\\\"*, *\\\"237 dead pointers\\\"* — each true when written, none checkable by the…",
    "uuid": "be015971-ccc2-89b2-8fbc-fc500ed460a0",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "face",
      "every",
      "number",
      "in",
      "this",
      "session",
      "reached",
      "its",
      "reader",
      "as",
      "a",
      "sentence",
      "blind",
      "probes",
      "slower",
      "cached",
      "dead",
      "pointers",
      "each",
      "true",
      "when",
      "written",
      "none",
      "checkable",
      "by",
      "the"
    ],
    "values": {
      "en": "Use when reasoning about face — Every number in this session reached its reader as a sentence. *\\\"48 blind probes\\\"*, *\\\"1.6× slower cached\\\"*, *\\\"237 dead pointers\\\"* — each true when written, none checkable by the…"
    }
  }
]

export default translations
