// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "graph",
    "uuid": "7c21383f-a606-8b6b-a455-3e9584239e54",
    "words": [
      "graph"
    ],
    "values": {
      "en": "graph"
    }
  },
  {
    "key": "description",
    "source": "Use when traversing corpus bonds as a directed graph — matrix adjacency under computer; executable not glossary.",
    "uuid": "e08978b6-f3dd-89f0-ad30-68d57c54b90b",
    "words": [
      "use",
      "when",
      "traversing",
      "corpus",
      "bonds",
      "as",
      "a",
      "directed",
      "graph",
      "matrix",
      "adjacency",
      "under",
      "computer",
      "executable",
      "not",
      "glossary"
    ],
    "values": {
      "en": "Use when traversing corpus bonds as a directed graph — matrix adjacency under computer; executable not glossary."
    }
  }
]

export default translations
