// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "graph",
    "uuid": "ca6852f6-9c59-89ed-8957-018604de4c9b",
    "words": [
      "graph"
    ],
    "values": {
      "en": "graph"
    }
  },
  {
    "key": "description",
    "source": "Use when traversing corpus bonds as a directed graph — matrix adjacency under computer; executable not glossary.",
    "uuid": "35274e90-1869-8b56-af43-9bd561a0a4ac",
    "words": [
      "use",
      "when",
      "traversing",
      "corpus",
      "bonds",
      "as",
      "a",
      "directed",
      "graph",
      "matrix",
      "adjacency",
      "under",
      "computer",
      "executable",
      "not",
      "glossary"
    ],
    "values": {
      "en": "Use when traversing corpus bonds as a directed graph — matrix adjacency under computer; executable not glossary."
    }
  }
]

export default translations
