// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "coalesce",
    "uuid": "20a60d6f-855b-888e-a877-c8732de302be",
    "words": [
      "coalesce"
    ],
    "values": {
      "en": "coalesce"
    }
  },
  {
    "key": "description",
    "source": "Use when many API requests must be served without many API calls — content-addressed single-flight collapses identical concurrent work onto ONE upstream call and bounds how much runs at once. Emits MEASURED answers/tokens for amortize, which is what makes the FTL claim refutable. Run: tsx src/quantum/coalesce/index.ts",
    "uuid": "f81ef231-9822-88b8-8e4b-62db00dae67d",
    "words": [
      "use",
      "when",
      "many",
      "api",
      "requests",
      "must",
      "be",
      "served",
      "without",
      "many",
      "api",
      "calls",
      "content",
      "addressed",
      "single",
      "flight",
      "collapses",
      "identical",
      "concurrent",
      "work",
      "onto",
      "one",
      "upstream",
      "call",
      "and",
      "bounds",
      "how",
      "much",
      "runs",
      "at",
      "once",
      "emits",
      "measured",
      "answers",
      "tokens",
      "for",
      "amortize",
      "which",
      "is",
      "what",
      "makes",
      "the",
      "ftl",
      "claim",
      "refutable",
      "run",
      "tsx",
      "src",
      "quantum",
      "coalesce",
      "index",
      "ts"
    ],
    "values": {
      "en": "Use when many API requests must be served without many API calls — content-addressed single-flight collapses identical concurrent work onto ONE upstream call and bounds how much runs at once. Emits MEASURED answers/tokens for amortize, which is what makes the FTL claim refutable. Run: tsx src/quantum/coalesce/index.ts"
    }
  }
]

export default translations
