// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "memo",
    "uuid": "3eb5223b-6779-8b78-bf38-93a8959f7627",
    "words": [
      "memo"
    ],
    "values": {
      "en": "memo"
    }
  },
  {
    "key": "description",
    "source": "Use when modelling one memo — the singular model of the memos collection (the plural store); a brief internal written note.",
    "uuid": "728256d8-1a60-8215-b248-7ba18b92a393",
    "words": [
      "use",
      "when",
      "modelling",
      "one",
      "memo",
      "the",
      "singular",
      "model",
      "of",
      "the",
      "memos",
      "collection",
      "the",
      "plural",
      "store",
      "a",
      "brief",
      "internal",
      "written",
      "note"
    ],
    "values": {
      "en": "Use when modelling one memo — the singular model of the memos collection (the plural store); a brief internal written note."
    }
  }
]

export default translations
