// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "midpoint",
    "uuid": "d5429e05-55d3-8ba5-a0b5-987fa1f91ba4",
    "words": [
      "midpoint"
    ],
    "values": {
      "en": "midpoint"
    }
  },
  {
    "key": "description",
    "source": "midpoint: a schema.org component word, fused from geoMidpoint",
    "uuid": "79b5b15d-292d-84d4-a86d-dceaa4894239",
    "words": [
      "midpoint",
      "a",
      "schema",
      "org",
      "component",
      "word",
      "fused",
      "from",
      "geomidpoint"
    ],
    "values": {
      "en": "midpoint: a schema.org component word, fused from geoMidpoint"
    }
  }
]

export default translations
