/** blocks — Payload block components + configs barrel. */
export { BannerBlock } from './banner/Component'
export { Banner } from './banner/config'
export { CodeBlock, type CodeBlockProps } from './code/Component'
export { Code } from './code/config'
export { ContentBlock } from './content/Component'
export { Content } from './content/config'
export { CallToActionBlock } from './call/to/action/Component'
export { CallToAction } from './call/to/action/config'
export { MediaBlock } from './media/block/Component'
export { MediaBlock as MediaBlockConfig } from './media/block/config'
export { ArchiveBlock } from './archive/block/Component'
export { Archive } from './archive/block/config'
export { FormBlock, type FormBlockType } from './form/Component'
export { FormBlock as FormBlockConfig } from './form/config'
export { RelatedPosts, type RelatedPostsProps } from './related/post/Component'
