// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "unofficial",
    "uuid": "81d79a71-90fd-8cb1-83e5-e842679846ff",
    "words": [
      "unofficial"
    ],
    "values": {
      "en": "unofficial"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about unofficial as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus.",
    "uuid": "39a057bf-cde2-8d0e-a39d-850541917744",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "unofficial",
      "as",
      "a",
      "schema",
      "org",
      "vocabulary",
      "word",
      "the",
      "single",
      "word",
      "collided",
      "from",
      "the",
      "schema",
      "org",
      "terms",
      "that",
      "contain",
      "it",
      "content",
      "addressed",
      "into",
      "the",
      "corpus"
    ],
    "values": {
      "en": "Use when reasoning about unofficial as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus."
    }
  }
]

export default translations
