// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "pi",
    "uuid": "524a45b2-3817-8696-845a-640d4e248e7c",
    "words": [
      "pi"
    ],
    "values": {
      "en": "pi"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about exiting the 128-bit uuid limit — pi is the infinite digit-stream, a universal address space where any data lives at an offset and length; the train you jump into and out of, when wired the static hash becomes a living realtime position. Honest — infinite address, no free compression.",
    "uuid": "e970d5da-c690-806e-a73d-63336db2ba0d",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "exiting",
      "the",
      "bit",
      "uuid",
      "limit",
      "pi",
      "is",
      "the",
      "infinite",
      "digit",
      "stream",
      "a",
      "universal",
      "address",
      "space",
      "where",
      "any",
      "data",
      "lives",
      "at",
      "an",
      "offset",
      "and",
      "length",
      "the",
      "train",
      "you",
      "jump",
      "into",
      "and",
      "out",
      "of",
      "when",
      "wired",
      "the",
      "static",
      "hash",
      "becomes",
      "a",
      "living",
      "realtime",
      "position",
      "honest",
      "infinite",
      "address",
      "no",
      "free",
      "compression"
    ],
    "values": {
      "en": "Use when reasoning about exiting the 128-bit uuid limit — pi is the infinite digit-stream, a universal address space where any data lives at an offset and length; the train you jump into and out of, when wired the static hash becomes a living realtime position. Honest — infinite address, no free compression."
    }
  }
]

export default translations
