// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "availability",
    "uuid": "d00b21f8-1c97-820c-839b-0d68df018c79",
    "words": [
      "availability"
    ],
    "values": {
      "en": "availability"
    }
  },
  {
    "key": "description",
    "source": "The availability of this item&#x2014;for example In stock, Out of stock, Pre-order, etc.",
    "uuid": "d64b2f96-fd35-8452-a79b-f93ccd1213ee",
    "words": [
      "the",
      "availability",
      "of",
      "this",
      "item",
      "x2014",
      "for",
      "example",
      "in",
      "stock",
      "out",
      "of",
      "stock",
      "pre",
      "order",
      "etc"
    ],
    "values": {
      "en": "The availability of this item&#x2014;for example In stock, Out of stock, Pre-order, etc."
    }
  }
]

export default translations
