// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "follows",
    "uuid": "ed9bf584-7a61-8de2-b802-25eaeeb1cb55",
    "words": [
      "follows"
    ],
    "values": {
      "en": "follows"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about follows — The most generic uni-directional social relation.",
    "uuid": "0ea3d793-9884-8629-8ae2-df443c886e1e",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "follows",
      "the",
      "most",
      "generic",
      "uni",
      "directional",
      "social",
      "relation"
    ],
    "values": {
      "en": "Use when reasoning about follows — The most generic uni-directional social relation."
    }
  }
]

export default translations
