// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "versions",
    "uuid": "1f9bc95f-325f-8a3c-abc8-4906da4aea44",
    "words": [
      "versions"
    ],
    "values": {
      "en": "versions"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about versions — turns on Payload's native for every collection except those named in , with bounding the history.",
    "uuid": "99554d3b-8bb9-8b5e-83eb-34f169557bd7",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "versions",
      "turns",
      "on",
      "payload",
      "s",
      "native",
      "for",
      "every",
      "collection",
      "except",
      "those",
      "named",
      "in",
      "with",
      "bounding",
      "the",
      "history"
    ],
    "values": {
      "en": "Use when reasoning about versions — turns on Payload's native for every collection except those named in , with bounding the history."
    }
  }
]

export default translations
