// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "water",
    "uuid": "c870aec3-25d5-859f-9017-4bcdab9a30a2",
    "words": [
      "water"
    ],
    "values": {
      "en": "water"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about water as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus.",
    "uuid": "22b7f689-76df-8706-825f-0d21d8c5e8f9",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "water",
      "as",
      "a",
      "schema",
      "org",
      "vocabulary",
      "word",
      "the",
      "single",
      "word",
      "collided",
      "from",
      "the",
      "schema",
      "org",
      "terms",
      "that",
      "contain",
      "it",
      "content",
      "addressed",
      "into",
      "the",
      "corpus"
    ],
    "values": {
      "en": "Use when reasoning about water as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus."
    }
  }
]

export default translations
