// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "properties",
    "uuid": "75cb2ed7-ff77-852f-8acd-5473e0c3172d",
    "words": [
      "properties"
    ],
    "values": {
      "en": "properties"
    }
  },
  {
    "key": "description",
    "source": "Use when recognising or remeasuring IAS 40 investment property — land or buildings held to earn rental income or capital appreciation — under the §30 fair-value or cost model election, with transfer-of-use triggers (§57–65) and IFRS 13 hierarchy classification. The IAS 40 investment-property register.",
    "uuid": "f01fa455-94e4-88b2-b73e-206b5d4be302",
    "words": [
      "use",
      "when",
      "recognising",
      "or",
      "remeasuring",
      "ias",
      "investment",
      "property",
      "land",
      "or",
      "buildings",
      "held",
      "to",
      "earn",
      "rental",
      "income",
      "or",
      "capital",
      "appreciation",
      "under",
      "the",
      "fair",
      "value",
      "or",
      "cost",
      "model",
      "election",
      "with",
      "transfer",
      "of",
      "use",
      "triggers",
      "and",
      "ifrs",
      "hierarchy",
      "classification",
      "the",
      "ias",
      "investment",
      "property",
      "register"
    ],
    "values": {
      "en": "Use when recognising or remeasuring IAS 40 investment property — land or buildings held to earn rental income or capital appreciation — under the §30 fair-value or cost model election, with transfer-of-use triggers (§57–65) and IFRS 13 hierarchy classification. The IAS 40 investment-property register."
    }
  }
]

export default translations
