// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "successor",
    "uuid": "c03d6853-0ef8-8a57-84d1-b4b65a285706",
    "words": [
      "successor"
    ],
    "values": {
      "en": "successor"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about successor — A pointer from a newer variant of a product to its previous, often discontinued predecessor.",
    "uuid": "680ac391-4ade-8f1c-a20a-cbdca9508ce9",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "successor",
      "a",
      "pointer",
      "from",
      "a",
      "newer",
      "variant",
      "of",
      "a",
      "product",
      "to",
      "its",
      "previous",
      "often",
      "discontinued",
      "predecessor"
    ],
    "values": {
      "en": "Use when reasoning about successor — A pointer from a newer variant of a product to its previous, often discontinued predecessor."
    }
  }
]

export default translations
