// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "cemetery",
    "uuid": "f4607aad-07ac-89d7-9089-3f79fc239cef",
    "words": [
      "cemetery"
    ],
    "values": {
      "en": "cemetery"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about cemetery — A graveyard.",
    "uuid": "b4fc08b8-fce9-8027-a63d-936a62182d18",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "cemetery",
      "a",
      "graveyard"
    ],
    "values": {
      "en": "Use when reasoning about cemetery — A graveyard."
    }
  }
]

export default translations
