// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "debit",
    "uuid": "75bcae2e-d5df-8a05-9695-571042f57a9b",
    "words": [
      "debit"
    ],
    "values": {
      "en": "debit"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about accounting/debit — debit/credit logic — double-entry validation and journal lines.",
    "uuid": "1583f38f-9c2e-8c35-ba0a-7ebce8a7e36a",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "accounting",
      "debit",
      "debit",
      "credit",
      "logic",
      "double",
      "entry",
      "validation",
      "and",
      "journal",
      "lines"
    ],
    "values": {
      "en": "Use when reasoning about accounting/debit — debit/credit logic — double-entry validation and journal lines."
    }
  }
]

export default translations
