// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "period",
    "uuid": "8e6d8ec8-3417-8251-be1a-acec38b43b69",
    "words": [
      "period"
    ],
    "values": {
      "en": "period"
    }
  },
  {
    "key": "description",
    "source": "Use when implementing or referencing Fiscal Period Standard.",
    "uuid": "72da13a6-e627-8f34-9ebf-f21d9e5b087a",
    "words": [
      "use",
      "when",
      "implementing",
      "or",
      "referencing",
      "fiscal",
      "period",
      "standard"
    ],
    "values": {
      "en": "Use when implementing or referencing Fiscal Period Standard."
    }
  }
]

export default translations
