// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "period",
    "uuid": "14598080-8b72-8095-b8e3-4f6a3756add9",
    "words": [
      "period"
    ],
    "values": {
      "en": "period"
    }
  },
  {
    "key": "description",
    "source": "Use when implementing or referencing Fiscal Period Standard.",
    "uuid": "380f0e2f-1651-8a14-8a61-b4f468f85c18",
    "words": [
      "use",
      "when",
      "implementing",
      "or",
      "referencing",
      "fiscal",
      "period",
      "standard"
    ],
    "values": {
      "en": "Use when implementing or referencing Fiscal Period Standard."
    }
  }
]

export default translations
