// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "country",
    "uuid": "3c9c75de-1ed9-8155-a95f-dc4cd511940f",
    "words": [
      "country"
    ],
    "values": {
      "en": "country"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about country — holds a canonical bundle per country and returns the one for an alpha-2 code: its holidays, its VAT treatment, its bank-statement and invoice formats, its signing profile.",
    "uuid": "ff4c848f-a03d-8359-bc8e-df387896ca1a",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "country",
      "holds",
      "a",
      "canonical",
      "bundle",
      "per",
      "country",
      "and",
      "returns",
      "the",
      "one",
      "for",
      "an",
      "alpha",
      "code",
      "its",
      "holidays",
      "its",
      "vat",
      "treatment",
      "its",
      "bank",
      "statement",
      "and",
      "invoice",
      "formats",
      "its",
      "signing",
      "profile"
    ],
    "values": {
      "en": "Use when reasoning about country — holds a canonical bundle per country and returns the one for an alpha-2 code: its holidays, its VAT treatment, its bank-statement and invoice formats, its signing profile."
    }
  }
]

export default translations
