// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "notary",
    "uuid": "8fd50e34-5ede-8b43-87b7-6ce6c9e16628",
    "words": [
      "notary"
    ],
    "values": {
      "en": "notary"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about notary — A notary.",
    "uuid": "6cef2a54-926a-85b9-8495-ae9008d2c3b3",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "notary",
      "a",
      "notary"
    ],
    "values": {
      "en": "Use when reasoning about notary — A notary."
    }
  }
]

export default translations
