// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "scholarly",
    "uuid": "2a661d78-1490-83cc-96e0-b78a5dd22d13",
    "words": [
      "scholarly"
    ],
    "values": {
      "en": "scholarly"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about scholarly as a medical facet of medical — vocabulary pivot to @/scholarly; nested not duplicated.",
    "uuid": "95d5338b-1bcb-89bd-976d-aac0f3a1ac0b",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "scholarly",
      "as",
      "a",
      "medical",
      "facet",
      "of",
      "medical",
      "vocabulary",
      "pivot",
      "to",
      "scholarly",
      "nested",
      "not",
      "duplicated"
    ],
    "values": {
      "en": "Use when reasoning about scholarly as a medical facet of medical — vocabulary pivot to @/scholarly; nested not duplicated."
    }
  }
]

export default translations
