// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "deferral",
    "uuid": "cc5f1d75-260d-812b-bfd7-41847d6b52b9",
    "words": [
      "deferral"
    ],
    "values": {
      "en": "deferral"
    }
  },
  {
    "key": "description",
    "source": "Use when deferring the recognition of revenue or expense to future periods pending contract performance, delivery, or time passage — the dual of accrual and core to IFRS-15 revenue recognition",
    "uuid": "0fe4dc48-09ff-8623-8120-b340f4daca2e",
    "words": [
      "use",
      "when",
      "deferring",
      "the",
      "recognition",
      "of",
      "revenue",
      "or",
      "expense",
      "to",
      "future",
      "periods",
      "pending",
      "contract",
      "performance",
      "delivery",
      "or",
      "time",
      "passage",
      "the",
      "dual",
      "of",
      "accrual",
      "and",
      "core",
      "to",
      "ifrs",
      "revenue",
      "recognition"
    ],
    "values": {
      "en": "Use when deferring the recognition of revenue or expense to future periods pending contract performance, delivery, or time passage — the dual of accrual and core to IFRS-15 revenue recognition"
    }
  }
]

export default translations
