// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "festival",
    "uuid": "96d28c5b-3621-860a-851e-f0276c1b629b",
    "words": [
      "festival"
    ],
    "values": {
      "en": "festival"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about festival — Event type: Festival.",
    "uuid": "8fb71e1e-1468-8785-b9fd-c96f4d718f6f",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "festival",
      "event",
      "type",
      "festival"
    ],
    "values": {
      "en": "Use when reasoning about festival — Event type: Festival."
    }
  }
]

export default translations
