// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "bic",
    "uuid": "ecfdcd45-f52f-84e1-b327-268b4c88617a",
    "words": [
      "bic"
    ],
    "values": {
      "en": "bic"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about bic — ISO 9362 BIC / SWIFT validator.",
    "uuid": "69e8888c-9d01-8001-bfa9-9b99b999c06d",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "bic",
      "iso",
      "bic",
      "swift",
      "validator"
    ],
    "values": {
      "en": "Use when reasoning about bic — ISO 9362 BIC / SWIFT validator."
    }
  }
]

export default translations
