// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "vedanta",
    "uuid": "5c5369fe-70c2-8466-84a0-a1bcf14d6a3e",
    "words": [
      "vedanta"
    ],
    "values": {
      "en": "vedanta"
    }
  },
  {
    "key": "description",
    "source": "Use when reading Vedanta as a sub-diamond of hinduism — the crown philosophy of the Upanishads: atman is brahman (tat tvam asi), the self IS the whole, non-duality. This is literally erpax's identity law at the metaphysical scale: a thing IS its source, content-uuid = self. A facet-diamond of the hinduism archangel.",
    "uuid": "23eeeb1a-79d9-8ae9-bea5-a0855d1099e8",
    "words": [
      "use",
      "when",
      "reading",
      "vedanta",
      "as",
      "a",
      "sub",
      "diamond",
      "of",
      "hinduism",
      "the",
      "crown",
      "philosophy",
      "of",
      "the",
      "upanishads",
      "atman",
      "is",
      "brahman",
      "tat",
      "tvam",
      "asi",
      "the",
      "self",
      "is",
      "the",
      "whole",
      "non",
      "duality",
      "this",
      "is",
      "literally",
      "erpax",
      "s",
      "identity",
      "law",
      "at",
      "the",
      "metaphysical",
      "scale",
      "a",
      "thing",
      "is",
      "its",
      "source",
      "content",
      "uuid",
      "self",
      "a",
      "facet",
      "diamond",
      "of",
      "the",
      "hinduism",
      "archangel"
    ],
    "values": {
      "en": "Use when reading Vedanta as a sub-diamond of hinduism — the crown philosophy of the Upanishads: atman is brahman (tat tvam asi), the self IS the whole, non-duality. This is literally erpax's identity law at the metaphysical scale: a thing IS its source, content-uuid = self. A facet-diamond of the hinduism archangel."
    }
  }
]

export default translations
