// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "reservoir",
    "uuid": "7c4336b1-0efc-88ef-b1ae-66165c2c1a48",
    "words": [
      "reservoir"
    ],
    "values": {
      "en": "reservoir"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about reservoir — A reservoir of water, typically an artificially created lake, like the Lake Kariba reservoir.",
    "uuid": "cb572b2b-0d66-8320-bf76-78d6cc127833",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "reservoir",
      "a",
      "reservoir",
      "of",
      "water",
      "typically",
      "an",
      "artificially",
      "created",
      "lake",
      "like",
      "the",
      "lake",
      "kariba",
      "reservoir"
    ],
    "values": {
      "en": "Use when reasoning about reservoir — A reservoir of water, typically an artificially created lake, like the Lake Kariba reservoir."
    }
  }
]

export default translations
