// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "law",
    "uuid": "85d40661-750b-8e8f-b012-c28e2381b6bd",
    "words": [
      "law"
    ],
    "values": {
      "en": "law"
    }
  },
  {
    "key": "description",
    "source": "Use when checking that an atom is grounded — law is the suffix, the invariant each SKILL.md must close with; this quantum twin scans the quantum atoms and finds the lawless ones (state without invariant), the way recycle finds orphans.",
    "uuid": "9af134a5-80de-8b23-b8b7-aa3ef8746a11",
    "words": [
      "use",
      "when",
      "checking",
      "that",
      "an",
      "atom",
      "is",
      "grounded",
      "law",
      "is",
      "the",
      "suffix",
      "the",
      "invariant",
      "each",
      "skill",
      "md",
      "must",
      "close",
      "with",
      "this",
      "quantum",
      "twin",
      "scans",
      "the",
      "quantum",
      "atoms",
      "and",
      "finds",
      "the",
      "lawless",
      "ones",
      "state",
      "without",
      "invariant",
      "the",
      "way",
      "recycle",
      "finds",
      "orphans"
    ],
    "values": {
      "en": "Use when checking that an atom is grounded — law is the suffix, the invariant each SKILL.md must close with; this quantum twin scans the quantum atoms and finds the lawless ones (state without invariant), the way recycle finds orphans."
    }
  }
]

export default translations
