// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "collection",
    "uuid": "70c0d8a5-1db9-8d74-94bd-4fc580a1fa63",
    "words": [
      "collection"
    ],
    "values": {
      "en": "collection"
    }
  },
  {
    "key": "description",
    "source": "A collection of items, e.g. creative works or products.",
    "uuid": "563b3014-343a-8079-9896-5326fc58c09e",
    "words": [
      "a",
      "collection",
      "of",
      "items",
      "e",
      "g",
      "creative",
      "works",
      "or",
      "products"
    ],
    "values": {
      "en": "A collection of items, e.g. creative works or products."
    }
  }
]

export default translations
