// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "design",
    "uuid": "c15d108a-dcb6-8b0c-914a-a9f0542ef327",
    "words": [
      "design"
    ],
    "values": {
      "en": "design"
    }
  },
  {
    "key": "description",
    "source": "Use when defining the visual and interaction form of an experience — wireframes, prototypes, design reviews, design systems, accessibility, user research insights applied to form.",
    "uuid": "76bdbd77-4016-87f0-97de-f972e81ec361",
    "words": [
      "use",
      "when",
      "defining",
      "the",
      "visual",
      "and",
      "interaction",
      "form",
      "of",
      "an",
      "experience",
      "wireframes",
      "prototypes",
      "design",
      "reviews",
      "design",
      "systems",
      "accessibility",
      "user",
      "research",
      "insights",
      "applied",
      "to",
      "form"
    ],
    "values": {
      "en": "Use when defining the visual and interaction form of an experience — wireframes, prototypes, design reviews, design systems, accessibility, user research insights applied to form."
    }
  }
]

export default translations
