// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "mycelium",
    "uuid": "f9ac36fc-24a5-829a-bc59-36da3a100121",
    "words": [
      "mycelium"
    ],
    "values": {
      "en": "mycelium"
    }
  },
  {
    "key": "description",
    "source": "Use when modelling a living network with NO center — mycelium is the fungal body as a self-organizing web of hyphae that explores, connects, and transports nutrients with no brain and no coordinator; the literal decentralization and the substrate of the mycorrhizal trade. Nature's proof of the wired whole — but the 'wood wide web' is real as a network while its 'mother tree' resource-sharing is contested.",
    "uuid": "9440935c-17d1-889e-b993-446d3fd782d5",
    "words": [
      "use",
      "when",
      "modelling",
      "a",
      "living",
      "network",
      "with",
      "no",
      "center",
      "mycelium",
      "is",
      "the",
      "fungal",
      "body",
      "as",
      "a",
      "self",
      "organizing",
      "web",
      "of",
      "hyphae",
      "that",
      "explores",
      "connects",
      "and",
      "transports",
      "nutrients",
      "with",
      "no",
      "brain",
      "and",
      "no",
      "coordinator",
      "the",
      "literal",
      "decentralization",
      "and",
      "the",
      "substrate",
      "of",
      "the",
      "mycorrhizal",
      "trade",
      "nature",
      "s",
      "proof",
      "of",
      "the",
      "wired",
      "whole",
      "but",
      "the",
      "wood",
      "wide",
      "web",
      "is",
      "real",
      "as",
      "a",
      "network",
      "while",
      "its",
      "mother",
      "tree",
      "resource",
      "sharing",
      "is",
      "contested"
    ],
    "values": {
      "en": "Use when modelling a living network with NO center — mycelium is the fungal body as a self-organizing web of hyphae that explores, connects, and transports nutrients with no brain and no coordinator; the literal decentralization and the substrate of the mycorrhizal trade. Nature's proof of the wired whole — but the 'wood wide web' is real as a network while its 'mother tree' resource-sharing is contested."
    }
  }
]

export default translations
