// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "requirements",
    "uuid": "3366f21c-8b4d-8e22-a61b-05a96cc46cf9",
    "words": [
      "requirements"
    ],
    "values": {
      "en": "requirements"
    }
  },
  {
    "key": "description",
    "source": "Use when defining or querying individual control obligations within a compliance framework — code, title, description, section, severity (critical/high/medium/low) — linked to a ComplianceFramework; super-admin-only writes, tenant-read. The per-requirement obligation register that ComplianceGaps reference.",
    "uuid": "07308b99-9f66-85b5-a85c-b4e3c23962ef",
    "words": [
      "use",
      "when",
      "defining",
      "or",
      "querying",
      "individual",
      "control",
      "obligations",
      "within",
      "a",
      "compliance",
      "framework",
      "code",
      "title",
      "description",
      "section",
      "severity",
      "critical",
      "high",
      "medium",
      "low",
      "linked",
      "to",
      "a",
      "complianceframework",
      "super",
      "admin",
      "only",
      "writes",
      "tenant",
      "read",
      "the",
      "per",
      "requirement",
      "obligation",
      "register",
      "that",
      "compliancegaps",
      "reference"
    ],
    "values": {
      "en": "Use when defining or querying individual control obligations within a compliance framework — code, title, description, section, severity (critical/high/medium/low) — linked to a ComplianceFramework; super-admin-only writes, tenant-read. The per-requirement obligation register that ComplianceGaps reference."
    }
  }
]

export default translations
