// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "biomass",
    "uuid": "68a073fa-acd8-832b-9828-473ab02c14b2",
    "words": [
      "biomass"
    ],
    "values": {
      "en": "biomass"
    }
  },
  {
    "key": "description",
    "source": "Use when a living stock is valued by its total mass, not per-individual — standing biomass (kg) is the IAS-41 fair-value unit for an aquaculture stock, a forest stand, or a bee colony's strength: mass × forward price − costs-to-sell. Its growth rate is biological transformation. The non-individuated living-asset measure, shared across aquaculture/forestry/apiculture.",
    "uuid": "0d99b114-44d2-88cd-bd7e-88c19e2ccf20",
    "words": [
      "use",
      "when",
      "a",
      "living",
      "stock",
      "is",
      "valued",
      "by",
      "its",
      "total",
      "mass",
      "not",
      "per",
      "individual",
      "standing",
      "biomass",
      "kg",
      "is",
      "the",
      "ias",
      "fair",
      "value",
      "unit",
      "for",
      "an",
      "aquaculture",
      "stock",
      "a",
      "forest",
      "stand",
      "or",
      "a",
      "bee",
      "colony",
      "s",
      "strength",
      "mass",
      "forward",
      "price",
      "costs",
      "to",
      "sell",
      "its",
      "growth",
      "rate",
      "is",
      "biological",
      "transformation",
      "the",
      "non",
      "individuated",
      "living",
      "asset",
      "measure",
      "shared",
      "across",
      "aquaculture",
      "forestry",
      "apiculture"
    ],
    "values": {
      "en": "Use when a living stock is valued by its total mass, not per-individual — standing biomass (kg) is the IAS-41 fair-value unit for an aquaculture stock, a forest stand, or a bee colony's strength: mass × forward price − costs-to-sell. Its growth rate is biological transformation. The non-individuated living-asset measure, shared across aquaculture/forestry/apiculture."
    }
  }
]

export default translations
