// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "propagation",
    "uuid": "4478c9d9-6ef5-8da5-9580-965c3c104e53",
    "words": [
      "propagation"
    ],
    "values": {
      "en": "propagation"
    }
  },
  {
    "key": "description",
    "source": "Use when raising transplants before the field — the greenhouse/nursery schedule of sowing into trays of cells (plugs) sized to deliver seedlings on their field date, plus hardening-off before transplant. The controlled-start stage upstream of transplanting; flats/cells/plugs are its containers, sized back from the transplant date.",
    "uuid": "57781e69-6f32-8fed-b518-162e97d2c371",
    "words": [
      "use",
      "when",
      "raising",
      "transplants",
      "before",
      "the",
      "field",
      "the",
      "greenhouse",
      "nursery",
      "schedule",
      "of",
      "sowing",
      "into",
      "trays",
      "of",
      "cells",
      "plugs",
      "sized",
      "to",
      "deliver",
      "seedlings",
      "on",
      "their",
      "field",
      "date",
      "plus",
      "hardening",
      "off",
      "before",
      "transplant",
      "the",
      "controlled",
      "start",
      "stage",
      "upstream",
      "of",
      "transplanting",
      "flats",
      "cells",
      "plugs",
      "are",
      "its",
      "containers",
      "sized",
      "back",
      "from",
      "the",
      "transplant",
      "date"
    ],
    "values": {
      "en": "Use when raising transplants before the field — the greenhouse/nursery schedule of sowing into trays of cells (plugs) sized to deliver seedlings on their field date, plus hardening-off before transplant. The controlled-start stage upstream of transplanting; flats/cells/plugs are its containers, sized back from the transplant date."
    }
  }
]

export default translations
