// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "dimension",
    "uuid": "33ef6aef-2251-8909-ad73-b5a50ae064bb",
    "words": [
      "dimension"
    ],
    "values": {
      "en": "dimension"
    }
  },
  {
    "key": "description",
    "source": "Use when projecting the corpus across its quantum dimensions — the dimension identities, plugin surface and coverage results the realtime child streams from. Promoted from a loose sibling; the hyphenated realtime half nests as a child atom rather than a second root file. Run: tsx src/quantum/dimension/index.ts",
    "uuid": "de6a5f58-773b-89b9-999a-8d2deb29e66c",
    "words": [
      "use",
      "when",
      "projecting",
      "the",
      "corpus",
      "across",
      "its",
      "quantum",
      "dimensions",
      "the",
      "dimension",
      "identities",
      "plugin",
      "surface",
      "and",
      "coverage",
      "results",
      "the",
      "realtime",
      "child",
      "streams",
      "from",
      "promoted",
      "from",
      "a",
      "loose",
      "sibling",
      "the",
      "hyphenated",
      "realtime",
      "half",
      "nests",
      "as",
      "a",
      "child",
      "atom",
      "rather",
      "than",
      "a",
      "second",
      "root",
      "file",
      "run",
      "tsx",
      "src",
      "quantum",
      "dimension",
      "index",
      "ts"
    ],
    "values": {
      "en": "Use when projecting the corpus across its quantum dimensions — the dimension identities, plugin surface and coverage results the realtime child streams from. Promoted from a loose sibling; the hyphenated realtime half nests as a child atom rather than a second root file. Run: tsx src/quantum/dimension/index.ts"
    }
  }
]

export default translations
