// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "assesses",
    "uuid": "47db403b-d7f5-8369-a102-5dfc782f2527",
    "words": [
      "assesses"
    ],
    "values": {
      "en": "assesses"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about assesses — The item being described is intended to assess the competency or learning outcome defined by the referenced term.",
    "uuid": "26ddd59f-9af7-8a32-9ca6-0808360404cd",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "assesses",
      "the",
      "item",
      "being",
      "described",
      "is",
      "intended",
      "to",
      "assess",
      "the",
      "competency",
      "or",
      "learning",
      "outcome",
      "defined",
      "by",
      "the",
      "referenced",
      "term"
    ],
    "values": {
      "en": "Use when reasoning about assesses — The item being described is intended to assess the competency or learning outcome defined by the referenced term."
    }
  }
]

export default translations
