// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "integration",
    "uuid": "d03b227a-284c-89ec-9c53-41516b9a762f",
    "words": [
      "integration"
    ],
    "values": {
      "en": "integration"
    }
  },
  {
    "key": "description",
    "source": "Use when implementing or referencing Phase B5: Tax Period Integration — Standards & Implementation.",
    "uuid": "8ff07fb3-93fc-82af-816c-1ca31b9e72cd",
    "words": [
      "use",
      "when",
      "implementing",
      "or",
      "referencing",
      "phase",
      "b5",
      "tax",
      "period",
      "integration",
      "standards",
      "implementation"
    ],
    "values": {
      "en": "Use when implementing or referencing Phase B5: Tax Period Integration — Standards & Implementation."
    }
  }
]

export default translations
