// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "impact",
    "uuid": "25249390-e8b5-8f24-96e0-235f0a6eec87",
    "words": [
      "impact"
    ],
    "values": {
      "en": "impact"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about impact — The mid-weight hero: rich text, an optional set of links, and an optional image below.",
    "uuid": "ab60d6cc-8ba8-8d6c-9110-9493077c46cf",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "impact",
      "the",
      "mid",
      "weight",
      "hero",
      "rich",
      "text",
      "an",
      "optional",
      "set",
      "of",
      "links",
      "and",
      "an",
      "optional",
      "image",
      "below"
    ],
    "values": {
      "en": "Use when reasoning about impact — The mid-weight hero: rich text, an optional set of links, and an optional image below."
    }
  }
]

export default translations
