// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "remediation-plans",
    "uuid": "3d757aaf-0536-88ba-bb46-3bfe27946519",
    "words": [
      "remediation",
      "plans"
    ],
    "values": {
      "en": "remediation-plans"
    }
  },
  {
    "key": "description",
    "source": "Use when planning or tracking remediation of an audit finding or compliance gap — design/process/system/training/policy action steps with owner, target date, priority, budget, risk-of-delay, approval chain; COSO-2013 deficiency-remediation and SOX §404 control lifecycle. The remediation-plans improvement collection.",
    "uuid": "10e97ac2-de18-8490-a742-1fc407b978d7",
    "words": [
      "use",
      "when",
      "planning",
      "or",
      "tracking",
      "remediation",
      "of",
      "an",
      "audit",
      "finding",
      "or",
      "compliance",
      "gap",
      "design",
      "process",
      "system",
      "training",
      "policy",
      "action",
      "steps",
      "with",
      "owner",
      "target",
      "date",
      "priority",
      "budget",
      "risk",
      "of",
      "delay",
      "approval",
      "chain",
      "coso",
      "deficiency",
      "remediation",
      "and",
      "sox",
      "control",
      "lifecycle",
      "the",
      "remediation",
      "plans",
      "improvement",
      "collection"
    ],
    "values": {
      "en": "Use when planning or tracking remediation of an audit finding or compliance gap — design/process/system/training/policy action steps with owner, target date, priority, budget, risk-of-delay, approval chain; COSO-2013 deficiency-remediation and SOX §404 control lifecycle. The remediation-plans improvement collection."
    }
  }
]

export default translations
