// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "patent",
    "uuid": "433048b3-2722-81d0-a70b-044bccbe3796",
    "words": [
      "patent"
    ],
    "values": {
      "en": "patent"
    }
  },
  {
    "key": "description",
    "source": "Use when challenging an over-broad or illegally granted patent — encode the claim as a content-digest and test it on three computable grounds (prior art via anchored anteriority, obviousness via merge identity, abstract-math via §101); defensive only, not legal advice.",
    "uuid": "a4e3e6e4-4e7d-8e72-af0f-9dff778c9f72",
    "words": [
      "use",
      "when",
      "challenging",
      "an",
      "over",
      "broad",
      "or",
      "illegally",
      "granted",
      "patent",
      "encode",
      "the",
      "claim",
      "as",
      "a",
      "content",
      "digest",
      "and",
      "test",
      "it",
      "on",
      "three",
      "computable",
      "grounds",
      "prior",
      "art",
      "via",
      "anchored",
      "anteriority",
      "obviousness",
      "via",
      "merge",
      "identity",
      "abstract",
      "math",
      "via",
      "defensive",
      "only",
      "not",
      "legal",
      "advice"
    ],
    "values": {
      "en": "Use when challenging an over-broad or illegally granted patent — encode the claim as a content-digest and test it on three computable grounds (prior art via anchored anteriority, obviousness via merge identity, abstract-math via §101); defensive only, not legal advice."
    }
  }
]

export default translations
