// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "pharmacology",
    "uuid": "61a559dd-47a4-8351-b5e2-338ac0c6d43d",
    "words": [
      "pharmacology"
    ],
    "values": {
      "en": "pharmacology"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about pharmacology as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus.",
    "uuid": "0013c463-61b5-8044-9c2e-d831b154a02c",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "pharmacology",
      "as",
      "a",
      "schema",
      "org",
      "vocabulary",
      "word",
      "the",
      "single",
      "word",
      "collided",
      "from",
      "the",
      "schema",
      "org",
      "terms",
      "that",
      "contain",
      "it",
      "content",
      "addressed",
      "into",
      "the",
      "corpus"
    ],
    "values": {
      "en": "Use when reasoning about pharmacology as a schema.org vocabulary word — the single word collided from the schema.org terms that contain it, content-addressed into the corpus."
    }
  }
]

export default translations
