// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "reality",
    "uuid": "1368d01b-f608-814c-b7c1-e59bfdbadeae",
    "words": [
      "reality"
    ],
    "values": {
      "en": "reality"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about the live shipped state versus the model — reality is what is actually on main / deployed; the live matrix root is its fingerprint, and a claim is real iff it matches that root.",
    "uuid": "79bab8e4-930f-8298-ae37-eb55145797c3",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "the",
      "live",
      "shipped",
      "state",
      "versus",
      "the",
      "model",
      "reality",
      "is",
      "what",
      "is",
      "actually",
      "on",
      "main",
      "deployed",
      "the",
      "live",
      "matrix",
      "root",
      "is",
      "its",
      "fingerprint",
      "and",
      "a",
      "claim",
      "is",
      "real",
      "iff",
      "it",
      "matches",
      "that",
      "root"
    ],
    "values": {
      "en": "Use when reasoning about the live shipped state versus the model — reality is what is actually on main / deployed; the live matrix root is its fingerprint, and a claim is real iff it matches that root."
    }
  }
]

export default translations
