// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "foot",
    "uuid": "dc007572-d2ab-8cf6-97ef-c0115ac32b2f",
    "words": [
      "foot"
    ],
    "values": {
      "en": "foot"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about foot as an anatomical part of body — vocabulary pivot to @/foot; nested not duplicated.",
    "uuid": "8027d30d-add1-8af1-a0d7-f16a484cc465",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "foot",
      "as",
      "an",
      "anatomical",
      "part",
      "of",
      "body",
      "vocabulary",
      "pivot",
      "to",
      "foot",
      "nested",
      "not",
      "duplicated"
    ],
    "values": {
      "en": "Use when reasoning about foot as an anatomical part of body — vocabulary pivot to @/foot; nested not duplicated."
    }
  }
]

export default translations
