// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "fund",
    "uuid": "addc7892-3152-81d4-8447-0d4d5d199256",
    "words": [
      "fund"
    ],
    "values": {
      "en": "fund"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about fund — erpax booked government grants correctly under IAS 20 — 31 fields, clawback provisions, the funded asset, the granting authority.",
    "uuid": "4b18743e-3c86-8dde-9f50-3eaae4a46c08",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "fund",
      "erpax",
      "booked",
      "government",
      "grants",
      "correctly",
      "under",
      "ias",
      "fields",
      "clawback",
      "provisions",
      "the",
      "funded",
      "asset",
      "the",
      "granting",
      "authority"
    ],
    "values": {
      "en": "Use when reasoning about fund — erpax booked government grants correctly under IAS 20 — 31 fields, clawback provisions, the funded asset, the granting authority."
    }
  }
]

export default translations
