// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "contact",
    "uuid": "67bde4a3-5da5-82f7-a200-148b6052497a",
    "words": [
      "contact"
    ],
    "values": {
      "en": "contact"
    }
  },
  {
    "key": "description",
    "source": "Use for the contact seed pair — the form definition and the page that renders it, seeded together because a page without its form is a dead route.",
    "uuid": "9dc57194-a164-8b2d-941b-40134a1044d5",
    "words": [
      "use",
      "for",
      "the",
      "contact",
      "seed",
      "pair",
      "the",
      "form",
      "definition",
      "and",
      "the",
      "page",
      "that",
      "renders",
      "it",
      "seeded",
      "together",
      "because",
      "a",
      "page",
      "without",
      "its",
      "form",
      "is",
      "a",
      "dead",
      "route"
    ],
    "values": {
      "en": "Use for the contact seed pair — the form definition and the page that renders it, seeded together because a page without its form is a dead route."
    }
  }
]

export default translations
