// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "scheme",
    "uuid": "93684288-07a3-880f-8794-d3416eec52d6",
    "words": [
      "scheme"
    ],
    "values": {
      "en": "scheme"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about scheme — A schema.org component word, collided out of schema.org compounds — fused from FundingScheme (sti · collapse · merge).",
    "uuid": "c7bc6f0f-7c31-8c90-bc73-8cff438facd6",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "scheme",
      "a",
      "schema",
      "org",
      "component",
      "word",
      "collided",
      "out",
      "of",
      "schema",
      "org",
      "compounds",
      "fused",
      "from",
      "fundingscheme",
      "sti",
      "collapse",
      "merge"
    ],
    "values": {
      "en": "Use when reasoning about scheme — A schema.org component word, collided out of schema.org compounds — fused from FundingScheme (sti · collapse · merge)."
    }
  }
]

export default translations
