// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "triggered",
    "uuid": "a6d889df-8090-81db-9691-219b8bf8d4ce",
    "words": [
      "triggered"
    ],
    "values": {
      "en": "triggered"
    }
  },
  {
    "key": "description",
    "source": "Use when checking whether every skill leads with its Use-when trigger — the computed convention that a SKILL.md frontmatter description starts with \\\"Use when\\\", measured live as coverage = triggered / total over the real tree.",
    "uuid": "97b0ab8e-c47f-87b2-8e3a-58f457593fa9",
    "words": [
      "use",
      "when",
      "checking",
      "whether",
      "every",
      "skill",
      "leads",
      "with",
      "its",
      "use",
      "when",
      "trigger",
      "the",
      "computed",
      "convention",
      "that",
      "a",
      "skill",
      "md",
      "frontmatter",
      "description",
      "starts",
      "with",
      "use",
      "when",
      "measured",
      "live",
      "as",
      "coverage",
      "triggered",
      "total",
      "over",
      "the",
      "real",
      "tree"
    ],
    "values": {
      "en": "Use when checking whether every skill leads with its Use-when trigger — the computed convention that a SKILL.md frontmatter description starts with \\\"Use when\\\", measured live as coverage = triggered / total over the real tree."
    }
  }
]

export default translations
