// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "pruning",
    "uuid": "eedc66ed-1194-8cde-8175-aa4f2e4ab823",
    "words": [
      "pruning"
    ],
    "values": {
      "en": "pruning"
    }
  },
  {
    "key": "description",
    "source": "Use when plant parts are removed to steer growth, airflow, and fruiting — pruning and suckering (pinching axillary shoots) concentrate the plant's energy into marketable fruit, open the canopy to reduce disease, and shape it to the trellis. Removing growth to improve what remains; the quality/airflow lever on indeterminate fruiting crops.",
    "uuid": "25ce4931-95aa-81f4-95ea-db1854008e37",
    "words": [
      "use",
      "when",
      "plant",
      "parts",
      "are",
      "removed",
      "to",
      "steer",
      "growth",
      "airflow",
      "and",
      "fruiting",
      "pruning",
      "and",
      "suckering",
      "pinching",
      "axillary",
      "shoots",
      "concentrate",
      "the",
      "plant",
      "s",
      "energy",
      "into",
      "marketable",
      "fruit",
      "open",
      "the",
      "canopy",
      "to",
      "reduce",
      "disease",
      "and",
      "shape",
      "it",
      "to",
      "the",
      "trellis",
      "removing",
      "growth",
      "to",
      "improve",
      "what",
      "remains",
      "the",
      "quality",
      "airflow",
      "lever",
      "on",
      "indeterminate",
      "fruiting",
      "crops"
    ],
    "values": {
      "en": "Use when plant parts are removed to steer growth, airflow, and fruiting — pruning and suckering (pinching axillary shoots) concentrate the plant's energy into marketable fruit, open the canopy to reduce disease, and shape it to the trellis. Removing growth to improve what remains; the quality/airflow lever on indeterminate fruiting crops."
    }
  }
]

export default translations
