// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "rate",
    "uuid": "e877b856-8697-887e-bad9-d56eebc3852d",
    "words": [
      "rate"
    ],
    "values": {
      "en": "rate"
    }
  },
  {
    "key": "description",
    "source": "Use when a value is a ratio of two dimensions pinned at a point in time — exchange rate, VAT/tax rate, interest rate, unit price (currency per quantity), wage (currency per hour), throughput/capacity (quantity per hour), run-time-per-unit. The RateConcern; a rate is value-per-unit, pinned at a point; blanks route to the no-op identity (cascade-resolved), never a magic literal.",
    "uuid": "52ea2b5d-141a-85ed-9fa0-27ec228fe665",
    "words": [
      "use",
      "when",
      "a",
      "value",
      "is",
      "a",
      "ratio",
      "of",
      "two",
      "dimensions",
      "pinned",
      "at",
      "a",
      "point",
      "in",
      "time",
      "exchange",
      "rate",
      "vat",
      "tax",
      "rate",
      "interest",
      "rate",
      "unit",
      "price",
      "currency",
      "per",
      "quantity",
      "wage",
      "currency",
      "per",
      "hour",
      "throughput",
      "capacity",
      "quantity",
      "per",
      "hour",
      "run",
      "time",
      "per",
      "unit",
      "the",
      "rateconcern",
      "a",
      "rate",
      "is",
      "value",
      "per",
      "unit",
      "pinned",
      "at",
      "a",
      "point",
      "blanks",
      "route",
      "to",
      "the",
      "no",
      "op",
      "identity",
      "cascade",
      "resolved",
      "never",
      "a",
      "magic",
      "literal"
    ],
    "values": {
      "en": "Use when a value is a ratio of two dimensions pinned at a point in time — exchange rate, VAT/tax rate, interest rate, unit price (currency per quantity), wage (currency per hour), throughput/capacity (quantity per hour), run-time-per-unit. The RateConcern; a rate is value-per-unit, pinned at a point; blanks route to the no-op identity (cascade-resolved), never a magic literal."
    }
  }
]

export default translations
