// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "publication",
    "uuid": "ae0ff3e3-42bb-8c8d-8b76-8cad122a41b2",
    "words": [
      "publication"
    ],
    "values": {
      "en": "publication"
    }
  },
  {
    "key": "description",
    "source": "Use when reasoning about publication — Zenodo v1.0.0 release workflow with permanent DOI and peer-verifiable publication",
    "uuid": "725f356b-9fb1-88cc-b688-bda77f964652",
    "words": [
      "use",
      "when",
      "reasoning",
      "about",
      "publication",
      "zenodo",
      "v1",
      "release",
      "workflow",
      "with",
      "permanent",
      "doi",
      "and",
      "peer",
      "verifiable",
      "publication"
    ],
    "values": {
      "en": "Use when reasoning about publication — Zenodo v1.0.0 release workflow with permanent DOI and peer-verifiable publication"
    }
  }
]

export default translations
