// AUTO-GENERATED by @/translations collect — do not edit.
// Massless projection of the dense core (../translation model + ../message uuid).
// Regenerate: pnpm translations:collect   ·   verify: pnpm translations
import type { Translation } from '@/translation'

export const translations: readonly Translation[] = [
  {
    "key": "name",
    "source": "matter",
    "uuid": "2dea2ab0-c6e4-8977-b1a7-e46ba9dc38f8",
    "words": [
      "matter"
    ],
    "values": {
      "en": "matter"
    }
  },
  {
    "key": "description",
    "source": "Use when confirming a real change rather than the uuid substrate — the payload ⊗ vitepress ⊗ build lane, scoped to the files a turn touched or --full across the corpus.",
    "uuid": "69879511-d74b-81d2-82a3-f935d8edf053",
    "words": [
      "use",
      "when",
      "confirming",
      "a",
      "real",
      "change",
      "rather",
      "than",
      "the",
      "uuid",
      "substrate",
      "the",
      "payload",
      "vitepress",
      "build",
      "lane",
      "scoped",
      "to",
      "the",
      "files",
      "a",
      "turn",
      "touched",
      "or",
      "full",
      "across",
      "the",
      "corpus"
    ],
    "values": {
      "en": "Use when confirming a real change rather than the uuid substrate — the payload ⊗ vitepress ⊗ build lane, scoped to the files a turn touched or --full across the corpus."
    }
  }
]

export default translations
